export const CLOUDFLARE_RUNTIME_LIVENESS_INTERVAL_MS = 5_000;
export const ACTIVE_INVOCATION_HEARTBEAT_STALE_MS = 30_000;
export const ACTIVE_INVOCATION_HEARTBEAT_STALE_MIN_MS =
  ACTIVE_INVOCATION_HEARTBEAT_STALE_MS;
