import type { HostedMemberBillingRef } from "@prisma/client";

export function createHostedBillingRefFixture(
  overrides: Partial<HostedMemberBillingRef> = {},
): HostedMemberBillingRef {
  return {
    memberId: "member_test",
    stripeCustomerLookupKey: null,
    stripeCustomerIdEncrypted: null,
    stripeSubscriptionLookupKey: null,
    stripeSubscriptionIdEncrypted: null,
    stripeSubscriptionScheduleLookupKey: null,
    stripeSubscriptionScheduleIdEncrypted: null,
    stripeCheckoutSessionLookupKey: null,
    stripeCheckoutSessionIdEncrypted: null,
    checkoutAttemptId: null,
    checkoutIntentHash: null,
    checkoutCreatedAt: null,
    stripeEffectClaimId: null,
    stripeEffectKind: null,
    stripeEffectTargetPlanCode: null,
    stripeEffectClaimedAt: null,
    stripeEffectExecutionId: null,
    stripeEffectExecutionStartedAt: null,
    currentBillingPlanCode: null,
    currentBillingPhase: null,
    currentCheckoutOffer: null,
    scheduledBillingPlanCode: null,
    scheduledBillingEffectiveAt: null,
    pulseTrialRedeemedAt: null,
    pulseTrialPolicyVersion: null,
    pulseTrialStartSource: null,
    currentPeriodStart: null,
    currentPeriodEnd: null,
    currentTrialStartedAt: null,
    currentTrialEndsAt: null,
    lastStripeEventCreatedAt: null,
    usagePlanTransitionAt: null,
    usagePlanTransitionFromCode: null,
    usagePlanTransitionKind: null,
    usagePlanTransitionToCode: null,
    createdAt: new Date("2026-09-01T00:00:00.000Z"),
    updatedAt: new Date("2026-09-01T00:00:00.000Z"),
    ...overrides,
  };
}

export const EMPTY_BILLING_REF_SNAPSHOT_FIELDS = {
  checkoutAttemptId: null,
  checkoutCreatedAt: null,
  checkoutIntentHash: null,
  currentBillingPhase: null,
  currentBillingPlanCode: null,
  currentCheckoutOffer: null,
  currentPeriodEnd: null,
  currentPeriodStart: null,
  currentTrialEndsAt: null,
  currentTrialStartedAt: null,
  lastStripeEventCreatedAt: null,
  pulseTrialPolicyVersion: null,
  pulseTrialRedeemedAt: null,
  pulseTrialStartSource: null,
  stripeCheckoutSessionId: null,
  usagePlanTransitionAt: null,
  usagePlanTransitionFromCode: null,
  usagePlanTransitionKind: null,
  usagePlanTransitionToCode: null,
};
