version: 2

updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/apps/*"
      - "/packages/*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "Australia/Sydney"
    open-pull-requests-limit: 8
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
      include: "scope"
    cooldown:
      default-days: 7
    groups:
      version-patch-and-minor:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
        group-by: dependency-name
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
