import path from "node:path";
import { defineConfig } from "vitest/config";

export default defineConfig({
  resolve: {
    alias: [
      { find: "@murph/contracts", replacement: path.resolve("packages/contracts/src/index.ts") },
      { find: "@murph/hosted-execution", replacement: path.resolve("packages/hosted-execution/src/index.ts") },
      { find: "@murph/runtime-state", replacement: path.resolve("packages/runtime-state/src/index.ts") },
      { find: "@murph/core", replacement: path.resolve("packages/core/src/index.ts") },
      { find: "@murph/importers", replacement: path.resolve("packages/importers/src/index.ts") },
      { find: "@murph/device-syncd", replacement: path.resolve("packages/device-syncd/src/index.ts") },
      { find: "@murph/inboxd", replacement: path.resolve("packages/inboxd/src/index.ts") },
      { find: "@murph/parsers", replacement: path.resolve("packages/parsers/src/index.ts") },
      { find: "@murph/query", replacement: path.resolve("packages/query/src/index.ts") },
      { find: /^murph\/assistant\/store$/, replacement: path.resolve("packages/cli/src/assistant/store.ts") },
      { find: /^murph\/operator-config$/, replacement: path.resolve("packages/cli/src/operator-config.ts") },
      { find: /^murph$/, replacement: path.resolve("packages/cli/src/index.ts") },
    ],
  },
  test: {
    environment: "node",
    fileParallelism: false,
    include: [
      "packages/core/test/canonical-mutations-boundary.test.ts",
      "packages/core/test/core.test.ts",
      "packages/core/test/device-import.test.ts",
      "packages/core/test/health-bank.test.ts",
      "packages/core/test/profile.test.ts",
      "packages/core/test/share-pack.test.ts",
      "packages/core/test/health-history-family.test.ts",
      "packages/core/test/ids.test.ts",
      "packages/importers/test/device-providers.test.ts",
      "packages/importers/test/importers.test.ts",
      "packages/importers/test/input-validation.test.ts",
      "packages/hosted-execution/test/hosted-execution.test.ts",
      "packages/runtime-state/test/hosted-bundle.test.ts",
      "packages/runtime-state/test/hosted-execution-reexport.test.ts",
      "packages/runtime-state/test/hosted-user-env.test.ts",
      "packages/runtime-state/test/ulid.test.ts",
      "packages/device-syncd/test/config.test.ts",
      "packages/device-syncd/test/http.test.ts",
      "packages/device-syncd/test/oura-provider.test.ts",
      "packages/device-syncd/test/oura-webhooks.test.ts",
      "packages/device-syncd/test/service.test.ts",
      "packages/device-syncd/test/shared-ids.test.ts",
      "packages/device-syncd/test/whoop-provider.test.ts",
      "packages/inboxd/test/connectors-daemon.test.ts",
      "packages/inboxd/test/email-connector.test.ts",
      "packages/inboxd/test/idempotency-rebuild.test.ts",
      "packages/inboxd/test/inboxd.test.ts",
      "packages/inboxd/test/shared-ids.test.ts",
      "packages/parsers/test/parsers.test.ts",
      "packages/query/test/health-tail.test.ts",
      "packages/query/test/query.test.ts",
      "packages/cli/test/health-tail.test.ts",
      "packages/cli/test/canonical-write-lock.test.ts",
      "packages/cli/test/canonical-write-source-audit.test.ts",
      "packages/cli/test/assistant-harness.test.ts",
      "packages/cli/test/assistant-state.test.ts",
      "packages/cli/test/assistant-provider.test.ts",
      "packages/cli/test/assistant-codex.test.ts",
      "packages/cli/test/assistant-cli-access.test.ts",
      "packages/cli/test/assistant-channel.test.ts",
      "packages/cli/test/assistant-chat-theme.test.ts",
      "packages/cli/test/assistant-runtime.test.ts",
      "packages/cli/test/assistant-cli.test.ts",
      "packages/cli/test/assistant-observability.test.ts",
      "packages/cli/test/assistant-robustness.test.ts",
      "packages/cli/test/assistant-service.test.ts",
      "packages/cli/test/device-daemon.test.ts",
      "packages/cli/test/device-sync-client.test.ts",
      "packages/cli/test/json-input.test.ts",
      "packages/cli/test/incur-smoke.test.ts",
      "packages/cli/test/canonical-mutation-boundary.test.ts",
      "packages/cli/test/inbox-incur-smoke.test.ts",
      "packages/cli/test/inbox-cli.test.ts",
      "packages/cli/test/inbox-model-harness.test.ts",
      "packages/cli/test/inbox-model-route.test.ts",
      "packages/cli/test/list-cursor-compat.test.ts",
      "packages/cli/test/cli-expansion-export-intake.test.ts",
      "packages/cli/test/cli-expansion-workout.test.ts",
      "packages/cli/test/runtime.test.ts",
      "packages/cli/test/search-runtime.test.ts",
      "packages/cli/test/setup-channels.test.ts",
      "packages/cli/test/setup-cli.test.ts",
      "packages/cli/test/selector-filter-normalization.test.ts",
      "packages/cli/test/stdin-input.test.ts",
      "packages/cli/test/vault-usecase-helpers.test.ts",
      "packages/cli/test/release-script-coverage-audit.test.ts",
      "packages/cli/test/release-workflow-guards.test.ts",
      "packages/assistant-runtime/test/hosted-email-route.test.ts",
    ],
    coverage: {
      enabled: true,
      provider: "v8",
      clean: false,
      reporter: ["text", "lcov"],
      reportsDirectory: "./coverage",
      include: [
        "packages/core/src/constants.ts",
        "packages/core/src/ids.ts",
        "packages/core/src/jsonl.ts",
        "packages/core/src/mutations.ts",
        "packages/core/src/raw.ts",
        "packages/core/src/vault.ts",
        "packages/importers/src/csv-sample-importer.ts",
        "packages/importers/src/document-importer.ts",
        "packages/importers/src/meal-importer.ts",
        "packages/hosted-execution/src/**/*.ts",
        "packages/query/src/export-pack.ts",
        "packages/query/src/model.ts",
        "packages/query/src/search.ts",
        "packages/query/src/search-sqlite.ts",
        "packages/query/src/summaries.ts",
        "packages/query/src/timeline.ts",
      ],
      exclude: [
        "coverage/**",
        "dist/**",
        "packages/inboxd/src/**",
        "packages/parsers/src/**",
        "**/*.d.ts",
      ],
      thresholds: {
        perFile: true,
        lines: 85,
        functions: 85,
        branches: 80,
        statements: 85,
      },
    },
    testTimeout: 60_000,
  },
});
