import {
  HOSTED_EXECUTION_DEVICE_SYNC_PASS_JOB_LIMIT,
} from "@murphai/device-syncd/hosted-runtime";

export const HOSTED_DEVICE_SYNC_DIRTY_PENDING_FETCH_LIMIT = 10;
export const HOSTED_DEVICE_SYNC_PASS_JOB_LIMIT =
  HOSTED_EXECUTION_DEVICE_SYNC_PASS_JOB_LIMIT;
