import { describe, expect, it } from "vitest";

import {
  ADVERSE_EFFECT_SEVERITIES as CONTRACT_ADVERSE_EFFECT_SEVERITIES,
  ALLERGY_CRITICALITIES as CONTRACT_ALLERGY_CRITICALITIES,
  ALLERGY_STATUSES as CONTRACT_ALLERGY_STATUSES,
  ASSESSMENT_SOURCES as CONTRACT_ASSESSMENT_SOURCES,
  CONDITION_CLINICAL_STATUSES as CONTRACT_CONDITION_CLINICAL_STATUSES,
  CONDITION_SEVERITIES as CONTRACT_CONDITION_SEVERITIES,
  CONDITION_VERIFICATION_STATUSES as CONTRACT_CONDITION_VERIFICATION_STATUSES,
  CONTRACT_SCHEMA_VERSION,
  FOOD_STATUSES as CONTRACT_FOOD_STATUSES,
  FRONTMATTER_DOC_TYPES,
  GOAL_HORIZONS as CONTRACT_GOAL_HORIZONS,
  GOAL_STATUSES as CONTRACT_GOAL_STATUSES,
  PROFILE_SNAPSHOT_SOURCES as CONTRACT_PROFILE_SNAPSHOT_SOURCES,
  PROTOCOL_KINDS as CONTRACT_PROTOCOL_KINDS,
  PROTOCOL_STATUSES as CONTRACT_PROTOCOL_STATUSES,
  RECIPE_STATUSES as CONTRACT_RECIPE_STATUSES,
  TEST_RESULT_STATUSES as CONTRACT_TEST_RESULT_STATUSES,
  WORKOUT_FORMAT_STATUSES as CONTRACT_WORKOUT_FORMAT_STATUSES,
} from "@murph/contracts";

import {
  ASSESSMENT_RESPONSE_SCHEMA_VERSION,
  ASSESSMENT_SOURCES,
} from "../src/assessment/types.ts";
import {
  ALLERGY_CRITICALITIES,
  ALLERGY_DOC_TYPE,
  ALLERGY_SCHEMA_VERSION,
  ALLERGY_STATUSES,
  CONDITION_CLINICAL_STATUSES,
  CONDITION_DOC_TYPE,
  CONDITION_SCHEMA_VERSION,
  CONDITION_SEVERITIES,
  CONDITION_VERIFICATION_STATUSES,
  FOOD_DOC_TYPE,
  FOOD_SCHEMA_VERSION,
  FOOD_STATUSES,
  GOAL_DOC_TYPE,
  GOAL_HORIZONS,
  GOAL_SCHEMA_VERSION,
  GOAL_STATUSES,
  PROTOCOL_DOC_TYPE,
  PROTOCOL_KINDS,
  PROTOCOL_SCHEMA_VERSION,
  PROTOCOL_STATUSES,
  RECIPE_DOC_TYPE,
  RECIPE_SCHEMA_VERSION,
  RECIPE_STATUSES,
  WORKOUT_FORMAT_DOC_TYPE,
  WORKOUT_FORMAT_SCHEMA_VERSION,
  WORKOUT_FORMAT_STATUSES,
} from "../src/bank/types.ts";
import {
  ADVERSE_EFFECT_SEVERITIES,
  TEST_STATUSES,
} from "../src/history/types.ts";
import {
  PROFILE_CURRENT_DOC_TYPE,
  PROFILE_CURRENT_SCHEMA_VERSION,
  PROFILE_SNAPSHOT_SCHEMA_VERSION,
  PROFILE_SNAPSHOT_SOURCES,
} from "../src/profile/types.ts";

describe("shared contract model alignment", () => {
  it("reuses contract-owned bank enums and document ids", () => {
    expect(GOAL_SCHEMA_VERSION).toBe(CONTRACT_SCHEMA_VERSION.goalFrontmatter);
    expect(GOAL_DOC_TYPE).toBe(FRONTMATTER_DOC_TYPES.goal);
    expect(GOAL_STATUSES).toBe(CONTRACT_GOAL_STATUSES);
    expect(GOAL_HORIZONS).toBe(CONTRACT_GOAL_HORIZONS);

    expect(CONDITION_SCHEMA_VERSION).toBe(CONTRACT_SCHEMA_VERSION.conditionFrontmatter);
    expect(CONDITION_DOC_TYPE).toBe(FRONTMATTER_DOC_TYPES.condition);
    expect(CONDITION_CLINICAL_STATUSES).toBe(CONTRACT_CONDITION_CLINICAL_STATUSES);
    expect(CONDITION_VERIFICATION_STATUSES).toBe(CONTRACT_CONDITION_VERIFICATION_STATUSES);
    expect(CONDITION_SEVERITIES).toBe(CONTRACT_CONDITION_SEVERITIES);

    expect(ALLERGY_SCHEMA_VERSION).toBe(CONTRACT_SCHEMA_VERSION.allergyFrontmatter);
    expect(ALLERGY_DOC_TYPE).toBe(FRONTMATTER_DOC_TYPES.allergy);
    expect(ALLERGY_STATUSES).toBe(CONTRACT_ALLERGY_STATUSES);
    expect(ALLERGY_CRITICALITIES).toBe(CONTRACT_ALLERGY_CRITICALITIES);

    expect(PROTOCOL_SCHEMA_VERSION).toBe(CONTRACT_SCHEMA_VERSION.protocolFrontmatter);
    expect(PROTOCOL_DOC_TYPE).toBe(FRONTMATTER_DOC_TYPES.protocol);
    expect(PROTOCOL_KINDS).toBe(CONTRACT_PROTOCOL_KINDS);
    expect(PROTOCOL_STATUSES).toBe(CONTRACT_PROTOCOL_STATUSES);

    expect(RECIPE_SCHEMA_VERSION).toBe(CONTRACT_SCHEMA_VERSION.recipeFrontmatter);
    expect(RECIPE_DOC_TYPE).toBe(FRONTMATTER_DOC_TYPES.recipe);
    expect(RECIPE_STATUSES).toBe(CONTRACT_RECIPE_STATUSES);

    expect(FOOD_SCHEMA_VERSION).toBe(CONTRACT_SCHEMA_VERSION.foodFrontmatter);
    expect(FOOD_DOC_TYPE).toBe(FRONTMATTER_DOC_TYPES.food);
    expect(FOOD_STATUSES).toBe(CONTRACT_FOOD_STATUSES);

    expect(WORKOUT_FORMAT_SCHEMA_VERSION).toBe(CONTRACT_SCHEMA_VERSION.workoutFormatFrontmatter);
    expect(WORKOUT_FORMAT_DOC_TYPE).toBe(FRONTMATTER_DOC_TYPES.workoutFormat);
    expect(WORKOUT_FORMAT_STATUSES).toBe(CONTRACT_WORKOUT_FORMAT_STATUSES);
  });

  it("reuses contract-owned ledger enums and schema ids", () => {
    expect(ASSESSMENT_RESPONSE_SCHEMA_VERSION).toBe(CONTRACT_SCHEMA_VERSION.assessmentResponse);
    expect(ASSESSMENT_SOURCES).toBe(CONTRACT_ASSESSMENT_SOURCES);

    expect(PROFILE_SNAPSHOT_SCHEMA_VERSION).toBe(CONTRACT_SCHEMA_VERSION.profileSnapshot);
    expect(PROFILE_CURRENT_SCHEMA_VERSION).toBe(CONTRACT_SCHEMA_VERSION.profileCurrentFrontmatter);
    expect(PROFILE_CURRENT_DOC_TYPE).toBe(FRONTMATTER_DOC_TYPES.profileCurrent);
    expect(PROFILE_SNAPSHOT_SOURCES).toBe(CONTRACT_PROFILE_SNAPSHOT_SOURCES);

    expect(TEST_STATUSES).toBe(CONTRACT_TEST_RESULT_STATUSES);
    expect(ADVERSE_EFFECT_SEVERITIES).toBe(CONTRACT_ADVERSE_EFFECT_SEVERITIES);
  });
});
