import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  HOSTED_WORKER_OPTIONAL_VAR_NAMES,
  HOSTED_WORKER_REQUIRED_VAR_NAMES,
} from "../../apps/cloudflare/scripts/deploy-automation/worker-optional-vars.ts";

const scriptsDir = path.dirname(fileURLToPath(import.meta.url));

export const repoRoot = path.resolve(scriptsDir, "..", "..");
export const webDir = path.join(repoRoot, "apps", "web");
export const cloudflareDir = path.join(repoRoot, "apps", "cloudflare");
export const cloudflareDevVarsPath = path.join(cloudflareDir, ".dev.vars");
export const vercelLinkCandidatePaths = [
  path.join(webDir, ".vercel", "project.json"),
  path.join(webDir, ".vercel", "repo.json"),
  path.join(repoRoot, ".vercel", "project.json"),
  path.join(repoRoot, ".vercel", "repo.json"),
] as const;

export const DEFAULT_WEB_HOST = "localhost";
export const DEFAULT_WEB_PORT = 3000;
export const DEFAULT_WORKER_HOST = "127.0.0.1";
export const DEFAULT_WORKER_PORT = 8787;
export const DEFAULT_WORKER_PROTOCOL = "http";
export const DEFAULT_WORKER_PERSIST_DIR = path.join(".wrangler", "state", "dev-root");
export const DEFAULT_STRIPE_ENV_FILE = path.join(".tmp", ".env.hosted-local-stripe");
export const DEFAULT_LINQ_WEBHOOK_TUNNEL_CONFIG = path.join(
  ".tmp",
  "cloudflared-linq-webhook.yml",
);
export const DEFAULT_LINQ_WEBHOOK_REGISTRATION_CACHE = path.join(
  ".tmp",
  "linq-webhook-registration.json",
);
export const HOSTED_LOCAL_DEV_CRYPTO_STATE_FILE = path.join(
  ".tmp",
  "hosted-local-dev-crypto-state.dev.vars",
);
export const DEFAULT_LINQ_WEBHOOK_TUNNEL_NAME = "dev";
export const DEFAULT_DATABASE_URL = "postgresql://postgres:postgres@127.0.0.1:5432/murph_device_sync";
// Local Cloudflare startup can include a full runner bundle build and cold container prep.
export const HEALTH_TIMEOUT_MS = 300_000;
export const HEALTH_POLL_INTERVAL_MS = 500;
export const HEALTH_REQUEST_TIMEOUT_MS = 20_000;
export const HOSTED_WEB_DEV_DIST_DIR = ".next-dev";
export const HOSTED_WEB_SMOKE_DIST_DIR = ".next-smoke";
export const HOSTED_RUNNER_LOCAL_BUILD_ID_ENV = "MURPH_HOSTED_RUNNER_LOCAL_BUILD_ID";
export const USE_REMOTE_HOSTED_CRYPTO_KEYS_ENV = "MURPH_DEV_USE_REMOTE_HOSTED_CRYPTO_KEYS";
export const HOSTED_RUNTIME_CODEX_APP_SERVER_STUB_BASE_URL_ENV =
  "MURPH_E2E_CODEX_APP_SERVER_STUB_BASE_URL";
export const HOSTED_RUNTIME_CODEX_APP_SERVER_STUB_EXPECT_DYNAMIC_TOOLS_ENV =
  "MURPH_E2E_CODEX_APP_SERVER_STUB_EXPECT_DYNAMIC_TOOLS";
export const HOSTED_RUNTIME_CODEX_APP_SERVER_STUB_TURN_DELAY_MS_ENV =
  "MURPH_E2E_CODEX_APP_SERVER_STUB_TURN_DELAY_MS";
export const HOSTED_RUNTIME_CODEX_MODEL_PROVIDER_BASE_URL_ENV =
  "HOSTED_RUNTIME_CODEX_MODEL_PROVIDER_BASE_URL";
export const WRANGLER_LOCAL_ENV_FILE_ONLY_NAMES = [] as const;
export const HOSTED_LOCAL_R2_PRESIGN_ACCESS_KEY_ID = "hosted-local-r2-access-key";
export const HOSTED_LOCAL_R2_PRESIGN_ACCOUNT_ID = "hosted-local-r2-account";
export const HOSTED_LOCAL_R2_PRESIGN_BUCKET_NAME = "hosted-local-r2-bundles";
export const HOSTED_LOCAL_R2_PRESIGN_SECRET_ACCESS_KEY = "hosted-local-r2-secret-key";

// Persisted for interactive hosted-local state even when the value is web-only
// or otherwise not declared in generated Wrangler config.
export const HOSTED_LOCAL_STATE_ONLY_ENV_NAMES = [
  "HOSTED_CRYPTO_AUTHORITY_VERIFY_KEYRING_JSON",
  "HOSTED_CRYPTO_CLOUDFLARE_AUTOMATION_PUBLIC_JWK",
  "HOSTED_CRYPTO_GCP_AUTHORITY_SIGN_KEY_VERSION",
  "HOSTED_CRYPTO_GCP_AUTHORITY_SIGN_PUBLIC_KEY_PEM",
  "HOSTED_CRYPTO_GCP_KMS_API_ROOT",
  "HOSTED_CRYPTO_GCP_WEB_WRAP_KEY_NAME",
  "HOSTED_CRYPTO_LOCAL_AUTHORITY_SIGN_PRIVATE_JWK",
  "HOSTED_CRYPTO_LOCAL_KMS_WRAP_KEY",
  "HOSTED_WEB_CALLBACK_SIGNING_PUBLIC_KEYRING_JSON",
  "HOSTED_DEVICE_ROUTING_INDEX_KEY",
] as const;

export const HOSTED_LOCAL_PERSISTED_STATE_ENV_NAMES = [
  "HOSTED_CRYPTO_AUTHORITY_SIGN_KEY_VERSION",
  "HOSTED_CRYPTO_AUTHORITY_SIGN_PUBLIC_KEY_PEM",
  "HOSTED_CRYPTO_AUTHORITY_VERIFY_KEYRING_JSON",
  "HOSTED_CRYPTO_CLOUDFLARE_AUTOMATION_KEY_ID",
  "HOSTED_CRYPTO_CLOUDFLARE_AUTOMATION_PRIVATE_JWK",
  "HOSTED_CRYPTO_CLOUDFLARE_AUTOMATION_PUBLIC_JWK",
  "HOSTED_CRYPTO_ENV",
  "HOSTED_CRYPTO_GCP_AUTHORITY_SIGN_KEY_VERSION",
  "HOSTED_CRYPTO_GCP_AUTHORITY_SIGN_PUBLIC_KEY_PEM",
  "HOSTED_CRYPTO_GCP_KMS_API_ROOT",
  "HOSTED_CRYPTO_GCP_WEB_WRAP_KEY_NAME",
  "HOSTED_CRYPTO_LOCAL_AUTHORITY_SIGN_PRIVATE_JWK",
  "HOSTED_CRYPTO_LOCAL_KMS_WRAP_KEY",
  "HOSTED_DEVICE_ROUTING_INDEX_KEY",
  "HOSTED_WEB_CALLBACK_SIGNING_KEY_ID",
  "HOSTED_WEB_CALLBACK_SIGNING_PRIVATE_JWK",
  "HOSTED_WEB_CALLBACK_SIGNING_PUBLIC_KEYRING_JSON",
] as const;

export const WRANGLER_VAR_ALLOWLIST = [
  ...HOSTED_WORKER_REQUIRED_VAR_NAMES,
  ...HOSTED_WORKER_OPTIONAL_VAR_NAMES,
  "LINQ_ATTACHMENT_CDN_BASE_URL",
  HOSTED_RUNTIME_CODEX_APP_SERVER_STUB_BASE_URL_ENV,
  HOSTED_RUNTIME_CODEX_APP_SERVER_STUB_EXPECT_DYNAMIC_TOOLS_ENV,
  HOSTED_RUNTIME_CODEX_APP_SERVER_STUB_TURN_DELAY_MS_ENV,
  HOSTED_RUNTIME_CODEX_MODEL_PROVIDER_BASE_URL_ENV,
  "MURPH_HOSTED_LOCAL_E2E_ISOLATION_REQUIRED",
  "MURPH_HOSTED_LOCAL_PROFILE",
  "MURPH_HOSTED_LOCAL_R2_DOCKER_BRIDGE_HOST",
  "MURPH_HOSTED_LOCAL_TEST_ROUTES",
  "NODE_ENV",
  "HOSTED_LOCAL_E2E_PARSER_TOOLCHAIN",
  "FFMPEG_COMMAND",
  "WHISPER_COMMAND",
  "WHISPER_MODEL_PATH",
  "HOSTED_EXECUTION_ALLOWED_USER_ENV_KEYS",
  "HOSTED_EXECUTION_IDLE_CHECKPOINT_DELAY_MS",
  "HOSTED_EXECUTION_MAX_EVENT_ATTEMPTS",
  "HOSTED_EXECUTION_RETRY_DELAY_MS",
  "HOSTED_EXECUTION_RUNNER_COMMIT_TIMEOUT_MS",
  "HOSTED_EXECUTION_RUNNER_HOST_ALIAS",
  "HOSTED_EXECUTION_RUNNER_READY_TIMEOUT_MS",
  "HOSTED_EXECUTION_RUNNER_TIMEOUT_MS",
  "HOSTED_EXECUTION_VERCEL_OIDC_ENVIRONMENT",
  "HOSTED_EXECUTION_VERCEL_OIDC_JWKS_URL",
  "HOSTED_EXECUTION_VERCEL_OIDC_PROJECT_NAME",
  "HOSTED_EXECUTION_VERCEL_OIDC_TEAM_SLUG",
  "HOSTED_R2_PRESIGN_ALLOW_LOCAL_ENDPOINT",
  "HOSTED_R2_PRESIGN_CONTROL_ENDPOINT",
  "HOSTED_WEB_BASE_URL",
  "HOSTED_WEB_CALLBACK_SIGNING_KEY_ID",
] as const satisfies readonly string[];
