import { readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Lists the goal illustrations checked into public/design-assets/goals so
// cards can render them without touching the filesystem at request time.
// Run after adding or removing illustrations:
//   pnpm --dir ../.. exec tsx apps/web/scripts/generate-goal-illustration-manifest.ts

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const packageDir = path.resolve(scriptDir, "..");
const illustrationDir = path.join(packageDir, "public/design-assets/goals");
const manifestPath = path.join(
  packageDir,
  "src/lib/goals/goal-illustrations.generated.ts",
);

const routeIds = readdirSync(illustrationDir)
  .filter((file) => file.endsWith(".svg"))
  .map((file) => file.slice(0, -".svg".length))
  .sort();

const manifest = [
  "// Generated by scripts/generate-goal-illustration-manifest.ts. Do not edit.",
  "",
  "export const GOAL_ILLUSTRATION_ROUTE_IDS: ReadonlySet<string> = new Set([",
  ...routeIds.map((routeId) => `  ${JSON.stringify(routeId)},`),
  "]);",
  "",
].join("\n");

writeFileSync(manifestPath, manifest);
console.log(`Wrote ${routeIds.length} goal illustration route ids to ${path.relative(packageDir, manifestPath)}.`);
