import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { loadChangelogFragmentEditions } from "../src/lib/changelog-fragments";

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

export function generateChangelogFragments(options: {
  contentRoot?: string;
  outputFile?: string;
} = {}): boolean {
  const contentRoot = options.contentRoot ?? path.join(appRoot, "changelog");
  const outputFile = options.outputFile
    ?? path.join(appRoot, "src/lib/changelog-fragments.generated.ts");
  const editions = loadChangelogFragmentEditions(contentRoot);
  const output = [
    "// Generated by apps/web/scripts/generate-changelog-fragments.ts.",
    "// Do not edit or commit this file; edit apps/web/changelog fragments instead.",
    `const CHANGELOG_FRAGMENT_EDITIONS = ${JSON.stringify(editions, null, 2)} as const;`,
    "",
    "export default CHANGELOG_FRAGMENT_EDITIONS;",
    "",
  ].join("\n");

  if (existsSync(outputFile) && readFileSync(outputFile, "utf8") === output) {
    return false;
  }
  writeFileSync(outputFile, output, "utf8");
  return true;
}

const isDirectRun = typeof process.argv[1] === "string"
  && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isDirectRun) {
  generateChangelogFragments();
}
