import { spawnSync } from "node:child_process";
import process from "node:process";

import {
  hostedWebProductionPrismaGenerateCommand,
  shouldRunHostedWebProductionMigrations,
  type HostedWebProductionMigrationEnvironment,
  type HostedWebProductionMigrationRunner,
} from "./run-production-migrations";

const prismaGeneratedByMigrationsFlag =
  "MURPH_HOSTED_WEB_PRISMA_GENERATED_BY_MIGRATIONS";

export async function prepareHostedWebPrismaClientForBuild(
  environment: HostedWebProductionMigrationEnvironment = process.env,
  runCommand: HostedWebProductionMigrationRunner = runCommandInherited,
): Promise<"generated" | "reused"> {
  const handoff = environment[prismaGeneratedByMigrationsFlag];
  if (handoff !== undefined && handoff !== "0" && handoff !== "1") {
    throw new Error(`${prismaGeneratedByMigrationsFlag} must be 0 or 1 when set.`);
  }

  if (handoff === "1" && shouldRunHostedWebProductionMigrations(environment)) {
    console.log("Reusing the Prisma client generated by the production migration step.");
    return "reused";
  }

  if (handoff === "1") {
    console.log("Ignoring the production Prisma handoff outside a main-branch Vercel production deploy.");
  }
  await runCommand(
    hostedWebProductionPrismaGenerateCommand.command,
    hostedWebProductionPrismaGenerateCommand.args,
  );
  return "generated";
}

function runCommandInherited(
  command: string,
  args: readonly string[],
): Promise<void> {
  const result = spawnSync(command, [...args], {
    cwd: new URL("../../../", import.meta.url),
    env: process.env,
    stdio: "inherit",
  });

  if (result.error) {
    throw result.error;
  }
  if (result.status !== 0) {
    throw new Error(
      `${command} ${args.join(" ")} failed with ${result.signal ?? `exit code ${result.status ?? "unknown"}`}.`,
    );
  }
  return Promise.resolve();
}

if (process.argv[1] === new URL(import.meta.url).pathname) {
  prepareHostedWebPrismaClientForBuild().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  });
}
