import {
  DEVICE_SYNC_CONTROL_TOKEN_ENV_KEYS,
  DEVICE_SYNC_SECRET_ENV_KEYS,
} from "../client.ts";

export { DEVICE_SYNC_CONTROL_TOKEN_ENV_KEYS, DEVICE_SYNC_SECRET_ENV_KEYS };

export const DEVICE_SYNC_ALLOWED_RETURN_ORIGINS_ENV_KEYS = [
  "DEVICE_SYNC_ALLOWED_RETURN_ORIGINS",
] as const;
export const DEVICE_SYNC_HOST_ENV_KEYS = ["DEVICE_SYNC_HOST"] as const;
export const DEVICE_SYNC_PORT_ENV_KEYS = ["DEVICE_SYNC_PORT"] as const;
export const DEVICE_SYNC_PUBLIC_BASE_URL_ENV_KEYS = [
  "DEVICE_SYNC_PUBLIC_BASE_URL",
] as const;
export const DEVICE_SYNC_PUBLIC_HOST_ENV_KEYS = [
  "DEVICE_SYNC_PUBLIC_HOST",
] as const;
export const DEVICE_SYNC_PUBLIC_PORT_ENV_KEYS = [
  "DEVICE_SYNC_PUBLIC_PORT",
] as const;
export const DEVICE_SYNC_SCHEDULER_POLL_MS_ENV_KEYS = [
  "DEVICE_SYNC_SCHEDULER_POLL_MS",
] as const;
export const DEVICE_SYNC_SESSION_TTL_MS_ENV_KEYS = [
  "DEVICE_SYNC_SESSION_TTL_MS",
] as const;
export const DEVICE_SYNC_STATE_DB_PATH_ENV_KEYS = [
  "DEVICE_SYNC_STATE_DB_PATH",
] as const;
export const DEVICE_SYNC_VAULT_ROOT_ENV_KEYS = ["DEVICE_SYNC_VAULT_ROOT"] as const;
export const DEVICE_SYNC_WORKER_BATCH_SIZE_ENV_KEYS = [
  "DEVICE_SYNC_WORKER_BATCH_SIZE",
] as const;
export const DEVICE_SYNC_WORKER_LEASE_MS_ENV_KEYS = [
  "DEVICE_SYNC_WORKER_LEASE_MS",
] as const;
export const DEVICE_SYNC_WORKER_POLL_MS_ENV_KEYS = [
  "DEVICE_SYNC_WORKER_POLL_MS",
] as const;
export const GARMIN_API_BASE_URL_ENV_KEYS = ["GARMIN_API_BASE_URL"] as const;
export const GARMIN_AUTH_BASE_URL_ENV_KEYS = ["GARMIN_AUTH_BASE_URL"] as const;
export const GARMIN_BACKFILL_DAYS_ENV_KEYS = ["GARMIN_BACKFILL_DAYS"] as const;
export const GARMIN_CLIENT_ID_ENV_KEYS = ["GARMIN_CLIENT_ID"] as const;
export const GARMIN_CLIENT_SECRET_ENV_KEYS = ["GARMIN_CLIENT_SECRET"] as const;
export const GARMIN_TOKEN_BASE_URL_ENV_KEYS = ["GARMIN_TOKEN_BASE_URL"] as const;
export const GARMIN_RECONCILE_DAYS_ENV_KEYS = [
  "GARMIN_RECONCILE_DAYS",
] as const;
export const GARMIN_RECONCILE_INTERVAL_MS_ENV_KEYS = [
  "GARMIN_RECONCILE_INTERVAL_MS",
] as const;
export const GARMIN_REQUEST_TIMEOUT_MS_ENV_KEYS = [
  "GARMIN_REQUEST_TIMEOUT_MS",
] as const;
export const OURA_API_BASE_URL_ENV_KEYS = ["OURA_API_BASE_URL"] as const;
export const OURA_AUTH_BASE_URL_ENV_KEYS = ["OURA_AUTH_BASE_URL"] as const;
export const OURA_BACKFILL_DAYS_ENV_KEYS = ["OURA_BACKFILL_DAYS"] as const;
export const OURA_CLIENT_ID_ENV_KEYS = ["OURA_CLIENT_ID"] as const;
export const OURA_CLIENT_SECRET_ENV_KEYS = ["OURA_CLIENT_SECRET"] as const;
export const OURA_WEBHOOK_VERIFICATION_TOKEN_ENV_KEYS = ["OURA_WEBHOOK_VERIFICATION_TOKEN"] as const;
export const OURA_RECONCILE_DAYS_ENV_KEYS = [
  "OURA_RECONCILE_DAYS",
] as const;
export const OURA_RECONCILE_INTERVAL_MS_ENV_KEYS = [
  "OURA_RECONCILE_INTERVAL_MS",
] as const;
export const OURA_REQUEST_TIMEOUT_MS_ENV_KEYS = [
  "OURA_REQUEST_TIMEOUT_MS",
] as const;
export const OURA_SCOPES_ENV_KEYS = ["OURA_SCOPES"] as const;
export const OURA_WEBHOOK_TIMESTAMP_TOLERANCE_MS_ENV_KEYS = [
  "OURA_WEBHOOK_TIMESTAMP_TOLERANCE_MS",
] as const;
export const WHOOP_BACKFILL_DAYS_ENV_KEYS = ["WHOOP_BACKFILL_DAYS"] as const;
export const WHOOP_BASE_URL_ENV_KEYS = ["WHOOP_BASE_URL"] as const;
export const WHOOP_CLIENT_ID_ENV_KEYS = ["WHOOP_CLIENT_ID"] as const;
export const WHOOP_CLIENT_SECRET_ENV_KEYS = ["WHOOP_CLIENT_SECRET"] as const;
export const WHOOP_RECONCILE_DAYS_ENV_KEYS = [
  "WHOOP_RECONCILE_DAYS",
] as const;
export const WHOOP_RECONCILE_INTERVAL_MS_ENV_KEYS = [
  "WHOOP_RECONCILE_INTERVAL_MS",
] as const;
export const WHOOP_REQUEST_TIMEOUT_MS_ENV_KEYS = [
  "WHOOP_REQUEST_TIMEOUT_MS",
] as const;
export const WHOOP_SCOPES_ENV_KEYS = ["WHOOP_SCOPES"] as const;
export const WHOOP_WEBHOOK_TIMESTAMP_TOLERANCE_MS_ENV_KEYS = [
  "WHOOP_WEBHOOK_TIMESTAMP_TOLERANCE_MS",
] as const;
export const STRAVA_API_BASE_URL_ENV_KEYS = ["STRAVA_API_BASE_URL"] as const;
export const STRAVA_AUTH_BASE_URL_ENV_KEYS = ["STRAVA_AUTH_BASE_URL"] as const;
export const STRAVA_BACKFILL_DAYS_ENV_KEYS = ["STRAVA_BACKFILL_DAYS"] as const;
export const STRAVA_CLIENT_ID_ENV_KEYS = ["STRAVA_CLIENT_ID"] as const;
export const STRAVA_CLIENT_SECRET_ENV_KEYS = ["STRAVA_CLIENT_SECRET"] as const;
export const STRAVA_RECONCILE_DAYS_ENV_KEYS = [
  "STRAVA_RECONCILE_DAYS",
] as const;
export const STRAVA_RECONCILE_INTERVAL_MS_ENV_KEYS = [
  "STRAVA_RECONCILE_INTERVAL_MS",
] as const;
export const STRAVA_REQUEST_TIMEOUT_MS_ENV_KEYS = [
  "STRAVA_REQUEST_TIMEOUT_MS",
] as const;
export const STRAVA_SCOPES_ENV_KEYS = ["STRAVA_SCOPES"] as const;
export const STRAVA_WEBHOOK_VERIFY_TOKEN_ENV_KEYS = [
  "STRAVA_WEBHOOK_VERIFY_TOKEN",
] as const;

const GARMIN_DEVICE_SYNC_PROVIDER_RUNTIME_SECRET_ENV_KEYS = [
  ...GARMIN_CLIENT_ID_ENV_KEYS,
  ...GARMIN_CLIENT_SECRET_ENV_KEYS,
] as const;
const GARMIN_DEVICE_SYNC_PROVIDER_RUNTIME_VARIABLE_ENV_KEYS = [
  ...GARMIN_API_BASE_URL_ENV_KEYS,
  ...GARMIN_AUTH_BASE_URL_ENV_KEYS,
  ...GARMIN_BACKFILL_DAYS_ENV_KEYS,
  ...GARMIN_RECONCILE_DAYS_ENV_KEYS,
  ...GARMIN_RECONCILE_INTERVAL_MS_ENV_KEYS,
  ...GARMIN_REQUEST_TIMEOUT_MS_ENV_KEYS,
  ...GARMIN_TOKEN_BASE_URL_ENV_KEYS,
] as const;
const OURA_DEVICE_SYNC_PROVIDER_RUNTIME_SECRET_ENV_KEYS = [
  ...OURA_CLIENT_ID_ENV_KEYS,
  ...OURA_CLIENT_SECRET_ENV_KEYS,
] as const;
const OURA_DEVICE_SYNC_PROVIDER_RUNTIME_VARIABLE_ENV_KEYS = [
  ...OURA_API_BASE_URL_ENV_KEYS,
  ...OURA_AUTH_BASE_URL_ENV_KEYS,
  ...OURA_BACKFILL_DAYS_ENV_KEYS,
  ...OURA_RECONCILE_DAYS_ENV_KEYS,
  ...OURA_RECONCILE_INTERVAL_MS_ENV_KEYS,
  ...OURA_REQUEST_TIMEOUT_MS_ENV_KEYS,
  ...OURA_SCOPES_ENV_KEYS,
  ...OURA_WEBHOOK_TIMESTAMP_TOLERANCE_MS_ENV_KEYS,
] as const;
const WHOOP_DEVICE_SYNC_PROVIDER_RUNTIME_SECRET_ENV_KEYS = [
  ...WHOOP_CLIENT_ID_ENV_KEYS,
  ...WHOOP_CLIENT_SECRET_ENV_KEYS,
] as const;
const STRAVA_DEVICE_SYNC_PROVIDER_RUNTIME_SECRET_ENV_KEYS = [
  ...STRAVA_CLIENT_ID_ENV_KEYS,
  ...STRAVA_CLIENT_SECRET_ENV_KEYS,
] as const;
const WHOOP_DEVICE_SYNC_PROVIDER_RUNTIME_VARIABLE_ENV_KEYS = [
  ...WHOOP_BACKFILL_DAYS_ENV_KEYS,
  ...WHOOP_BASE_URL_ENV_KEYS,
  ...WHOOP_RECONCILE_DAYS_ENV_KEYS,
  ...WHOOP_RECONCILE_INTERVAL_MS_ENV_KEYS,
  ...WHOOP_REQUEST_TIMEOUT_MS_ENV_KEYS,
  ...WHOOP_SCOPES_ENV_KEYS,
  ...WHOOP_WEBHOOK_TIMESTAMP_TOLERANCE_MS_ENV_KEYS,
] as const;
const STRAVA_DEVICE_SYNC_PROVIDER_RUNTIME_VARIABLE_ENV_KEYS = [
  ...STRAVA_API_BASE_URL_ENV_KEYS,
  ...STRAVA_AUTH_BASE_URL_ENV_KEYS,
  ...STRAVA_BACKFILL_DAYS_ENV_KEYS,
  ...STRAVA_RECONCILE_DAYS_ENV_KEYS,
  ...STRAVA_RECONCILE_INTERVAL_MS_ENV_KEYS,
  ...STRAVA_REQUEST_TIMEOUT_MS_ENV_KEYS,
  ...STRAVA_SCOPES_ENV_KEYS,
] as const;

export const deviceSyncProviderRuntimeSecretEnvKeys = Object.freeze([
  ...GARMIN_DEVICE_SYNC_PROVIDER_RUNTIME_SECRET_ENV_KEYS,
  ...OURA_DEVICE_SYNC_PROVIDER_RUNTIME_SECRET_ENV_KEYS,
  ...WHOOP_DEVICE_SYNC_PROVIDER_RUNTIME_SECRET_ENV_KEYS,
  ...STRAVA_DEVICE_SYNC_PROVIDER_RUNTIME_SECRET_ENV_KEYS,
]);

export const deviceSyncProviderRuntimeVariableEnvKeys = Object.freeze([
  ...GARMIN_DEVICE_SYNC_PROVIDER_RUNTIME_VARIABLE_ENV_KEYS,
  ...OURA_DEVICE_SYNC_PROVIDER_RUNTIME_VARIABLE_ENV_KEYS,
  ...WHOOP_DEVICE_SYNC_PROVIDER_RUNTIME_VARIABLE_ENV_KEYS,
  ...STRAVA_DEVICE_SYNC_PROVIDER_RUNTIME_VARIABLE_ENV_KEYS,
]);
