export interface DeviceSyncProviderEnvSpec {
  configKeys: readonly string[];
  secretKeys: readonly string[];
  variableKeys: readonly string[];
}

export const JUNCTION_API_BASE_URL_ENV_KEYS = ["JUNCTION_API_BASE_URL"] as const;
export const JUNCTION_API_KEY_ENV_KEYS = ["JUNCTION_API_KEY"] as const;
export const JUNCTION_CLIENT_USER_ID_NAMESPACE_ENV_KEYS =
  ["JUNCTION_CLIENT_USER_ID_NAMESPACE"] as const;
export const JUNCTION_CLIENT_USER_ID_SECRET_ENV_KEYS = ["JUNCTION_CLIENT_USER_ID_SECRET"] as const;
export const JUNCTION_ENV_ENV_KEYS = ["JUNCTION_ENV"] as const;
export const JUNCTION_PROVIDER_FILTER_ENV_KEYS = ["JUNCTION_PROVIDER_FILTER"] as const;
export const JUNCTION_PUSH_SOURCE_RECOVERY_ENABLED_ENV_KEYS =
  ["JUNCTION_PUSH_SOURCE_RECOVERY_ENABLED"] as const;
export const JUNCTION_RECONCILE_DAYS_ENV_KEYS = ["JUNCTION_RECONCILE_DAYS"] as const;
export const JUNCTION_RECONCILE_INTERVAL_MS_ENV_KEYS = ["JUNCTION_RECONCILE_INTERVAL_MS"] as const;
export const JUNCTION_REGION_ENV_KEYS = ["JUNCTION_REGION"] as const;
export const JUNCTION_REQUEST_TIMEOUT_MS_ENV_KEYS = ["JUNCTION_REQUEST_TIMEOUT_MS"] as const;
export const JUNCTION_SUMMARY_BACKFILL_DAYS_ENV_KEYS = ["JUNCTION_SUMMARY_BACKFILL_DAYS"] as const;
export const JUNCTION_SUMMARY_RESOURCES_ENV_KEYS = ["JUNCTION_SUMMARY_RESOURCES"] as const;
export const JUNCTION_TIMESERIES_BACKFILL_DAYS_ENV_KEYS = ["JUNCTION_TIMESERIES_BACKFILL_DAYS"] as const;
export const JUNCTION_WEBHOOK_SECRET_ENV_KEYS = ["JUNCTION_WEBHOOK_SECRET"] as const;
export const JUNCTION_WEBHOOK_TIMESTAMP_TOLERANCE_MS_ENV_KEYS = ["JUNCTION_WEBHOOK_TIMESTAMP_TOLERANCE_MS"] as const;

export const OURA_API_BASE_URL_ENV_KEYS = ["OURA_API_BASE_URL"] as const;
export const OURA_AUTH_BASE_URL_ENV_KEYS = ["OURA_AUTH_BASE_URL"] as const;
export const OURA_BACKFILL_DAYS_ENV_KEYS = ["OURA_BACKFILL_DAYS"] as const;
export const OURA_CLIENT_ID_ENV_KEYS = ["OURA_CLIENT_ID"] as const;
export const OURA_CLIENT_SECRET_ENV_KEYS = ["OURA_CLIENT_SECRET"] as const;
export const OURA_WEBHOOK_VERIFICATION_TOKEN_ENV_KEYS = ["OURA_WEBHOOK_VERIFICATION_TOKEN"] as const;
export const OURA_RECONCILE_DAYS_ENV_KEYS = ["OURA_RECONCILE_DAYS"] as const;
export const OURA_RECONCILE_INTERVAL_MS_ENV_KEYS = ["OURA_RECONCILE_INTERVAL_MS"] as const;
export const OURA_REQUEST_TIMEOUT_MS_ENV_KEYS = ["OURA_REQUEST_TIMEOUT_MS"] as const;
export const OURA_SCOPES_ENV_KEYS = ["OURA_SCOPES"] as const;
export const OURA_WEBHOOK_TIMESTAMP_TOLERANCE_MS_ENV_KEYS = ["OURA_WEBHOOK_TIMESTAMP_TOLERANCE_MS"] as const;

export const WHOOP_BACKFILL_DAYS_ENV_KEYS = ["WHOOP_BACKFILL_DAYS"] as const;
export const WHOOP_BASE_URL_ENV_KEYS = ["WHOOP_BASE_URL"] as const;
export const WHOOP_CLIENT_ID_ENV_KEYS = ["WHOOP_CLIENT_ID"] as const;
export const WHOOP_CLIENT_SECRET_ENV_KEYS = ["WHOOP_CLIENT_SECRET"] as const;
export const WHOOP_RECONCILE_DAYS_ENV_KEYS = ["WHOOP_RECONCILE_DAYS"] as const;
export const WHOOP_RECONCILE_INTERVAL_MS_ENV_KEYS = ["WHOOP_RECONCILE_INTERVAL_MS"] as const;
export const WHOOP_REQUEST_TIMEOUT_MS_ENV_KEYS = ["WHOOP_REQUEST_TIMEOUT_MS"] as const;
export const WHOOP_SCOPES_ENV_KEYS = ["WHOOP_SCOPES"] as const;
export const WHOOP_WEBHOOK_TIMESTAMP_TOLERANCE_MS_ENV_KEYS = ["WHOOP_WEBHOOK_TIMESTAMP_TOLERANCE_MS"] as const;

export const STRAVA_API_BASE_URL_ENV_KEYS = ["STRAVA_API_BASE_URL"] as const;
export const STRAVA_AUTH_BASE_URL_ENV_KEYS = ["STRAVA_AUTH_BASE_URL"] as const;
export const STRAVA_BACKFILL_DAYS_ENV_KEYS = ["STRAVA_BACKFILL_DAYS"] as const;
export const STRAVA_CLIENT_ID_ENV_KEYS = ["STRAVA_CLIENT_ID"] as const;
export const STRAVA_CLIENT_SECRET_ENV_KEYS = ["STRAVA_CLIENT_SECRET"] as const;
export const STRAVA_RECONCILE_DAYS_ENV_KEYS = ["STRAVA_RECONCILE_DAYS"] as const;
export const STRAVA_RECONCILE_INTERVAL_MS_ENV_KEYS = ["STRAVA_RECONCILE_INTERVAL_MS"] as const;
export const STRAVA_REQUEST_TIMEOUT_MS_ENV_KEYS = ["STRAVA_REQUEST_TIMEOUT_MS"] as const;
export const STRAVA_SCOPES_ENV_KEYS = ["STRAVA_SCOPES"] as const;
export const STRAVA_WEBHOOK_SIGNING_SECRET_ENV_KEYS = ["STRAVA_WEBHOOK_SIGNING_SECRET"] as const;
export const STRAVA_WEBHOOK_TIMESTAMP_TOLERANCE_MS_ENV_KEYS = [
  "STRAVA_WEBHOOK_TIMESTAMP_TOLERANCE_MS",
] as const;
export const STRAVA_WEBHOOK_VERIFY_TOKEN_ENV_KEYS = ["STRAVA_WEBHOOK_VERIFY_TOKEN"] as const;

export const JUNCTION_DEVICE_SYNC_PROVIDER_ENV_SPEC = {
  configKeys: [
    ...JUNCTION_API_BASE_URL_ENV_KEYS,
    ...JUNCTION_API_KEY_ENV_KEYS,
    ...JUNCTION_CLIENT_USER_ID_NAMESPACE_ENV_KEYS,
    ...JUNCTION_CLIENT_USER_ID_SECRET_ENV_KEYS,
    ...JUNCTION_ENV_ENV_KEYS,
    ...JUNCTION_PROVIDER_FILTER_ENV_KEYS,
    ...JUNCTION_PUSH_SOURCE_RECOVERY_ENABLED_ENV_KEYS,
    ...JUNCTION_RECONCILE_DAYS_ENV_KEYS,
    ...JUNCTION_RECONCILE_INTERVAL_MS_ENV_KEYS,
    ...JUNCTION_REGION_ENV_KEYS,
    ...JUNCTION_REQUEST_TIMEOUT_MS_ENV_KEYS,
    ...JUNCTION_SUMMARY_BACKFILL_DAYS_ENV_KEYS,
    ...JUNCTION_SUMMARY_RESOURCES_ENV_KEYS,
    ...JUNCTION_TIMESERIES_BACKFILL_DAYS_ENV_KEYS,
    ...JUNCTION_WEBHOOK_SECRET_ENV_KEYS,
    ...JUNCTION_WEBHOOK_TIMESTAMP_TOLERANCE_MS_ENV_KEYS,
  ],
  secretKeys: [
    ...JUNCTION_API_KEY_ENV_KEYS,
    ...JUNCTION_CLIENT_USER_ID_SECRET_ENV_KEYS,
    ...JUNCTION_WEBHOOK_SECRET_ENV_KEYS,
  ],
  variableKeys: [
    ...JUNCTION_API_BASE_URL_ENV_KEYS,
    ...JUNCTION_CLIENT_USER_ID_NAMESPACE_ENV_KEYS,
    ...JUNCTION_ENV_ENV_KEYS,
    ...JUNCTION_PROVIDER_FILTER_ENV_KEYS,
    ...JUNCTION_PUSH_SOURCE_RECOVERY_ENABLED_ENV_KEYS,
    ...JUNCTION_RECONCILE_DAYS_ENV_KEYS,
    ...JUNCTION_RECONCILE_INTERVAL_MS_ENV_KEYS,
    ...JUNCTION_REGION_ENV_KEYS,
    ...JUNCTION_REQUEST_TIMEOUT_MS_ENV_KEYS,
    ...JUNCTION_SUMMARY_BACKFILL_DAYS_ENV_KEYS,
    ...JUNCTION_SUMMARY_RESOURCES_ENV_KEYS,
    ...JUNCTION_TIMESERIES_BACKFILL_DAYS_ENV_KEYS,
    ...JUNCTION_WEBHOOK_TIMESTAMP_TOLERANCE_MS_ENV_KEYS,
  ],
} as const satisfies DeviceSyncProviderEnvSpec;

export const OURA_DEVICE_SYNC_PROVIDER_ENV_SPEC = {
  configKeys: [
    ...OURA_API_BASE_URL_ENV_KEYS,
    ...OURA_AUTH_BASE_URL_ENV_KEYS,
    ...OURA_BACKFILL_DAYS_ENV_KEYS,
    ...OURA_CLIENT_ID_ENV_KEYS,
    ...OURA_CLIENT_SECRET_ENV_KEYS,
    ...OURA_RECONCILE_DAYS_ENV_KEYS,
    ...OURA_RECONCILE_INTERVAL_MS_ENV_KEYS,
    ...OURA_REQUEST_TIMEOUT_MS_ENV_KEYS,
    ...OURA_SCOPES_ENV_KEYS,
    ...OURA_WEBHOOK_TIMESTAMP_TOLERANCE_MS_ENV_KEYS,
    ...OURA_WEBHOOK_VERIFICATION_TOKEN_ENV_KEYS,
  ],
  secretKeys: [
    ...OURA_CLIENT_ID_ENV_KEYS,
    ...OURA_CLIENT_SECRET_ENV_KEYS,
  ],
  variableKeys: [
    ...OURA_API_BASE_URL_ENV_KEYS,
    ...OURA_AUTH_BASE_URL_ENV_KEYS,
    ...OURA_BACKFILL_DAYS_ENV_KEYS,
    ...OURA_RECONCILE_DAYS_ENV_KEYS,
    ...OURA_RECONCILE_INTERVAL_MS_ENV_KEYS,
    ...OURA_REQUEST_TIMEOUT_MS_ENV_KEYS,
    ...OURA_SCOPES_ENV_KEYS,
    ...OURA_WEBHOOK_TIMESTAMP_TOLERANCE_MS_ENV_KEYS,
  ],
} as const satisfies DeviceSyncProviderEnvSpec;

export const WHOOP_DEVICE_SYNC_PROVIDER_ENV_SPEC = {
  configKeys: [
    ...WHOOP_BACKFILL_DAYS_ENV_KEYS,
    ...WHOOP_BASE_URL_ENV_KEYS,
    ...WHOOP_CLIENT_ID_ENV_KEYS,
    ...WHOOP_CLIENT_SECRET_ENV_KEYS,
    ...WHOOP_RECONCILE_DAYS_ENV_KEYS,
    ...WHOOP_RECONCILE_INTERVAL_MS_ENV_KEYS,
    ...WHOOP_REQUEST_TIMEOUT_MS_ENV_KEYS,
    ...WHOOP_SCOPES_ENV_KEYS,
    ...WHOOP_WEBHOOK_TIMESTAMP_TOLERANCE_MS_ENV_KEYS,
  ],
  secretKeys: [
    ...WHOOP_CLIENT_ID_ENV_KEYS,
    ...WHOOP_CLIENT_SECRET_ENV_KEYS,
  ],
  variableKeys: [
    ...WHOOP_BACKFILL_DAYS_ENV_KEYS,
    ...WHOOP_BASE_URL_ENV_KEYS,
    ...WHOOP_RECONCILE_DAYS_ENV_KEYS,
    ...WHOOP_RECONCILE_INTERVAL_MS_ENV_KEYS,
    ...WHOOP_REQUEST_TIMEOUT_MS_ENV_KEYS,
    ...WHOOP_SCOPES_ENV_KEYS,
    ...WHOOP_WEBHOOK_TIMESTAMP_TOLERANCE_MS_ENV_KEYS,
  ],
} as const satisfies DeviceSyncProviderEnvSpec;

export const STRAVA_DEVICE_SYNC_PROVIDER_ENV_SPEC = {
  configKeys: [
    ...STRAVA_API_BASE_URL_ENV_KEYS,
    ...STRAVA_AUTH_BASE_URL_ENV_KEYS,
    ...STRAVA_BACKFILL_DAYS_ENV_KEYS,
    ...STRAVA_CLIENT_ID_ENV_KEYS,
    ...STRAVA_CLIENT_SECRET_ENV_KEYS,
    ...STRAVA_RECONCILE_DAYS_ENV_KEYS,
    ...STRAVA_RECONCILE_INTERVAL_MS_ENV_KEYS,
    ...STRAVA_REQUEST_TIMEOUT_MS_ENV_KEYS,
    ...STRAVA_SCOPES_ENV_KEYS,
    ...STRAVA_WEBHOOK_SIGNING_SECRET_ENV_KEYS,
    ...STRAVA_WEBHOOK_TIMESTAMP_TOLERANCE_MS_ENV_KEYS,
    ...STRAVA_WEBHOOK_VERIFY_TOKEN_ENV_KEYS,
  ],
  secretKeys: [
    ...STRAVA_CLIENT_ID_ENV_KEYS,
    ...STRAVA_CLIENT_SECRET_ENV_KEYS,
    ...STRAVA_WEBHOOK_SIGNING_SECRET_ENV_KEYS,
  ],
  variableKeys: [
    ...STRAVA_API_BASE_URL_ENV_KEYS,
    ...STRAVA_AUTH_BASE_URL_ENV_KEYS,
    ...STRAVA_BACKFILL_DAYS_ENV_KEYS,
    ...STRAVA_RECONCILE_DAYS_ENV_KEYS,
    ...STRAVA_RECONCILE_INTERVAL_MS_ENV_KEYS,
    ...STRAVA_REQUEST_TIMEOUT_MS_ENV_KEYS,
    ...STRAVA_SCOPES_ENV_KEYS,
    ...STRAVA_WEBHOOK_TIMESTAMP_TOLERANCE_MS_ENV_KEYS,
  ],
} as const satisfies DeviceSyncProviderEnvSpec;
