const MS_PER_DAY = 24 * 60 * 60 * 1000;

export const HOSTED_GROWTH_GROUP_PRIVATE_ATTRIBUTION_LOOKBACK_DAYS = 14;
export const HOSTED_GROWTH_GROUP_PRIVATE_ATTRIBUTION_LOOKBACK_MS =
  HOSTED_GROWTH_GROUP_PRIVATE_ATTRIBUTION_LOOKBACK_DAYS * MS_PER_DAY;
