// Generated by scripts/generate-goal-illustration-manifest.ts. Do not edit.

export const GOAL_ILLUSTRATION_ROUTE_IDS: ReadonlySet<string> = new Set([
  "improve-digestion",
  "manage-ibs-symptoms",
  "manage-lactose-intolerance",
  "reduce-acid-reflux",
  "reduce-bloating",
  "relieve-constipation",
  "run-ironman",
]);
