import type { GoalCategorySlug } from "@/src/lib/goals/goal-categories";

export interface GoalDirectorySectionDefinition {
  id: string;
  label: string;
  routeIds: readonly string[];
}

export const GOAL_DIRECTORY_SECTION_DEFINITIONS: Readonly<
  Record<GoalCategorySlug, readonly GoalDirectorySectionDefinition[]>
> = {
  biomarkers: [
    {
      id: "blood-sugar-diabetes",
      label: "Blood sugar and diabetes",
      routeIds: [
        "improve-blood-sugar-control",
        "improve-insulin-sensitivity",
        "lower-a1c",
        "move-out-of-prediabetes-range",
        "prevent-type-2-diabetes",
        "type-2-diabetes-remission",
      ],
    },
    {
      id: "blood-pressure-heart-fitness",
      label: "Blood pressure and heart fitness",
      routeIds: [
        "lower-blood-pressure",
        "lower-resting-heart-rate",
        "improve-hrv",
      ],
    },
    {
      id: "cholesterol-cardiovascular-risk",
      label: "Cholesterol and cardiovascular risk",
      routeIds: [
        "lower-cholesterol",
        "lower-ldl-cholesterol",
        "lower-apob",
        "lower-triglycerides",
        "reduce-risk-from-high-lpa",
        "reduce-heart-disease-risk",
        "reduce-stroke-risk",
      ],
    },
    {
      id: "vitamin-iron-levels",
      label: "Vitamin and iron levels",
      routeIds: [
        "correct-b12-deficiency",
        "correct-iron-deficiency",
        "recover-from-iron-deficiency-anemia",
        "correct-vitamin-d-deficiency",
      ],
    },
    {
      id: "kidney-uric-acid",
      label: "Kidney and uric acid health",
      routeIds: [
        "protect-kidney-function",
        "reduce-urine-albumin",
        "lower-uric-acid",
        "prevent-gout-attacks",
      ],
    },
    {
      id: "liver-health",
      label: "Liver health",
      routeIds: ["improve-fatty-liver-disease", "reduce-liver-fat"],
    },
    {
      id: "cancer-risk",
      label: "Cancer risk reduction",
      routeIds: [
        "reduce-colorectal-cancer-risk",
        "reduce-lung-cancer-risk",
        "reduce-skin-cancer-risk",
      ],
    },
    {
      id: "bone-health",
      label: "Bone health",
      routeIds: ["build-stronger-bones", "reduce-fracture-risk"],
    },
  ],
  cardio: [
    {
      id: "fitness",
      label: "Cardio fitness",
      routeIds: [
        "improve-vo2-max",
        "improve-cardio-endurance",
        "improve-heart-rate-recovery",
        "get-150-minutes-of-cardio",
        "exercise-30-minutes-without-stopping",
        "climb-stairs-without-getting-winded",
      ],
    },
    {
      id: "running",
      label: "Running",
      routeIds: [
        "start-running",
        "return-to-running",
        "run-mile-without-stopping",
        "run-faster-mile",
        "run-first-5k",
        "run-faster-5k",
        "run-first-10k",
        "run-faster-10k",
        "run-half-marathon",
        "run-marathon",
        "run-trail-race",
        "run-ultramarathon",
      ],
    },
    {
      id: "cycling",
      label: "Cycling",
      routeIds: [
        "cycle-farther",
        "cycle-faster",
        "increase-cycling-power",
        "ride-100-miles",
      ],
    },
    {
      id: "swimming-rowing",
      label: "Swimming and rowing",
      routeIds: [
        "swim-farther-without-stopping",
        "swim-faster",
        "swim-one-mile",
        "improve-rowing-endurance",
        "row-faster-2k",
      ],
    },
    {
      id: "triathlon-endurance",
      label: "Triathlon and long-distance endurance",
      routeIds: [
        "complete-first-triathlon",
        "complete-olympic-triathlon",
        "complete-half-ironman",
        "run-ironman",
        "hike-longer",
        "complete-long-distance-hike",
        "ruck-farther",
      ],
    },
    {
      id: "everyday-sports",
      label: "Everyday movement and team sports",
      routeIds: [
        "walk-every-day",
        "sit-less",
        "jump-rope-10-minutes",
        "get-in-basketball-shape",
        "get-in-soccer-shape",
      ],
    },
  ],
  "life-stages": [
    {
      id: "healthy-aging",
      label: "Healthy aging",
      routeIds: [
        "stay-independent-as-i-age",
        "stay-strong-as-i-age",
        "improve-balance-as-i-age",
        "keep-my-brain-healthy-as-i-age",
        "stay-mobile-as-i-age",
      ],
    },
    {
      id: "fertility-reproductive-health",
      label: "Fertility and reproductive health",
      routeIds: [
        "get-ready-for-pregnancy",
        "improve-sperm-health",
        "improve-erectile-health",
      ],
    },
    {
      id: "pregnancy-wellbeing",
      label: "Pregnancy wellbeing",
      routeIds: [
        "eat-well-during-pregnancy",
        "reduce-back-pain-during-pregnancy",
        "sleep-better-during-pregnancy",
        "stay-active-during-pregnancy",
        "stay-strong-during-pregnancy",
      ],
    },
    {
      id: "postpartum-recovery",
      label: "Postpartum recovery",
      routeIds: [
        "recover-after-giving-birth",
        "return-to-exercise-postpartum",
        "return-to-running-postpartum",
        "improve-postpartum-mental-health",
        "rebuild-core-strength-after-birth",
        "rebuild-pelvic-floor-after-birth",
      ],
    },
    {
      id: "menopause-health",
      label: "Menopause health",
      routeIds: [
        "reduce-hot-flashes",
        "reduce-night-sweats",
        "improve-vaginal-comfort-after-menopause",
        "protect-bone-health-after-menopause",
        "sleep-better-during-menopause",
        "stay-strong-through-menopause",
      ],
    },
    {
      id: "period-pelvic-health",
      label: "Period and pelvic health",
      routeIds: [
        "have-more-regular-periods",
        "improve-bladder-control",
        "reduce-pain-during-sex",
        "reduce-period-pain",
        "reduce-pms-symptoms",
      ],
    },
  ],
  mind: [
    {
      id: "stress-emotional-health",
      label: "Stress and emotional health",
      routeIds: [
        "reduce-stress",
        "manage-anxiety",
        "improve-mood",
        "handle-emotions",
        "manage-anger",
        "stop-overthinking",
      ],
    },
    {
      id: "focus-presence",
      label: "Focus and presence",
      routeIds: [
        "improve-focus",
        "be-more-present",
        "meditate-regularly",
        "stop-procrastinating",
        "feel-more-energetic",
      ],
    },
    {
      id: "burnout-work-life",
      label: "Burnout and work-life balance",
      routeIds: [
        "improve-work-life-balance",
        "prevent-burnout",
        "recover-from-burnout",
        "unwind-after-work",
      ],
    },
    {
      id: "routines-behavior-change",
      label: "Routines and behavior change",
      routeIds: [
        "build-a-habit",
        "break-a-bad-habit",
        "stick-to-health-goals",
        "build-a-morning-routine",
        "build-an-evening-routine",
      ],
    },
    {
      id: "digital-wellbeing",
      label: "Digital wellbeing",
      routeIds: [
        "reduce-screen-time",
        "use-social-media-less",
        "stop-doomscrolling",
      ],
    },
    {
      id: "connection-outdoors",
      label: "Connection and time outdoors",
      routeIds: [
        "build-a-support-system",
        "feel-less-lonely",
        "reconnect-with-people",
        "make-new-friends",
        "deepen-friendships",
        "spend-more-time-outdoors",
      ],
    },
    {
      id: "alcohol-substances",
      label: "Alcohol, nicotine, and substances",
      routeIds: [
        "drink-less-alcohol",
        "stop-drinking-alcohol",
        "cut-back-on-caffeine",
        "use-less-cannabis",
        "quit-smoking",
        "quit-vaping",
        "quit-nicotine-pouches",
      ],
    },
  ],
  nutrition: [
    {
      id: "everyday-eating",
      label: "Everyday eating",
      routeIds: [
        "eat-balanced-diet",
        "eat-regular-meals",
        "eat-more-fruits-and-vegetables",
        "eat-more-whole-grains",
        "eat-more-beans-and-lentils",
        "eat-more-fiber",
        "stay-hydrated",
        "cook-at-home-more",
        "meal-prep-consistently",
      ],
    },
    {
      id: "weight-appetite",
      label: "Weight and appetite",
      routeIds: [
        "lose-weight",
        "lose-fat-keep-muscle",
        "maintain-weight-loss",
        "gain-weight-healthily",
        "feel-fuller-between-meals",
        "reduce-food-cravings",
        "reduce-emotional-eating",
        "stop-late-night-snacking",
      ],
    },
    {
      id: "nutrients-training",
      label: "Nutrients and training fuel",
      routeIds: [
        "hit-protein-target",
        "get-enough-calcium",
        "get-enough-iron",
        "eat-more-omega-3s",
        "fuel-my-training",
      ],
    },
    {
      id: "heart-healthy-patterns",
      label: "Heart-healthy eating patterns",
      routeIds: [
        "follow-mediterranean-diet",
        "follow-dash-diet",
        "eat-less-sodium",
        "eat-less-saturated-fat",
        "eat-less-added-sugar",
        "eat-fewer-ultra-processed-foods",
      ],
    },
    {
      id: "dietary-needs-situations",
      label: "Dietary needs and situations",
      routeIds: [
        "eat-well-vegan",
        "eat-well-vegetarian",
        "eat-well-celiac-disease",
        "manage-lactose-intolerance",
        "eat-well-on-glp-1",
        "eat-healthy-on-budget",
        "eat-healthy-while-traveling",
      ],
    },
    {
      id: "digestion",
      label: "Digestion",
      routeIds: [
        "improve-digestion",
        "manage-ibs-symptoms",
        "reduce-acid-reflux",
        "reduce-bloating",
        "relieve-constipation",
      ],
    },
  ],
  sleep: [
    {
      id: "quality",
      label: "Sleep quality",
      routeIds: [
        "sleep-better",
        "fall-asleep-faster",
        "improve-chronic-insomnia",
        "improve-deep-sleep",
        "improve-rem-sleep",
        "sleep-longer",
        "sleep-through-the-night",
        "wake-up-feeling-rested",
        "recover-from-sleep-debt",
        "reduce-sleep-anxiety",
        "have-fewer-nightmares",
      ],
    },
    {
      id: "schedule",
      label: "Sleep schedule and timing",
      routeIds: [
        "adjust-to-daylight-saving-time",
        "fix-my-sleep-schedule",
        "keep-a-consistent-sleep-schedule",
        "reduce-jet-lag",
        "sleep-better-on-night-shifts",
        "sleep-better-on-rotating-shifts",
        "stop-hitting-snooze",
        "stop-waking-up-too-early",
        "take-better-naps",
        "wake-up-earlier",
      ],
    },
    {
      id: "situations-comfort",
      label: "Sleep situations and comfort",
      routeIds: [
        "sleep-better-during-stressful-times",
        "sleep-better-in-hot-weather",
        "sleep-better-while-traveling",
        "sleep-better-with-a-partner-who-snores",
        "sleep-better-with-acid-reflux",
        "sleep-better-with-allergies",
        "sleep-better-with-chronic-pain",
        "sleep-better-with-noise",
      ],
    },
    {
      id: "snoring-apnea",
      label: "Snoring and sleep apnea",
      routeIds: [
        "get-sleep-apnea-under-control",
        "use-cpap-consistently",
        "snore-less",
      ],
    },
    {
      id: "nighttime-symptoms",
      label: "Nighttime symptoms",
      routeIds: [
        "feel-less-sleepy-during-the-day",
        "reduce-nighttime-teeth-grinding",
        "reduce-restless-legs-at-night",
      ],
    },
  ],
  strength: [
    {
      id: "foundational-strength",
      label: "Foundational strength",
      routeIds: [
        "get-stronger",
        "build-muscle",
        "build-upper-body-strength",
        "build-leg-strength",
        "build-core-strength",
        "build-stronger-glutes",
        "build-bigger-arms",
        "build-muscle-after-50",
        "improve-grip-strength",
        "carry-heavy-things-more-easily",
      ],
    },
    {
      id: "main-lifts",
      label: "Main lifts",
      routeIds: [
        "bench-press-more-weight",
        "overhead-press-more-weight",
        "deadlift-more-weight",
        "squat-more-weight",
      ],
    },
    {
      id: "bodyweight-athletic-skills",
      label: "Bodyweight and athletic skills",
      routeIds: [
        "do-first-push-up",
        "do-more-push-ups",
        "do-first-pull-up",
        "do-more-pull-ups",
        "do-first-dip",
        "do-muscle-up",
        "do-pistol-squat",
        "do-handstand",
        "jump-higher",
        "dunk-basketball",
      ],
    },
    {
      id: "mobility-flexibility",
      label: "Mobility and flexibility",
      routeIds: [
        "improve-mobility",
        "improve-ankle-mobility",
        "improve-hip-mobility",
        "improve-shoulder-mobility",
        "touch-toes",
        "do-splits",
        "sit-in-deep-squat",
        "feel-less-stiff",
        "improve-posture",
      ],
    },
    {
      id: "everyday-movement-balance",
      label: "Everyday movement and balance",
      routeIds: [
        "improve-balance",
        "reduce-fall-risk",
        "get-up-from-chair-more-easily",
        "get-up-from-floor-more-easily",
        "walk-faster",
      ],
    },
    {
      id: "pain-relief",
      label: "Pain relief",
      routeIds: ["reduce-back-pain", "reduce-neck-pain", "reduce-knee-pain"],
    },
  ],
};
