import {
  deviceSyncProviderRuntimeSecretEnvKeys,
} from "@murphai/device-syncd/config";

export const HOSTED_WORKER_REQUIRED_SECRET_NAMES = [
  "HOSTED_EXECUTION_PLATFORM_ENVELOPE_KEY",
  "HOSTED_EXECUTION_AUTOMATION_RECIPIENT_PRIVATE_JWK",
  "HOSTED_EXECUTION_AUTOMATION_RECIPIENT_PUBLIC_JWK",
  "HOSTED_EXECUTION_RECOVERY_RECIPIENT_PUBLIC_JWK",
  "HOSTED_WAKE_ENCRYPTION_KEY",
  "HOSTED_WEB_CALLBACK_SIGNING_PRIVATE_JWK",
] as const;

export const HOSTED_WORKER_OPTIONAL_SECRET_NAMES = [
  "DEVICE_SYNC_SECRET",
  ...deviceSyncProviderRuntimeSecretEnvKeys,
  "JUNCTION_API_KEY",
  "JUNCTION_CLIENT_USER_ID_SECRET",
  "JUNCTION_WEBHOOK_SECRET",
  "HOSTED_AI_USAGE_REPORTING_SECRET",
  "HOSTED_LOG_FINGERPRINT_SECRET",
  "HOSTED_EMAIL_SIGNING_SECRET",
  "HOSTED_EXECUTION_AUTOMATION_RECIPIENT_PRIVATE_KEYRING_JSON",
  "HOSTED_EXECUTION_PLATFORM_ENVELOPE_KEYRING_JSON",
  "HOSTED_EXECUTION_TEE_AUTOMATION_RECIPIENT_PUBLIC_JWK",
  "HOSTED_WAKE_ENCRYPTION_KEYRING_JSON",
  "HOSTED_AI_USAGE_STRIPE_RESTRICTED_ACCESS_KEY",
  "LINQ_API_TOKEN",
  "LINQ_WEBHOOK_SECRET",
  "MAPBOX_ACCESS_TOKEN",
  "TELEGRAM_BOT_TOKEN",
  "VERCEL_AI_API_KEY",
] as const;
