import {
  deviceSyncProviderRuntimeSecretEnvKeys,
} from "@murphai/device-syncd/config";
import {
  HOSTED_ASSISTANT_WORKER_SECRET_ENV_NAMES,
} from "@murphai/hosted-execution/assistant-capabilities";

const HOSTED_WORKER_OPTIONAL_PROVIDER_SECRET_NAMES =
  HOSTED_ASSISTANT_WORKER_SECRET_ENV_NAMES;

export const HOSTED_WORKER_REQUIRED_SECRET_NAMES = [
  "HOSTED_CRYPTO_CLOUDFLARE_AUTOMATION_PRIVATE_JWK",
  "HOSTED_LOG_FINGERPRINT_SECRET",
  "HOSTED_PRIVATE_MEDIA_CAPABILITY_SECRET",
  "HOSTED_PROVIDER_EGRESS_CREDENTIAL_SIGNING_SECRET",
  "HOSTED_R2_PRESIGN_ACCESS_KEY_ID",
  "HOSTED_R2_PRESIGN_SECRET_ACCESS_KEY",
  "HOSTED_WEB_CALLBACK_SIGNING_PRIVATE_JWK",
  "MURPH_DATA_API_KEY",
  "OPENAI_API_KEY",
] as const;

export const HOSTED_WORKER_OPTIONAL_SECRET_NAMES = [
  "DEVICE_SYNC_SECRET",
  ...deviceSyncProviderRuntimeSecretEnvKeys,
  ...HOSTED_WORKER_OPTIONAL_PROVIDER_SECRET_NAMES,
  "HOSTED_AI_USAGE_REPORTING_SECRET",
  "HOSTED_CRYPTO_CLOUDFLARE_AUTOMATION_PRIVATE_KEYRING_JSON",
  "HOSTED_DATABASE_ALERT_LINQ_CHAT_ID",
  "HOSTED_DATABASE_ALERT_LINQ_SECONDARY_CHAT_ID",
  "HOSTED_DATABASE_ALERT_PLANETSCALE_SERVICE_TOKEN",
  "HOSTED_DATABASE_ALERT_PLANETSCALE_SERVICE_TOKEN_ID",
  "HOSTED_EMAIL_SIGNING_SECRET",
  "LINQ_WEBHOOK_SECRET",
  "VENICE_API_KEY",
] as const;
