import {
  deviceSyncProviderRuntimeSecretEnvKeys,
} from "@murphai/device-syncd/config";

export const HOSTED_WORKER_REQUIRED_SECRET_NAMES = [
  "HOSTED_CRYPTO_CLOUDFLARE_AUTOMATION_PRIVATE_JWK",
  "HOSTED_LOG_FINGERPRINT_SECRET",
  "HOSTED_R2_PRESIGN_ACCESS_KEY_ID",
  "HOSTED_R2_PRESIGN_SECRET_ACCESS_KEY",
  "HOSTED_WEB_CALLBACK_SIGNING_PRIVATE_JWK",
  "MURPH_DATA_API_KEY",
  "OPENAI_API_KEY",
] as const;

export const HOSTED_WORKER_OPTIONAL_SECRET_NAMES = [
  "CLOUDFLARE_IMAGES_API_KEY",
  "DEVICE_SYNC_SECRET",
  ...deviceSyncProviderRuntimeSecretEnvKeys,
  "ELEVENLABS_API_KEY",
  "HOSTED_AI_USAGE_REPORTING_SECRET",
  "HOSTED_EMAIL_SIGNING_SECRET",
  "EXA_API_KEY",
  "LINQ_API_TOKEN",
  "LINQ_WEBHOOK_SECRET",
  "MAPBOX_ACCESS_TOKEN",
  "TELEGRAM_BOT_TOKEN",
  "WHATSAPP_ACCESS_TOKEN",
  "WHATSAPP_PHONE_NUMBER_ID",
] as const;
