import {
  deviceSyncProviderRuntimeVariableEnvKeys,
} from "@murphai/device-syncd/config";
import {
  HOSTED_ASSISTANT_FORWARDED_CONFIG_ENV_NAMES,
} from "@murphai/hosted-execution/assistant-capabilities";
import {
  MURPH_ANDROID_APP_ENABLED_ENV,
} from "@murphai/hosted-execution/env";

const HOSTED_WORKER_OPTIONAL_PROVIDER_VAR_NAMES =
  HOSTED_ASSISTANT_FORWARDED_CONFIG_ENV_NAMES;

export const HOSTED_WORKER_REQUIRED_VAR_NAMES = [
  "CF_PUBLIC_BASE_URL",
  "HOSTED_CRYPTO_AUTHORITY_SIGN_KEY_VERSION",
  "HOSTED_CRYPTO_AUTHORITY_SIGN_PUBLIC_KEY_PEM",
  "HOSTED_CRYPTO_CLOUDFLARE_AUTOMATION_KEY_ID",
  "HOSTED_CRYPTO_ENV",
  "HOSTED_R2_PRESIGN_ACCOUNT_ID",
  "HOSTED_R2_PRESIGN_BUCKET_NAME",
] as const;

export const HOSTED_WORKER_TRIMMED_OPTIONAL_VAR_NAMES = [
  "DEVICE_SYNC_PUBLIC_BASE_URL",
  ...deviceSyncProviderRuntimeVariableEnvKeys,
  "HOSTED_CRYPTO_AUTHORITY_VERIFY_KEYRING_JSON",
  "HOSTED_EMAIL_DEFAULT_SUBJECT",
  "HOSTED_EMAIL_DOMAIN",
  "HOSTED_EMAIL_FROM_ADDRESS",
  "HOSTED_EMAIL_LOCAL_PART",
  "HOSTED_DATABASE_ALERT_ENABLED",
  "HOSTED_DATABASE_ALERT_PLANETSCALE_BRANCH_ID",
  "HOSTED_DATABASE_ALERT_PLANETSCALE_BRANCH_NAME",
  "HOSTED_DATABASE_ALERT_PLANETSCALE_DATABASE_NAME",
  "HOSTED_DATABASE_ALERT_PLANETSCALE_ORGANIZATION",
  "HOSTED_ASSISTANT_APPROVAL_POLICY",
  "HOSTED_ASSISTANT_MODEL",
  "HOSTED_ASSISTANT_PROVIDER",
  "HOSTED_ASSISTANT_REASONING_EFFORT",
  "HOSTED_ASSISTANT_SANDBOX",
  "HOSTED_EXECUTION_RUNNER_ENV_PROFILES",
  "HOSTED_EXECUTION_RUNNER_IDLE_TTL_MS",
  "HOSTED_EXECUTION_RUNNER_LIFECYCLE_REEVALUATION_MS",
  "HOSTED_EXECUTION_VERCEL_OIDC_ENVIRONMENT",
  "HOSTED_EXECUTION_VERCEL_OIDC_PROJECT_NAME",
  "HOSTED_EXECUTION_VERCEL_OIDC_TEAM_SLUG",
  "HOSTED_PHYSICAL_NOTES_ENABLED",
  "HOSTED_R2_PRESIGN_ENDPOINT",
  "HOSTED_WEB_BASE_URL",
  "HOSTED_WEB_CALLBACK_SIGNING_KEY_ID",
  "MURPH_HOSTED_CHECKPOINT_DEBUG_PATHS",
  "MURPH_HOSTED_CHECKPOINT_DEBUG_PATHS_FILE",
  "MURPH_HOSTED_CHECKPOINT_DEBUG_PATHS_LOG",
  "MURPH_HOSTED_CHECKPOINT_DEBUG_PATHS_LOG_LIMIT",
  "MURPH_HOSTED_CHECKPOINT_DEBUG_PATHS_LOG_RAW",
  ...HOSTED_WORKER_OPTIONAL_PROVIDER_VAR_NAMES,
] as const;

export const HOSTED_WORKER_OPTIONAL_VAR_NAMES = [
  ...HOSTED_WORKER_TRIMMED_OPTIONAL_VAR_NAMES,
  MURPH_ANDROID_APP_ENABLED_ENV,
] as const;

// Source-controlled defaults applied when the deploy environment leaves an
// optional var unset. These are the values real deploys ship by default, so
// they must stay aligned with the checked-in wrangler.jsonc scaffold vars
// (enforced by deploy-automation.test.ts). Production overrides live in the
// GitHub `production` environment variables.
export const HOSTED_WORKER_OPTIONAL_VAR_DEFAULTS: Partial<
  Record<(typeof HOSTED_WORKER_OPTIONAL_VAR_NAMES)[number], string>
> = {
  // Device-sync stays worker-only and is serialized into resolvedConfig instead
  // of forwarding raw provider env into the hosted child runtime.
  HOSTED_EXECUTION_RUNNER_ENV_PROFILES: "exa,hosted-email,linq,mapbox,telegram",
  HOSTED_EXECUTION_RUNNER_IDLE_TTL_MS: "1200000",
  HOSTED_EXECUTION_VERCEL_OIDC_ENVIRONMENT: "production",
};
