export const TEST_AUTOMATION_RECIPIENT_KEY_ID = "automation:v1";
export const TEST_RECOVERY_RECIPIENT_KEY_ID = "recovery:v1";
export const TEST_TEE_AUTOMATION_RECIPIENT_KEY_ID = "tee-automation:v1";

export const TEST_AUTOMATION_RECIPIENT_PUBLIC_JWK = {
  crv: "P-256",
  ext: true,
  key_ops: [] as string[],
  kty: "EC",
  x: "xSelVJv6r6LPUS8GCNgj1T_7z5GXOrhgY1cCdzGb5ao",
  y: "8HhciS1cAPKs_fPfgZnb1USdRtBX-4Nvp8XiBHuMcmY",
} as const;
export const TEST_TEE_AUTOMATION_RECIPIENT_PUBLIC_JWK =
  TEST_AUTOMATION_RECIPIENT_PUBLIC_JWK;

export const TEST_AUTOMATION_RECIPIENT_PRIVATE_JWK = {
  ...TEST_AUTOMATION_RECIPIENT_PUBLIC_JWK,
  d: "HAPljluiFVW3g-UEmrJ9NVYTlclAhaC8N5LT0h7vitQ",
  key_ops: ["deriveBits"] as string[],
} as const;

export const TEST_AUTOMATION_RECIPIENT_PUBLIC_JWK_JSON = JSON.stringify(
  TEST_AUTOMATION_RECIPIENT_PUBLIC_JWK,
);
export const TEST_RECOVERY_RECIPIENT_PUBLIC_JWK_JSON = JSON.stringify(
  TEST_AUTOMATION_RECIPIENT_PUBLIC_JWK,
);
export const TEST_TEE_AUTOMATION_RECIPIENT_PUBLIC_JWK_JSON = JSON.stringify(
  TEST_TEE_AUTOMATION_RECIPIENT_PUBLIC_JWK,
);

export const TEST_AUTOMATION_RECIPIENT_PRIVATE_JWK_JSON = JSON.stringify(
  TEST_AUTOMATION_RECIPIENT_PRIVATE_JWK,
);
export const TEST_HOSTED_WEB_CALLBACK_PRIVATE_JWK_JSON = JSON.stringify(
  TEST_AUTOMATION_RECIPIENT_PRIVATE_JWK,
);
export const TEST_HOSTED_WEB_CALLBACK_PUBLIC_JWK_JSON = JSON.stringify(
  TEST_AUTOMATION_RECIPIENT_PUBLIC_JWK,
);

export function createHostedExecutionTestEnv(
  overrides: Partial<Record<string, string | undefined>> = {},
): Record<string, string | undefined> {
  return {
    HOSTED_EXECUTION_AUTOMATION_RECIPIENT_KEY_ID: TEST_AUTOMATION_RECIPIENT_KEY_ID,
    HOSTED_EXECUTION_AUTOMATION_RECIPIENT_PRIVATE_JWK:
      TEST_AUTOMATION_RECIPIENT_PRIVATE_JWK_JSON,
    HOSTED_EXECUTION_AUTOMATION_RECIPIENT_PUBLIC_JWK:
      TEST_AUTOMATION_RECIPIENT_PUBLIC_JWK_JSON,
    HOSTED_EXECUTION_RECOVERY_RECIPIENT_KEY_ID: TEST_RECOVERY_RECIPIENT_KEY_ID,
    HOSTED_EXECUTION_RECOVERY_RECIPIENT_PUBLIC_JWK:
      TEST_RECOVERY_RECIPIENT_PUBLIC_JWK_JSON,
    HOSTED_EXECUTION_TEE_AUTOMATION_RECIPIENT_KEY_ID:
      TEST_TEE_AUTOMATION_RECIPIENT_KEY_ID,
    HOSTED_EXECUTION_TEE_AUTOMATION_RECIPIENT_PUBLIC_JWK:
      TEST_TEE_AUTOMATION_RECIPIENT_PUBLIC_JWK_JSON,
    HOSTED_EXECUTION_PLATFORM_ENVELOPE_KEY: Buffer.alloc(32, 9).toString("base64"),
    HOSTED_EXECUTION_VERCEL_OIDC_PROJECT_NAME: "murph-web",
    HOSTED_EXECUTION_VERCEL_OIDC_TEAM_SLUG: "murph-team",
    HOSTED_WEB_CALLBACK_SIGNING_PRIVATE_JWK: TEST_HOSTED_WEB_CALLBACK_PRIVATE_JWK_JSON,
    ...overrides,
  };
}
