export type {
  TelegramChat,
  TelegramContact,
  TelegramDirectMessagesTopic,
  TelegramFile,
  TelegramFileBase,
  TelegramLocation,
  TelegramMessageLike,
  TelegramPoll,
  TelegramPhotoSize,
  TelegramTextQuote,
  TelegramUpdateLike,
  TelegramUser,
  TelegramVenue,
  TelegramWebhookInfo,
} from "@murphai/messaging-ingress/telegram-webhook";
