// Generated from reviewed public brand assets on 2026-09-03.
// Assets are stored locally; source URLs are provenance only and are never fetched at render time.
export const COMPARISON_LOGO_ASSETS = {
  "whoop": {"alt":"WHOOP logo","height":512,"path":"/compare/logos/whoop.png","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/whoop/id933944389","width":512},
  "oura-ring": {"alt":"Oura Ring logo","height":180,"path":"/compare/logos/oura-ring.png","sourceKind":"official","sourceUrl":"https://ouraring.com/assets/icons/apple-touch-icon.png","width":180},
  "garmin-connect": {"alt":"Garmin Connect logo","height":180,"path":"/compare/logos/garmin-connect.png","sourceKind":"official","sourceUrl":"https://share-assets.fe.garmin.com/apple-touch-icon.png","width":180},
  "google-health": {"alt":"Google Health Premium logo","height":512,"path":"/compare/logos/google-health.jpg","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/google-health-fitbit/id462638897","width":512},
  "apple-health-fitness": {"alt":"Apple Health and Fitness logo","height":512,"path":"/compare/logos/apple-health-fitness.jpg","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/apple-health/id1242545199","width":512},
  "samsung-health": {"alt":"Samsung Health logo","height":512,"path":"/compare/logos/samsung-health.jpg","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/samsung-health/id1224541484","width":512},
  "ultrahuman-ring-pro": {"alt":"Ultrahuman Ring PRO logo","height":47,"path":"/compare/logos/ultrahuman-ring-pro.png","sourceKind":"official","sourceUrl":"https://www.ultrahuman.com/logo.png","width":64},
  "polar-loop": {"alt":"POLAR Loop logo","height":20,"path":"/compare/logos/polar-loop.svg","sourceKind":"official","sourceUrl":"https://www.polar.com/img/polar-logo.svg","width":122},
  "coros": {"alt":"COROS logo","height":1024,"path":"/compare/logos/coros.svg","sourceKind":"official","sourceUrl":"https://coros.com/public/images/COROS.svg","width":1024},
  "amazfit-helio-strap": {"alt":"Amazfit Helio Strap Pro logo","height":180,"path":"/compare/logos/amazfit-helio-strap.png","sourceKind":"official","sourceUrl":"https://eu.amazfit.com/cdn/shop/files/Amazfit_brand_Logo.png?crop=center&height=180&v=1744166731&width=180","width":180},
  "ringconn": {"alt":"RingConn logo","height":142,"path":"/compare/logos/ringconn.png","sourceKind":"official","sourceUrl":"https://ringconn.com/cdn/shop/files/RC_logo-06.png?v=1767085003&width=2048","width":512},
  "circular": {"alt":"Circular Ring 2 logo","height":256,"path":"/compare/logos/circular.png","sourceKind":"official","sourceUrl":"https://cdn.prod.website-files.com/5c9cf810e0682292a9da04b8/67a204399b4bc2207ff31412_Circular-Icon-only-2025-256.png","width":256},
  "withings": {"alt":"Withings logo","height":20,"path":"/compare/logos/withings.svg","sourceKind":"official","sourceUrl":"https://www.withings.com/cdn/shop/files/Logo-black.svg?v=1775229175\\u0026width=500","width":143},
  "guava": {"alt":"Guava logo","height":512,"path":"/compare/logos/guava.jpg","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/guava-health-tracker/id1622255863","width":512},
  "careclinic": {"alt":"CareClinic logo","height":180,"path":"/compare/logos/careclinic.png","sourceKind":"official","sourceUrl":"https://careclinic.io/apple-touch-icon.png","width":180},
  "bearable": {"alt":"Bearable logo","height":101,"path":"/compare/logos/bearable.png","sourceKind":"official","sourceUrl":"https://bearable.app/wp-content/uploads/2019/08/Group-4.1-e1565005685664.png","width":98},
  "exist": {"alt":"Exist logo","height":180,"path":"/compare/logos/exist.svg","sourceKind":"official","sourceUrl":"https://exist.io/static/img/pics/homepage2.svg","width":210},
  "gyroscope": {"alt":"Gyroscope logo","height":300,"path":"/compare/logos/gyroscope.png","sourceKind":"official","sourceUrl":"https://media.gyrosco.pe/images/logo/300.png","width":300},
  "welltory": {"alt":"Welltory logo","height":120,"path":"/compare/logos/welltory.png","sourceKind":"official","sourceUrl":"https://intercom.help/welltory/assets/favicon","width":120},
  "fitnesssyncer": {"alt":"FitnessSyncer logo","height":54,"path":"/compare/logos/fitnesssyncer.png","sourceKind":"official","sourceUrl":"https://static.fitnesssyncer.com/resources/FitnessSyncer.png","width":240},
  "heads-up-health": {"alt":"Heads Up Health logo","height":512,"path":"/compare/logos/heads-up-health.jpg","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/heads-up-health-1-0-legacy/id1399133678","width":512},
  "commonhealth": {"alt":"CommonHealth logo","height":40,"path":"/compare/logos/commonhealth.svg","sourceKind":"official","sourceUrl":"https://cdn.prod.website-files.com/620bbc2a1b3d84fd471ceba8/6442bf8d0c52d1dd1c76ab4e_CommonHealth_Logo%201%20(1).svg","width":243},
  "function-health": {"alt":"Function Health logo","height":45.2955,"path":"/compare/logos/function-health.svg","sourceKind":"official","sourceUrl":"https://www.functionhealth.com/images/logo-icon.svg","width":45.5134},
  "superpower": {"alt":"Superpower logo","height":512,"path":"/compare/logos/superpower.jpg","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/superpower/id6747997159","width":512},
  "insidetracker": {"alt":"InsideTracker logo","height":32,"path":"/compare/logos/insidetracker.svg","sourceKind":"official","sourceUrl":"https://store.insidetracker.com/cdn/shop/files/logo.svg?v=1769498935&width=160","width":168},
  "siphox-health": {"alt":"SiPhox Health logo","height":29,"path":"/compare/logos/siphox-health.svg","sourceKind":"official","sourceUrl":"https://siphoxhealth.com/_next/image?url=https%3A%2F%2Fcdn.sanity.io%2Fimages%2Fq2ivj963%2Fproduction%2Ff3f9fe9a853c1a43dea1624705e4912b0e1b5862-200x29.svg%3Ffit%3Dmax%26auto%3Dformat&w=640&q=75","width":200},
  "lifeforce": {"alt":"Lifeforce logo","height":475,"path":"/compare/logos/lifeforce.png","sourceKind":"official","sourceUrl":"https://a.storyblok.com/f/130005/1969x475/f2a741a714/lifeforce_logo_black.png","width":1969},
  "mito-health": {"alt":"Mito Health logo","height":294,"path":"/compare/logos/mito-health.svg","sourceKind":"official","sourceUrl":"https://mitohealth.com/_astro/f8cKrhMz.svg","width":995},
  "parsley-health": {"alt":"Parsley Health logo","height":16,"path":"/compare/logos/parsley-health.svg","sourceKind":"official","sourceUrl":"https://www.parsleyhealth.com/icons/logo-horizontal-bone.svg","width":123},
  "wild-health": {"alt":"Wild Health logo","height":24,"path":"/compare/logos/wild-health.svg","sourceKind":"official","sourceUrl":"https://cdn.prod.website-files.com/60d0c19652832c888121dff7/6598399d4c4683dab82a532a_WH%20Logo%20Registered%20Black.svg","width":166},
  "hone-health": {"alt":"Hone Health logo","height":300,"path":"/compare/logos/hone-health.png","sourceKind":"official","sourceUrl":"https://honehealth.com/wp-content/uploads/2024/04/cropped-favicon-300x300.png","width":300},
  "quest-health": {"alt":"Quest Health logo","height":36,"path":"/compare/logos/quest-health.svg","sourceKind":"official","sourceUrl":"https://www.questhealth.com/on/demandware.static/Sites-QD-CIT-Site/-/default/dwd3afd741/images/qd/quest-logo.svg","width":135},
  "labcorp-ondemand": {"alt":"Labcorp OnDemand logo","height":180,"path":"/compare/logos/labcorp-ondemand.png","sourceKind":"official","sourceUrl":"https://www.ondemand.labcorp.com/content/dam/labcorp-ondemand/assets/favicons/apple-touch-icon.png","width":180},
  "bioniq": {"alt":"Bioniq logo","height":23,"path":"/compare/logos/bioniq.svg","sourceKind":"official","sourceUrl":"https://cdn.prod.website-files.com/655df381efb0b50a5ce3198e/655df381efb0b50a5ce3200a_bioniq-logo.svg","width":86},
  "neko-health": {"alt":"Neko Health logo","height":512,"path":"/compare/logos/neko-health.jpg","sourceKind":"official","sourceUrl":"https://apps.apple.com/in/app/neko-health/id6751233363","width":512},
  "fountain-life": {"alt":"Fountain Life logo","height":512,"path":"/compare/logos/fountain-life.jpg","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/fountain-life/id6473792565","width":512},
  "prenuvo": {"alt":"Prenuvo logo","height":256,"path":"/compare/logos/prenuvo.png","sourceKind":"official","sourceUrl":"https://cdn.prod.website-files.com/653836f64e8770bb2190b74d/65429febfc26b093f842b22e_prenuvo-favicon.png","width":256},
  "trudiagnostic": {"alt":"TruDiagnostic logo","height":100,"path":"/compare/logos/trudiagnostic.svg","sourceKind":"official","sourceUrl":"https://shop.trudiagnostic.com/cdn/shop/files/Logo_With_Tagline_On_Light.svg?v=1723655696&width=210","width":300},
  "tally-health": {"alt":"Tally Health logo","height":300,"path":"/compare/logos/tally-health.png","sourceKind":"official","sourceUrl":"https://attachments.gorgias.help/3dBwk7WdgexNZ9mO/hc/r1WE86rJvb6J4Mvg/2025080521-9b6d3317-c3db-4108-9bce-7be930fce79e-tally_favicon_300x300.png","width":300},
  "future-pro": {"alt":"Future Pro logo","height":512,"path":"/compare/logos/future-pro.jpg","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/future-pro-personal-training/id1288178982","width":512},
  "fitbod": {"alt":"Fitbod logo","height":512,"path":"/compare/logos/fitbod.png","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/fitbod-gym-fitness-planner/id1041517543","width":512},
  "caliber": {"alt":"Caliber logo","height":180,"path":"/compare/logos/caliber.png","sourceKind":"official","sourceUrl":"https://caliberstrong.com/wp-content/uploads/2020/02/cropped-Caliber-Favicon-180x180.png","width":180},
  "freeletics": {"alt":"Freeletics logo","height":16,"path":"/compare/logos/freeletics.svg","sourceKind":"official","sourceUrl":"https://assets.freeletics.net/images/favicon.svg","width":16},
  "centr": {"alt":"Centr logo","height":512,"path":"/compare/logos/centr.jpg","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/centr-strength-fitness-app/id1382530817","width":512},
  "ladder": {"alt":"Ladder logo","height":130,"path":"/compare/logos/ladder.png","sourceKind":"official","sourceUrl":"https://www.joinladder.com/assets/logo/white.png","width":969},
  "nike-training-club": {"alt":"Nike Training Club logo","height":152,"path":"/compare/logos/nike-training-club.png","sourceKind":"official","sourceUrl":"https://www.nike.com/apple-touch-icon-152x152-precomposed.png","width":152},
  "peloton-app": {"alt":"Peloton App logo","height":192,"path":"/compare/logos/peloton-app.png","sourceKind":"official","sourceUrl":"https://www.onepeloton.com/images/apple-touch-icon-192.png","width":192},
  "tonal": {"alt":"Tonal logo","height":60,"path":"/compare/logos/tonal.png","sourceKind":"official","sourceUrl":"https://tonal.com/cdn/shop/files/Tonal-Icon-Logo.png?v=1757541446\\u0026width=80","width":80},
  "trainwell": {"alt":"trainwell logo","height":512,"path":"/compare/logos/trainwell.jpg","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/trainwell-personal-training/id1466445684","width":512},
  "juggernautai": {"alt":"JuggernautAI logo","height":80,"path":"/compare/logos/juggernautai.png","sourceKind":"official","sourceUrl":"https://cdn.prod.website-files.com/653a0fc479ec415433fc9e9a/653a0fc479ec415433fc9ec9_main-logo.webp","width":395},
  "alpha-progression": {"alt":"Alpha Progression logo","height":1536,"path":"/compare/logos/alpha-progression.svg","sourceKind":"official","sourceUrl":"https://alphaprogression.com/img/alpha-progression-logo.svg","width":1536},
  "strong": {"alt":"Strong logo","height":152,"path":"/compare/logos/strong.png","sourceKind":"official","sourceUrl":"https://d33v4339jhl8k0.cloudfront.net/docs/assets/57baea42c697917de37cf9d3/images/5d263a84042863478674bd91/logo2.png","width":152},
  "hevy": {"alt":"Hevy logo","height":180,"path":"/compare/logos/hevy.png","sourceKind":"official","sourceUrl":"https://www.hevyapp.com/wp-content/uploads/cropped-hevy-logo-180x180.png","width":180},
  "strava": {"alt":"Strava logo","height":512,"path":"/compare/logos/strava.png","sourceKind":"official","sourceUrl":"https://intercom.help/strava-1cd7bea78485/assets/favicon","width":512},
  "runna": {"alt":"Runna logo","height":72,"path":"/compare/logos/runna.png","sourceKind":"official","sourceUrl":"https://cdn.prod.website-files.com/6241c8c95eb4fa2f8a36e792/62c705320ef85ec760aad248_logo-runna.png","width":228},
  "apple-fitness-plus": {"alt":"Apple Fitness+ logo","height":512,"path":"/compare/logos/apple-fitness-plus.jpg","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/apple-fitness/id1208224953","width":512},
  "rp-hypertrophy-app": {"alt":"RP Hypertrophy App logo","height":75,"path":"/compare/logos/rp-hypertrophy-app.svg","sourceKind":"official","sourceUrl":"https://rpstrength.com/cdn/shop/files/RP-Logo.svg?v=1708462558\\u0026width=500","width":268},
  "boostcamp": {"alt":"Boostcamp logo","height":180,"path":"/compare/logos/boostcamp.png","sourceKind":"official","sourceUrl":"https://www.boostcamp.app/apple-touch-icon.png","width":180},
  "shred": {"alt":"SHRED logo","height":512,"path":"/compare/logos/shred.jpg","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/shred-gym-home-workouts/id1439828095","width":512},
  "jefit": {"alt":"JEFIT logo","height":77,"path":"/compare/logos/jefit.svg","sourceKind":"official","sourceUrl":"https://www.jefit.com/icons/logo/nameIcon.svg","width":292},
  "myfitnesspal": {"alt":"MyFitnessPal logo","height":512,"path":"/compare/logos/myfitnesspal.jpg","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/myfitnesspal-calorie-counter/id341232718","width":512},
  "cronometer": {"alt":"Cronometer logo","height":512,"path":"/compare/logos/cronometer.png","sourceKind":"official","sourceUrl":"https://cdn1.cronometer.com/wf-2026-08-25/images/webclip.png","width":512},
  "macrofactor": {"alt":"MacroFactor logo","height":180,"path":"/compare/logos/macrofactor.png","sourceKind":"official","sourceUrl":"https://macrofactor.com/wp-content/uploads/2025/09/cropped-MF_Avatar_Square_150ppi-180x180.png","width":180},
  "noom": {"alt":"Noom logo","height":180,"path":"/compare/logos/noom.png","sourceKind":"official","sourceUrl":"https://www.noom.com/tachyon/2024/09/noom_logo_symbol_tarocco_512x512.png?fit=180%2C180","width":180},
  "weight-watchers": {"alt":"Weight Watchers logo","height":219,"path":"/compare/logos/weight-watchers.svg","sourceKind":"official","sourceUrl":"https://a.storyblok.com/f/286334833788875/1190x219/14b9ec3456/ww.svg","width":1190},
  "lose-it": {"alt":"Lose It! logo","height":1031.17,"path":"/compare/logos/lose-it.svg","sourceKind":"official","sourceUrl":"https://assets.loseit.com/website/corporate/LoseIt_Logo_FullColor_TM.svg","width":2570.33},
  "foodnoms": {"alt":"Foodnoms logo","height":1200,"path":"/compare/logos/foodnoms.png","sourceKind":"official","sourceUrl":"https://framerusercontent.com/images/b7R3zOTrOmIs8jFCHOpQIIiZZs.png","width":1200},
  "my-net-diary": {"alt":"MyNetDiary logo","height":180,"path":"/compare/logos/my-net-diary.png","sourceKind":"official","sourceUrl":"https://assets.mynetdiary.com/images/apple-touch-icon/2023_180x180.png","width":180},
  "lifesum": {"alt":"Lifesum logo","height":166,"path":"/compare/logos/lifesum.png","sourceKind":"official","sourceUrl":"https://storage.crisp.chat/users/helpdesk/website/-/1/a/8/1/1a8129f0defae40/lifesumeheader-logo800px_o509ix.png","width":800},
  "yazio": {"alt":"YAZIO logo","height":180,"path":"/compare/logos/yazio.svg","sourceKind":"official","sourceUrl":"https://images.yazio-cdn.com/process/plain/frontend/web-funnels/icons/favicon.svg","width":180},
  "lumen": {"alt":"Lumen logo","height":180,"path":"/compare/logos/lumen.png","sourceKind":"official","sourceUrl":"https://cdn.us.prod-website.lumen.me/website-journal/build/assets/images/favicon/apple-touch-icon.png","width":180},
  "january-ai": {"alt":"January logo","height":256,"path":"/compare/logos/january-ai.png","sourceKind":"official","sourceUrl":"https://january.ai/apple-touch-icon.png","width":256},
  "signos": {"alt":"Signos logo","height":512,"path":"/compare/logos/signos.jpg","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/signos/id1534943157","width":512},
  "levels": {"alt":"Levels logo","height":152,"path":"/compare/logos/levels.png","sourceKind":"official","sourceUrl":"https://d33v4339jhl8k0.cloudfront.net/docs/assets/5f6243234cedfd0017635412/images/6240d2c1ab585b230a8a54ad/LEVELS_Logo_Logomark_Black.png","width":152},
  "zoe": {"alt":"ZOE logo","height":125,"path":"/compare/logos/zoe.png","sourceKind":"official","sourceUrl":"https://zoe.com/assets/img/ds/zoe-logo-brand.png","width":356},
  "nourish": {"alt":"Nourish logo","height":32,"path":"/compare/logos/nourish.svg","sourceKind":"official","sourceUrl":"https://cdn.prod.website-files.com/699ce714348d0db6b6640eaf/699ce714348d0db6b664123b_Nourish%20Logo.svg","width":141},
  "fay": {"alt":"Fay logo","height":512,"path":"/compare/logos/fay.jpg","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/fay-nutrition-dietitians/id6711357628","width":512},
  "nutrisense": {"alt":"Nutrisense logo","height":129,"path":"/compare/logos/nutrisense.png","sourceKind":"official","sourceUrl":"https://assets.nutrisense.io/62c477aa7b7db12cfffa5de3/65c64ecfc547df1ff4eeb3ec_nutrisense_logo.png","width":612},
  "carb-manager": {"alt":"Carb Manager logo","height":512,"path":"/compare/logos/carb-manager.jpg","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/carb-manager-keto-macro-log/id410089731","width":512},
  "cal-ai": {"alt":"Cal AI logo","height":492,"path":"/compare/logos/cal-ai.png","sourceKind":"official","sourceUrl":"https://calai.app/logo.png","width":492},
  "atemate": {"alt":"AteMate logo","height":180,"path":"/compare/logos/atemate.png","sourceKind":"official","sourceUrl":"https://framerusercontent.com/images/84xumqMDG54sfM1gtNrlM1LjB78.png","width":180},
  "eight-sleep": {"alt":"Eight Sleep logo","height":27,"path":"/compare/logos/eight-sleep.svg","sourceKind":"official","sourceUrl":"https://res.cloudinary.com/eightsleep/image/upload/v1761171870/Logo_White_xwtn4w.svg","width":64},
  "sleep-cycle": {"alt":"Sleep Cycle logo","height":28,"path":"/compare/logos/sleep-cycle.svg","sourceKind":"official","sourceUrl":"https://sleepcycle.com/sqs-icons/icon-sleep.svg","width":28},
  "rise-sleep-tracker": {"alt":"RISE: Sleep Tracker logo","height":293,"path":"/compare/logos/rise-sleep-tracker.png","sourceKind":"official","sourceUrl":"https://www.risescience.com/assets/632dd2dfbefab022e1a7fd8c_App_icon.png","width":293},
  "autosleep": {"alt":"AutoSleep logo","height":160,"path":"/compare/logos/autosleep.png","sourceKind":"official","sourceUrl":"https://lh3.googleusercontent.com/sitesv/AG8ngQW932AHHwiFZnwSgugWhRDSRAsUSuEeAC5FnHp3CCvY4h0e0ZH5024UvG8yJ6idPB2x2Nps8_AfkxSXB1-GR4vW2bI5DQT_bbtL9gJXhz8xW2uapofeY5C5AQqcilGmaKH0Cv1jcCu1KbC_cnqXkpMtK-25wyxavQzPLVeRBzdDEUbixf2kQNa3KjCQvIN0nA","width":160},
  "pillow": {"alt":"Pillow logo","height":300,"path":"/compare/logos/pillow.png","sourceKind":"official","sourceUrl":"https://pillow.app/wp-content/uploads/pillowIcon-v5-light-rounded-300x300.png","width":300},
  "sleepwatch": {"alt":"SleepWatch logo","height":512,"path":"/compare/logos/sleepwatch.jpg","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/sleepwatch-top-sleep-tracker/id1138066420","width":512},
  "sleepscore": {"alt":"SleepScore logo","height":180,"path":"/compare/logos/sleepscore.png","sourceKind":"official","sourceUrl":"https://validated.sleepscore.com/cdn/shop/t/33/assets/apple-icon-180x180.png?v=15819145692377976101722374781","width":180},
  "sleep-reset": {"alt":"Sleep Reset logo","height":56,"path":"/compare/logos/sleep-reset.svg","sourceKind":"official","sourceUrl":"https://cdn.prod.website-files.com/61e6c90d43582777cf0fc084/648303b9cd99deffb8cd44e1_logo.svg","width":221},
  "calm": {"alt":"Calm logo","height":41,"path":"/compare/logos/calm.svg","sourceKind":"official","sourceUrl":"https://www.calm.com/_n/images/calm-logo.svg","width":103},
  "headspace": {"alt":"Headspace logo","height":32,"path":"/compare/logos/headspace.svg","sourceKind":"official","sourceUrl":"https://images.ctfassets.net/v3n26e09qg2r/64mSWkeWKMrDAwmTViOdmS/ec6d493260ff34b5a6205be6aec2a485/Logo.svg","width":32},
  "balance": {"alt":"Balance logo","height":512,"path":"/compare/logos/balance.jpg","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/balance-meditation-sleep/id1361356590","width":512},
  "wysa": {"alt":"Wysa logo","height":1092,"path":"/compare/logos/wysa.png","sourceKind":"official","sourceUrl":"https://cdn.wysa.io/logos/logo.png","width":2268},
  "daylio": {"alt":"Daylio logo","height":180,"path":"/compare/logos/daylio.png","sourceKind":"official","sourceUrl":"https://daylio.net/wp-content/uploads/2020/04/cropped-favicon-180x180.png","width":180},
  "finch": {"alt":"Finch logo","height":512,"path":"/compare/logos/finch.png","sourceKind":"official","sourceUrl":"https://befinch.notion.site/images/logo-ios.png","width":512},
  "muse": {"alt":"Muse S Athena logo","height":180,"path":"/compare/logos/muse.png","sourceKind":"official","sourceUrl":"https://choosemuse.com/cdn/shop/t/80/assets/apple-touch-icon.png?v=49269511737057087671770937375","width":180},
  "apollo-neuro": {"alt":"Apollo Neuro logo","height":512,"path":"/compare/logos/apollo-neuro.jpg","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/apollo-neuro/id1457385148","width":512},
  "bodybuddy": {"alt":"BodyBuddy logo","height":1024,"path":"/compare/logos/bodybuddy.png","sourceKind":"official","sourceUrl":"https://bodybuddy.app/icon-512.png","width":1024},
  "ada": {"alt":"Ada logo","height":180,"path":"/compare/logos/ada.png","sourceKind":"official","sourceUrl":"https://ada.com/apple-touch-icon.png","width":180},
  "hume-health": {"alt":"Hume Health logo","height":36,"path":"/compare/logos/hume-health.png","sourceKind":"official","sourceUrl":"https://humehealth.com/cdn/shop/files/hume_health_logo.png?v=1697520680\\u0026width=267","width":267},
  "humanity": {"alt":"Humanity logo","height":24,"path":"/compare/logos/humanity.svg","sourceKind":"official","sourceUrl":"https://cdn.prod.website-files.com/66451ef81f7cd0f029179bf1/66451ef81f7cd0f029179bf4_Humanity%20logo.svg","width":301},
  "healthily": {"alt":"Healthily logo","height":512,"path":"/compare/logos/healthily.jpg","sourceKind":"official","sourceUrl":"https://apps.apple.com/us/app/health-tracker-healthily/id1491316446","width":512},
  "tempo": {"alt":"Tempo logo","height":1920,"path":"/compare/logos/tempo.png","sourceKind":"official","sourceUrl":"https://jointempo.app/assets/tempo-icon.png","width":1920},
  "nudge": {"alt":"Nudge logo","height":1000,"path":"/compare/logos/nudge.png","sourceKind":"official","sourceUrl":"https://www.nudge.gs/favicon.png","width":1000},
  "matcha": {"alt":"Matcha logo","height":1024,"path":"/compare/logos/matcha.jpg","sourceKind":"official","sourceUrl":"https://heymatcha.app/assets/logomark.jpg","width":1024},
  "iris": {"alt":"Iris logo","height":272,"path":"/compare/logos/iris.svg","sourceKind":"official","sourceUrl":"https://chatwithiris.com/iris-logo-mark.svg","width":272},
  "sam-by-sunflower": {"alt":"Sam by Sunflower logo","height":180,"path":"/compare/logos/sam-by-sunflower.png","sourceKind":"official","sourceUrl":"https://sunflowersober.com/apple-icon.png","width":180},
  "bo": {"alt":"Bo logo","height":180,"path":"/compare/logos/bo.png","sourceKind":"official","sourceUrl":"https://getbo.com/icons/apple-icon-180x180.png","width":180},
  "capy": {"alt":"Capy by MeAgain logo","height":180,"path":"/compare/logos/capy.png","sourceKind":"official","sourceUrl":"https://meagain.com/apple-touch-icon.png","width":180},
  "mochi": {"alt":"Mochi logo","height":512,"path":"/compare/logos/mochi.png","sourceKind":"official","sourceUrl":"https://mochitext.com/android-chrome-512x512.png","width":512},
  "askpetal": {"alt":"AskPetal logo","height":512,"path":"/compare/logos/askpetal.png","sourceKind":"official","sourceUrl":"https://askpetal.com/favicon.png","width":512},
  "miora": {"alt":"miora logo","height":1024,"path":"/compare/logos/miora.png","sourceKind":"official","sourceUrl":"https://getmiora.com/favicon.png","width":1024},
} as const;

export type ComparisonLogoSlug = keyof typeof COMPARISON_LOGO_ASSETS;

export type ComparisonLogoAsset =
  (typeof COMPARISON_LOGO_ASSETS)[ComparisonLogoSlug];

export function getComparisonLogoAsset(
  slug: string,
): ComparisonLogoAsset | null {
  if (!Object.hasOwn(COMPARISON_LOGO_ASSETS, slug)) {
    return null;
  }

  return COMPARISON_LOGO_ASSETS[slug as ComparisonLogoSlug];
}

export function hasComparisonLogoAsset(slug: string): boolean {
  return Object.hasOwn(COMPARISON_LOGO_ASSETS, slug);
}
