export const HOSTED_ASSISTANT_PROVIDER_ENV = 'HOSTED_ASSISTANT_PROVIDER'
export const HOSTED_ASSISTANT_MODEL_ENV = 'HOSTED_ASSISTANT_MODEL'
export const HOSTED_ASSISTANT_BASE_URL_ENV = 'HOSTED_ASSISTANT_BASE_URL'
export const HOSTED_ASSISTANT_API_KEY_ENV = 'HOSTED_ASSISTANT_API_KEY_ENV'
export const HOSTED_ASSISTANT_PROVIDER_NAME_ENV = 'HOSTED_ASSISTANT_PROVIDER_NAME'
export const HOSTED_ASSISTANT_CODEX_COMMAND_ENV = 'HOSTED_ASSISTANT_CODEX_COMMAND'
export const HOSTED_ASSISTANT_APPROVAL_POLICY_ENV = 'HOSTED_ASSISTANT_APPROVAL_POLICY'
export const HOSTED_ASSISTANT_SANDBOX_ENV = 'HOSTED_ASSISTANT_SANDBOX'
export const HOSTED_ASSISTANT_PROFILE_ENV = 'HOSTED_ASSISTANT_PROFILE'
export const HOSTED_ASSISTANT_REASONING_EFFORT_ENV = 'HOSTED_ASSISTANT_REASONING_EFFORT'
export const HOSTED_ASSISTANT_OSS_ENV = 'HOSTED_ASSISTANT_OSS'
export const HOSTED_ASSISTANT_GATEWAY_ONLY_PROVIDERS_ENV =
  'HOSTED_ASSISTANT_GATEWAY_ONLY_PROVIDERS'
export const HOSTED_ASSISTANT_ELEVENLABS_VOICE_ID_ENV =
  'MURPH_ELEVENLABS_VOICE_ID'
export const HOSTED_ASSISTANT_ELEVENLABS_MODEL_ID_ENV =
  'MURPH_ELEVENLABS_MODEL_ID'

export const HOSTED_ASSISTANT_CONFIG_ENV_NAMES = [
  HOSTED_ASSISTANT_PROVIDER_ENV,
  HOSTED_ASSISTANT_MODEL_ENV,
  HOSTED_ASSISTANT_APPROVAL_POLICY_ENV,
  HOSTED_ASSISTANT_SANDBOX_ENV,
  HOSTED_ASSISTANT_REASONING_EFFORT_ENV,
  HOSTED_ASSISTANT_ELEVENLABS_VOICE_ID_ENV,
  HOSTED_ASSISTANT_ELEVENLABS_MODEL_ID_ENV,
] as const

export const HOSTED_ASSISTANT_ALLOWED_API_KEY_ENV_NAMES = [
  'ELEVENLABS_API_KEY',
  'OPENAI_API_KEY',
] as const
