export const HOSTED_ASSISTANT_PROVIDER_ENV = 'HOSTED_ASSISTANT_PROVIDER'
export const HOSTED_ASSISTANT_MODEL_ENV = 'HOSTED_ASSISTANT_MODEL'
export const HOSTED_ASSISTANT_BASE_URL_ENV = 'HOSTED_ASSISTANT_BASE_URL'
export const HOSTED_ASSISTANT_API_KEY_ENV = 'HOSTED_ASSISTANT_API_KEY_ENV'
export const HOSTED_ASSISTANT_PROVIDER_NAME_ENV = 'HOSTED_ASSISTANT_PROVIDER_NAME'
export const HOSTED_ASSISTANT_CODEX_COMMAND_ENV = 'HOSTED_ASSISTANT_CODEX_COMMAND'
export const HOSTED_ASSISTANT_APPROVAL_POLICY_ENV = 'HOSTED_ASSISTANT_APPROVAL_POLICY'
export const HOSTED_ASSISTANT_SANDBOX_ENV = 'HOSTED_ASSISTANT_SANDBOX'
export const HOSTED_ASSISTANT_PROFILE_ENV = 'HOSTED_ASSISTANT_PROFILE'
export const HOSTED_ASSISTANT_REASONING_EFFORT_ENV = 'HOSTED_ASSISTANT_REASONING_EFFORT'
export const HOSTED_ASSISTANT_OSS_ENV = 'HOSTED_ASSISTANT_OSS'
export const HOSTED_ASSISTANT_ZERO_DATA_RETENTION_ENV =
  'HOSTED_ASSISTANT_ZERO_DATA_RETENTION'
export const HOSTED_ASSISTANT_GATEWAY_ONLY_PROVIDERS_ENV =
  'HOSTED_ASSISTANT_GATEWAY_ONLY_PROVIDERS'

export const HOSTED_ASSISTANT_CONFIG_ENV_NAMES = [
  HOSTED_ASSISTANT_PROVIDER_ENV,
  HOSTED_ASSISTANT_MODEL_ENV,
  HOSTED_ASSISTANT_BASE_URL_ENV,
  HOSTED_ASSISTANT_API_KEY_ENV,
  HOSTED_ASSISTANT_PROVIDER_NAME_ENV,
  HOSTED_ASSISTANT_CODEX_COMMAND_ENV,
  HOSTED_ASSISTANT_APPROVAL_POLICY_ENV,
  HOSTED_ASSISTANT_SANDBOX_ENV,
  HOSTED_ASSISTANT_PROFILE_ENV,
  HOSTED_ASSISTANT_REASONING_EFFORT_ENV,
  HOSTED_ASSISTANT_OSS_ENV,
  HOSTED_ASSISTANT_ZERO_DATA_RETENTION_ENV,
  HOSTED_ASSISTANT_GATEWAY_ONLY_PROVIDERS_ENV,
] as const

export const HOSTED_ASSISTANT_ALLOWED_API_KEY_ENV_NAMES = [
  'ANTHROPIC_API_KEY',
  'CEREBRAS_API_KEY',
  'DEEPSEEK_API_KEY',
  'FIREWORKS_API_KEY',
  'GOOGLE_API_KEY',
  'GOOGLE_GENERATIVE_AI_API_KEY',
  'GROQ_API_KEY',
  'HF_TOKEN',
  'HUGGINGFACEHUB_API_TOKEN',
  'HUGGINGFACE_API_KEY',
  'HUGGING_FACE_HUB_TOKEN',
  'LITELLM_PROXY_API_KEY',
  'LM_STUDIO_API_KEY',
  'MISTRAL_API_KEY',
  'NVIDIA_API_KEY',
  'NGC_API_KEY',
  'OLLAMA_API_KEY',
  'OPENAI_API_KEY',
  'OPENROUTER_API_KEY',
  'PERPLEXITY_API_KEY',
  'TOGETHER_API_KEY',
  'VERCEL_AI_API_KEY',
  'VENICE_API_KEY',
  'VLLM_API_KEY',
  'XAI_API_KEY',
] as const
