const HOSTED_EXECUTION_RESULTS_WORKER_HOST = "results.worker";

export const HOSTED_EXECUTION_CALLBACK_HOSTS = {
  artifacts: "artifacts.worker",
  results: HOSTED_EXECUTION_RESULTS_WORKER_HOST,
  commit: HOSTED_EXECUTION_RESULTS_WORKER_HOST,
  email: HOSTED_EXECUTION_RESULTS_WORKER_HOST,
  sideEffects: HOSTED_EXECUTION_RESULTS_WORKER_HOST,
} as const;

export const HOSTED_EXECUTION_PROXY_HOSTS = {
  deviceSync: "device-sync.worker",
  usage: "usage.worker",
} as const;

export const DEFAULT_HOSTED_EXECUTION_ARTIFACTS_BASE_URL =
  `http://${HOSTED_EXECUTION_CALLBACK_HOSTS.artifacts}`;
export const DEFAULT_HOSTED_EXECUTION_RESULTS_BASE_URL =
  `http://${HOSTED_EXECUTION_CALLBACK_HOSTS.results}`;
export const DEFAULT_HOSTED_EXECUTION_COMMIT_BASE_URL =
  DEFAULT_HOSTED_EXECUTION_RESULTS_BASE_URL;
export const DEFAULT_HOSTED_EXECUTION_DEVICE_SYNC_PROXY_BASE_URL =
  `http://${HOSTED_EXECUTION_PROXY_HOSTS.deviceSync}`;
export const DEFAULT_HOSTED_EXECUTION_EMAIL_BASE_URL =
  DEFAULT_HOSTED_EXECUTION_RESULTS_BASE_URL;
export const DEFAULT_HOSTED_EXECUTION_SIDE_EFFECTS_BASE_URL =
  DEFAULT_HOSTED_EXECUTION_RESULTS_BASE_URL;
export const DEFAULT_HOSTED_EXECUTION_USAGE_PROXY_BASE_URL =
  `http://${HOSTED_EXECUTION_PROXY_HOSTS.usage}`;
