export {
  HOSTED_RUNTIME_GROUP_SHARED_READ_MAX_PROJECTION_SCOPES as ASSISTANT_HOSTED_GROUP_SHARED_READ_MAX_PROJECTION_SCOPES,
} from '@murphai/hosted-execution/runtime-control'
export const ASSISTANT_HOSTED_GROUP_SHARED_READ_MAX_RESULT_CODE_UNITS = 200 * 1024
