import {
  HOSTED_RUNTIME_GROUP_CHAT_PARTICIPANTS_MAX,
  HOSTED_RUNTIME_GROUP_SENDER_HANDLE_MAX_CODE_POINTS,
  HOSTED_RUNTIME_GROUP_SHARED_READ_DISPLAY_NAME_MAX_CODE_POINTS,
  HOSTED_RUNTIME_GROUP_SHARED_READ_MAX_PROJECTION_SCOPES,
  HOSTED_RUNTIME_GROUP_SHARED_READ_PARTICIPANT_ID_MAX_CODE_POINTS,
  HOSTED_RUNTIME_GROUP_SHARED_READ_SCOPE_KEY_MAX_CODE_POINTS,
} from '@murphai/hosted-execution/runtime-control'
// Retain the pre-history per-scope model budget. Expanded reads are date-paged.
const GROUP_SHARED_READ_MODEL_PROJECTION_MAX_CODE_UNITS = 320 * 1024

export {
  HOSTED_RUNTIME_GROUP_SHARED_READ_MAX_PROJECTION_SCOPES as ASSISTANT_HOSTED_GROUP_SHARED_READ_MAX_PROJECTION_SCOPES,
}

const JSON_MAX_CODE_UNITS_PER_CODE_POINT = 6
const GROUP_SHARED_READ_MODEL_FIXED_ENVELOPE_MAX_CODE_UNITS = 4 * 1024
const GROUP_SHARED_READ_MODEL_MEMBER_IDENTITY_MAX_CODE_UNITS =
  JSON_MAX_CODE_UNITS_PER_CODE_POINT * (
    HOSTED_RUNTIME_GROUP_CHAT_PARTICIPANTS_MAX
      * HOSTED_RUNTIME_GROUP_SENDER_HANDLE_MAX_CODE_POINTS
    + HOSTED_RUNTIME_GROUP_SHARED_READ_PARTICIPANT_ID_MAX_CODE_POINTS
    + HOSTED_RUNTIME_GROUP_SHARED_READ_DISPLAY_NAME_MAX_CODE_POINTS
    // Each scope key occurs once in the projection map and once in the
    // requested-scope list.
    + 2 * HOSTED_RUNTIME_GROUP_SHARED_READ_MAX_PROJECTION_SCOPES
      * HOSTED_RUNTIME_GROUP_SHARED_READ_SCOPE_KEY_MAX_CODE_POINTS
  )

// Keep the established model ceiling rather than multiplying it by the new
// storage ceiling. A single history page (256 KiB) plus its member envelope fits.
// Oversized ordinary reads omit whole members explicitly; retry one participant
// and one requested scope instead of dropping dates or sources.
export const ASSISTANT_HOSTED_GROUP_SHARED_READ_MAX_RESULT_CODE_UNITS =
  HOSTED_RUNTIME_GROUP_SHARED_READ_MAX_PROJECTION_SCOPES
    * GROUP_SHARED_READ_MODEL_PROJECTION_MAX_CODE_UNITS
  + GROUP_SHARED_READ_MODEL_MEMBER_IDENTITY_MAX_CODE_UNITS
  + GROUP_SHARED_READ_MODEL_FIXED_ENVELOPE_MAX_CODE_UNITS
