import {
  HOSTED_RUNTIME_GROUP_CHAT_PARTICIPANTS_MAX,
  HOSTED_RUNTIME_GROUP_SENDER_HANDLE_MAX_CODE_POINTS,
  HOSTED_RUNTIME_GROUP_SHARED_READ_DISPLAY_NAME_MAX_CODE_POINTS,
  HOSTED_RUNTIME_GROUP_SHARED_READ_MAX_PROJECTION_SCOPES,
  HOSTED_RUNTIME_GROUP_SHARED_READ_PARTICIPANT_ID_MAX_CODE_POINTS,
  HOSTED_RUNTIME_GROUP_SHARED_READ_SCOPE_KEY_MAX_CODE_POINTS,
} from '@murphai/hosted-execution/runtime-control'
import {
  HOSTED_VAULT_SHARE_SERIALIZED_PROJECTION_MAX_BYTES,
} from '@murphai/hosted-execution/vault-share'

export {
  HOSTED_RUNTIME_GROUP_SHARED_READ_MAX_PROJECTION_SCOPES as ASSISTANT_HOSTED_GROUP_SHARED_READ_MAX_PROJECTION_SCOPES,
}

const JSON_MAX_CODE_UNITS_PER_CODE_POINT = 6
const GROUP_SHARED_READ_MODEL_FIXED_ENVELOPE_MAX_CODE_UNITS = 4 * 1024
const GROUP_SHARED_READ_MODEL_MEMBER_IDENTITY_MAX_CODE_UNITS =
  JSON_MAX_CODE_UNITS_PER_CODE_POINT * (
    HOSTED_RUNTIME_GROUP_CHAT_PARTICIPANTS_MAX
      * HOSTED_RUNTIME_GROUP_SENDER_HANDLE_MAX_CODE_POINTS
    + HOSTED_RUNTIME_GROUP_SHARED_READ_PARTICIPANT_ID_MAX_CODE_POINTS
    + HOSTED_RUNTIME_GROUP_SHARED_READ_DISPLAY_NAME_MAX_CODE_POINTS
    // Each scope key occurs once in the projection map and once in the
    // requested-scope list.
    + 2 * HOSTED_RUNTIME_GROUP_SHARED_READ_MAX_PROJECTION_SCOPES
      * HOSTED_RUNTIME_GROUP_SHARED_READ_SCOPE_KEY_MAX_CODE_POINTS
  )

// A single member must fit before roster compaction can omit whole members.
// Compose the complete per-projection transport authority with the maximum
// three-scope request and the parser-bounded member envelope, including JSON's
// worst-case escaping. This keeps admission derived from existing contracts.
export const ASSISTANT_HOSTED_GROUP_SHARED_READ_MAX_RESULT_CODE_UNITS =
  HOSTED_RUNTIME_GROUP_SHARED_READ_MAX_PROJECTION_SCOPES
    * HOSTED_VAULT_SHARE_SERIALIZED_PROJECTION_MAX_BYTES
  + GROUP_SHARED_READ_MODEL_MEMBER_IDENTITY_MAX_CODE_UNITS
  + GROUP_SHARED_READ_MODEL_FIXED_ENVELOPE_MAX_CODE_UNITS
