export const MURPH_PERSONAL_PATTERNS_UPDATE_AUTOMATION_ID =
  'automation_01M0A7T3RN5VPD8C2K4V6X9ZBQ'

export const MURPH_WEEKLY_USAGE_OPTIMIZER_AUTOMATION_ID =
  'automation_01K7A8B9C0D1E2F3G4H5J6K7MN'

export const MURPH_WEEKLY_HEALTH_DIGEST_AUTOMATION_ID =
  'automation_01JNW7YJ7MNE7M9Q2QWQK4Z3FY'

export const MURPH_WEEKLY_HEALTH_INSIGHT_AUTOMATION_ID =
  'automation_X3GPAWV2CCHNCYHAAJ4CE2M144'

export const MURPH_JOURNAL_CONNECTED_CONTEXT_MORNING_AUTOMATION_ID =
  'automation_01M1J7C8M0RN1NGC0NT3XT7D2A'

export const MURPH_MONTHLY_IMPROVEMENT_COACH_AUTOMATION_ID =
  'automation_01K2WKKY3F8Q4R5S6T7V8W9XAB'

export const MURPH_WEEKLY_HEALTH_RESEARCH_SCOUT_AUTOMATION_ID =
  'automation_01K0EXA5C0VT9F7X3KG6JMPZ5A'
