import path from "node:path";

export const HOSTED_LOCAL_DEV_CRYPTO_STATE_FILE = path.join(
  ".tmp",
  "hosted-local-dev-crypto-state.dev.vars",
);

export const HOSTED_LOCAL_PERSISTED_STATE_ENV_NAMES = [
  "HOSTED_CRYPTO_AUTHORITY_SIGN_KEY_VERSION",
  "HOSTED_CRYPTO_AUTHORITY_SIGN_PUBLIC_KEY_PEM",
  "HOSTED_CRYPTO_AUTHORITY_VERIFY_KEYRING_JSON",
  "HOSTED_CRYPTO_CLOUDFLARE_AUTOMATION_KEY_ID",
  "HOSTED_CRYPTO_CLOUDFLARE_AUTOMATION_PRIVATE_JWK",
  "HOSTED_CRYPTO_CLOUDFLARE_AUTOMATION_PUBLIC_JWK",
  "HOSTED_CRYPTO_ENV",
  "HOSTED_CRYPTO_GCP_AUTHORITY_SIGN_KEY_VERSION",
  "HOSTED_CRYPTO_GCP_AUTHORITY_SIGN_PUBLIC_KEY_PEM",
  "HOSTED_CRYPTO_GCP_KMS_API_ROOT",
  "HOSTED_CRYPTO_GCP_WEB_WRAP_KEY_NAME",
  "HOSTED_CRYPTO_LOCAL_AUTHORITY_SIGN_PRIVATE_JWK",
  "HOSTED_CRYPTO_LOCAL_KMS_WRAP_KEY",
  "HOSTED_DEVICE_ROUTING_INDEX_KEY",
  "HOSTED_LOG_FINGERPRINT_SECRET",
  "HOSTED_PRIVATE_MEDIA_CAPABILITY_SECRET",
  "HOSTED_PROVIDER_EGRESS_CREDENTIAL_SIGNING_SECRET",
  "HOSTED_WEB_CALLBACK_SIGNING_KEY_ID",
  "HOSTED_WEB_CALLBACK_SIGNING_PRIVATE_JWK",
  "HOSTED_WEB_CALLBACK_SIGNING_PUBLIC_KEYRING_JSON",
] as const;
