#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"
source scripts/repo-tools.config.sh

fail_on_issues=0
upstream_args=()
for arg in "$@"; do
  case "$arg" in
    --fail-on-issues)
      fail_on_issues=1
      ;;
    *)
      upstream_args+=("$arg")
      ;;
  esac
done

if [[ "${FAIL_ON_DOC_ISSUES:-0}" == "1" ]]; then
  fail_on_issues=1
fi

set +e
if [[ "${#upstream_args[@]}" -gt 0 ]]; then
  upstream_output="$(
    FAIL_ON_DOC_ISSUES=0 "$(cobuild_repo_tool_bin cobuild-doc-gardening)" "${upstream_args[@]}"
  )"
else
  upstream_output="$(
    FAIL_ON_DOC_ISSUES=0 "$(cobuild_repo_tool_bin cobuild-doc-gardening)"
  )"
fi
upstream_status=$?
set -e
if [[ "$upstream_status" -ne 0 ]]; then
  printf '%s\n' "$upstream_output"
  exit "$upstream_status"
fi

DOC_GARDENING_FAIL_ON_ISSUES="$fail_on_issues" node <<'NODE'
const fs = require("node:fs");

const reportPath = "agent-docs/generated/doc-gardening-report.md";
const inventoryPath = "agent-docs/generated/doc-inventory.md";
const excludePattern = process.env.COBUILD_DOC_GARDENING_EXCLUDE_PATTERN
  ?? "^agent-docs/exec-plans/completed/";
const exclude = new RegExp(excludePattern);
const failOnIssues = process.env.DOC_GARDENING_FAIL_ON_ISSUES === "1";

function isBulletPath(line) {
  const match = line.match(/^- `([^`]+)`$/u);
  return match ? match[1] : null;
}

function parseReport(text) {
  const unindexed = [];
  const broken = [];
  let section = "";

  for (const line of text.split("\n")) {
    if (line === "## Unindexed Tracked Artifacts") {
      section = "unindexed";
      continue;
    }
    if (line === "## Broken Index Targets") {
      section = "broken";
      continue;
    }

    const path = isBulletPath(line);
    if (!path || path === "None") continue;

    if (section === "unindexed") {
      if (!exclude.test(path)) unindexed.push(path);
    } else if (section === "broken") {
      broken.push(path);
    }
  }

  return { unindexed, broken };
}

function formatReport({ unindexed, broken }) {
  const lines = [
    "# Agent Doc Gardening Report",
    "",
    "Auto-generated by cobuild-doc-gardening.",
    "",
    "## Unindexed Tracked Artifacts",
  ];

  if (unindexed.length === 0) {
    lines.push("- None");
  } else {
    for (const path of unindexed) lines.push(`- \`${path}\``);
  }

  lines.push("", "## Broken Index Targets");
  if (broken.length === 0) {
    lines.push("- None");
  } else {
    for (const path of broken) lines.push(`- \`${path}\``);
  }

  lines.push("");
  return lines.join("\n");
}

function filterInventory() {
  if (!fs.existsSync(inventoryPath)) return;
  const next = fs
    .readFileSync(inventoryPath, "utf8")
    .split("\n")
    .filter((line) => {
      const path = isBulletPath(line);
      return path ? !exclude.test(path) : true;
    })
    .join("\n");
  fs.writeFileSync(inventoryPath, next);
}

const report = parseReport(fs.readFileSync(reportPath, "utf8"));
fs.writeFileSync(reportPath, formatReport(report));
filterInventory();

const issueCount = report.unindexed.length + report.broken.length;
console.log(`Doc gardening completed. Issues found: ${issueCount}`);

if (failOnIssues && issueCount > 0) {
  console.error("Doc gardening found issues and fail-on-issues is enabled.");
  process.exit(1);
}
NODE
