import { describe, expect, it } from "vitest";

import {
  filterDocGardeningInventory,
  formatDocGardeningReport,
  parseDocGardeningReport,
} from "./doc-gardening-report.mjs";

const upstreamReport = `# Agent Doc Gardening Report

Auto-generated by cobuild-doc-gardening.

## Unindexed Tracked Artifacts
- \`agent-docs/tracked.md\`
- \`agent-docs/private.local.md\`
- \`agent-docs/exec-plans/completed/history.md\`

## Broken Index Targets
- \`agent-docs/missing.md\`
`;

describe("doc gardening report filtering", () => {
  it("keeps tracked findings while excluding ignored and completed documents", () => {
    const report = parseDocGardeningReport(upstreamReport, {
      exclude: /^agent-docs\/exec-plans\/completed\//u,
      trackedPaths: new Set(["agent-docs/tracked.md"]),
    });

    expect(report).toEqual({
      unindexed: ["agent-docs/tracked.md"],
      broken: ["agent-docs/missing.md"],
    });
    expect(formatDocGardeningReport(report)).toContain(
      "- `agent-docs/tracked.md`",
    );
  });

  it("removes untracked and excluded paths from the generated inventory", () => {
    const inventory = [
      "# Inventory",
      "- `agent-docs/tracked.md`",
      "- `agent-docs/private.local.md`",
      "- `agent-docs/exec-plans/completed/history.md`",
      "",
    ].join("\n");

    expect(filterDocGardeningInventory(inventory, {
      exclude: /^agent-docs\/exec-plans\/completed\//u,
      trackedPaths: new Set(["agent-docs/tracked.md"]),
    })).toBe("# Inventory\n- `agent-docs/tracked.md`\n");
  });
});
