#!/usr/bin/env node

import { existsSync, lstatSync, rmSync } from "node:fs";
import path from "node:path";

import {
  ORCHESTRATOR_SCHEMA_VERSION,
  buildCommandHelperScript,
  buildCommandWrapper,
  buildProtocolMetadata,
  buildSharedPromptHeader,
  ensureRepoLocalOutputDir,
  formatBulletList,
  formatDirTimestamp,
  isExistingScaffoldDir,
  mkdirp,
  renderTemplate,
  repoRoot,
  slugify,
  toPosixRelative,
  toTitleCase,
  writeExecutable,
  writeResearchReviewGptSupportFiles,
  writeTextFile,
} from "./research-orchestrator/lib.mjs";

function usage(exitCode = 2) {
  console.error(`Usage:
  pnpm research:init "topic"
  pnpm research:init --topic "topic" [options]

Options:
  --topic <text>       Research topic. You can also pass this as the first positional argument.
  --family <slug>      Provisional family slug override for the charter scaffold.
  --slug <slug>        Provisional protocol slug override for the charter scaffold.
  --out-dir <dir>      Output directory inside this repo. Defaults to output-packages/research/<slug>-<timestamp>.
  --force              Replace an existing output directory.
  -h, --help           Show this help text.

Environment used by generated command wrappers:
  RESEARCH_MODEL         Defaults to gpt-5.4-pro
  RESEARCH_WAIT_TIMEOUT  Defaults to 200m
  RESEARCH_TIMEOUT       Defaults to 210m
`);
  process.exit(exitCode);
}

function parseArgs(argv) {
  let topic = "";
  let family = "";
  let slug = "";
  let outDir = "";
  let force = false;

  for (let index = 0; index < argv.length; index += 1) {
    const value = argv[index];

    switch (value) {
      case "--topic":
        topic = argv[index + 1] ?? "";
        index += 1;
        break;
      case "--family":
        family = argv[index + 1] ?? "";
        index += 1;
        break;
      case "--slug":
        slug = argv[index + 1] ?? "";
        index += 1;
        break;
      case "--out-dir":
        outDir = argv[index + 1] ?? "";
        index += 1;
        break;
      case "--force":
        force = true;
        break;
      case "-h":
      case "--help":
        usage(0);
        break;
      default:
        if (value.startsWith("--")) {
          throw new Error(`Unknown option: ${value}`);
        }
        if (!topic) {
          topic = value;
        } else {
          throw new Error(`Unexpected extra argument: ${value}`);
        }
    }
  }

  if (!topic.trim()) {
    throw new Error("Missing research topic.");
  }

  return {
    topic: topic.trim(),
    family: family.trim(),
    slug: slug.trim(),
    outDir: outDir.trim(),
    force,
  };
}

function resolveInitialSpecification({ topic, family, slug }) {
  const protocolSlug = slug || slugify(topic) || "research-topic";
  return {
    topic,
    protocolName: toTitleCase(topic),
    protocolSlug,
    familySlug: family || protocolSlug,
  };
}

function buildInitialIdentityHints(spec) {
  return formatBulletList([
    `User-supplied topic string: "${spec.topic}"`,
    `Provisional protocol name: ${spec.protocolName}`,
    `Provisional protocol slug: ${spec.protocolSlug}`,
    `Provisional family slug: ${spec.familySlug}`,
    "The charter may replace these provisional identity fields if a better canonical family or variant split emerges.",
  ]);
}

function buildWorkflowObject({ generatedAt, outDirRelative, spec }) {
  return {
    schemaVersion: ORCHESTRATOR_SCHEMA_VERSION,
    generatedAt,
    status: "charter_pending",
    outputDir: outDirRelative,
    topic: spec.topic,
    charterResponseFile: "responses/01-charter.md",
    protocol: {
      ...buildProtocolMetadata(spec.protocolName, spec.protocolSlug, spec.familySlug),
      provisional: true,
    },
    discoveryShards: [],
    sectionSeams: [],
    promptFiles: ["prompts/01-charter.md"],
    runnableCommands: ["commands/01-charter.sh"],
  };
}

function buildRunbook({ outDirRelative, spec }) {
  return `# Research Orchestrator Scaffold

This workspace was generated by \`pnpm research:init\`.
It scaffolds the charter-first review:gpt research flow for **${spec.protocolName}** without precommitting discovery seams.

## Current State

Only the charter stage is runnable right now. The later discovery shards, section seams, and template prompts are generated after the charter response exists.

## Provisional Identity

- Topic: ${spec.topic}
- Provisional protocol name: ${spec.protocolName}
- Provisional protocol slug: ${spec.protocolSlug}
- Provisional family slug: ${spec.familySlug}
- Output package: \`${outDirRelative}\`

These identity fields are only starting hints for the charter. The charter manifest is allowed to replace them before post-charter prompts are generated.

## Run Now

1. \`bash commands/01-charter.sh\`

That command writes:

- \`responses/01-charter.md\`
- \`logs/01-charter.result.json\`
- \`logs/01-charter.stderr.log\`
- \`state/chat-urls/01-charter.txt\` when a ChatGPT thread URL is detected
- \`state/thread-exports/01-charter.thread.json\` when thread export succeeds

## After The Charter Finishes

1. Confirm the full charter response is saved at \`responses/01-charter.md\`.
2. Run \`pnpm research:materialize --workspace ${outDirRelative}\`.
3. Review the generated discovery commands and later template prompts before launching the next tranche.

## Environment Knobs

- \`RESEARCH_MODEL\`: defaults to \`gpt-5.4-pro\`
- \`RESEARCH_WAIT_TIMEOUT\`: defaults to \`200m\`
- \`RESEARCH_TIMEOUT\`: defaults to \`210m\`

## Notes

- The generated command wrapper discovers the repo root dynamically at runtime and does not hardcode absolute local paths.
- The legacy \`pnpm research\` runner remains unchanged. This scaffold is a new charter-first orchestrator path alongside it.
- \`pnpm research:materialize\` replaces generated post-charter prompts and commands inside this workspace when the charter output changes.
`;
}

function main(argv) {
  const args = parseArgs(argv);
  const spec = resolveInitialSpecification(args);
  const now = new Date();
  const timestamp = formatDirTimestamp(now);
  const outDir = path.resolve(
    repoRoot,
    args.outDir || path.join("output-packages", "research", `${spec.protocolSlug}-${timestamp}`),
  );

  ensureRepoLocalOutputDir(outDir);

  if (existsSync(outDir)) {
    const stat = lstatSync(outDir);
    if (!stat.isDirectory()) {
      throw new Error(`Output target is not a directory: ${toPosixRelative(outDir)}`);
    }
    if (!args.force) {
      throw new Error(`Output directory already exists: ${toPosixRelative(outDir)}`);
    }
    if (!isExistingScaffoldDir(outDir)) {
      throw new Error(
        `Refusing --force for a non-scaffold directory: ${toPosixRelative(outDir)}`,
      );
    }
    rmSync(outDir, { recursive: true, force: true });
  }

  const dirs = [
    outDir,
    path.join(outDir, "prompts"),
    path.join(outDir, "commands"),
    path.join(outDir, "responses"),
    path.join(outDir, "logs"),
    path.join(outDir, "downloads"),
    path.join(outDir, "state"),
    path.join(outDir, "state", "chat-urls"),
    path.join(outDir, "state", "thread-exports"),
  ];

  for (const dir of dirs) {
    mkdirp(dir);
  }

  const sharedHeader = buildSharedPromptHeader(spec);
  const charterPromptPath = path.join(outDir, "prompts", "01-charter.md");
  writeTextFile(
    charterPromptPath,
    renderTemplate("charter.md", {
      SHARED_HEADER: sharedHeader,
      INITIAL_IDENTITY_HINTS: buildInitialIdentityHints(spec),
      PROTOCOL_NAME: spec.protocolName,
      PROTOCOL_SLUG: spec.protocolSlug,
      FAMILY_SLUG: spec.familySlug,
    }),
  );

  writeExecutable(
    path.join(outDir, "commands", "_run-review-gpt.sh"),
    buildCommandHelperScript(),
  );
  writeResearchReviewGptSupportFiles(outDir);
  writeExecutable(
    path.join(outDir, "commands", "01-charter.sh"),
    buildCommandWrapper("01-charter", "prompts/01-charter.md"),
  );

  const outDirRelative = toPosixRelative(outDir);
  writeTextFile(
    path.join(outDir, "workflow.json"),
    JSON.stringify(
      buildWorkflowObject({
        generatedAt: now.toISOString(),
        outDirRelative,
        spec,
      }),
      null,
      2,
    ) + "\n",
  );
  writeTextFile(path.join(outDir, "README.md"), buildRunbook({ outDirRelative, spec }));

  console.log(`Initialized research orchestrator scaffold at ${outDirRelative}`);
  console.log(`Run next: bash ${path.posix.join(outDirRelative, "commands/01-charter.sh")}`);
  console.log(`Then materialize later seams with: pnpm research:materialize --workspace ${outDirRelative}`);
}

try {
  main(process.argv.slice(2));
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  console.error(message);
  process.exitCode = 1;
}
