import type { MetricDefinition } from "../types.ts";

export const ACTIVITY_METRICS = [
  {
    aliases: [
      "daily-step-count",
      "daily_step_count",
      "daily-steps",
      "daily_steps",
      "step-count",
      "step_count",
      "step-count-per-day",
      "step_count_per_day",
      "steps",
      "steps-per-day",
      "steps_per_day",
    ],
    biomarkerKey: null,
    canonicalUnit: "count",
    category: "activity",
    displayName: "Steps",
    displayUnit: "steps",
    key: "steps",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: [
      "activity-counts",
      "activity_counts",
      "accelerometer-counts",
      "accelerometer_counts",
      "actigraphy-counts",
      "actigraphy_counts",
      "activity-counts-per-day",
      "activity_counts_per_day",
    ],
    biomarkerKey: null,
    canonicalUnit: "counts/day",
    category: "activity",
    displayName: "Activity counts",
    displayUnit: "counts/day",
    key: "activity-counts",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["activeCalories", "active-calories", "active_calories", "calories-active", "calories_active"],
    biomarkerKey: null,
    canonicalUnit: "kcal",
    category: "activity",
    displayName: "Active calories",
    displayUnit: "kcal",
    key: "active-calories",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["calories-basal"],
    biomarkerKey: null,
    canonicalUnit: "kcal",
    category: "activity",
    displayName: "Basal calories",
    displayUnit: "kcal",
    key: "basal-calories",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["daylight-exposure"],
    biomarkerKey: null,
    canonicalUnit: "minutes",
    category: "activity",
    displayName: "Daylight exposure",
    displayUnit: "minutes",
    key: "daylight-exposure-minutes",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["active-minutes", "active_minutes", "activeMinutes", "activity-minutes"],
    biomarkerKey: null,
    canonicalUnit: "minutes",
    category: "activity",
    displayName: "Activity minutes",
    displayUnit: "minutes",
    key: "activity-minutes",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["session-minutes", "workout-duration"],
    biomarkerKey: null,
    canonicalUnit: "minutes",
    category: "activity",
    displayName: "Workout minutes",
    displayUnit: "minutes",
    key: "workout-minutes",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["session-count", "session_count", "sessionCount", "workout-count", "workout_count", "workouts"],
    biomarkerKey: null,
    canonicalUnit: "count",
    category: "activity",
    displayName: "Workout count",
    displayUnit: "workouts",
    key: "workout-count",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["activityScore", "activity_score", "activity-score", "movement-score"],
    biomarkerKey: null,
    canonicalUnit: "score",
    category: "activity",
    displayName: "Activity score",
    displayUnit: "score",
    key: "activity-score",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["dayStrain", "day_strain", "day-strain", "strain"],
    biomarkerKey: null,
    canonicalUnit: "strain",
    category: "activity",
    displayName: "Day strain",
    displayUnit: "strain",
    key: "day-strain",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 1,
  },
  {
    aliases: ["distance", "distanceKm", "distance_km", "daily-distance", "daily_distance"],
    biomarkerKey: null,
    canonicalUnit: "km",
    category: "activity",
    displayName: "Distance",
    displayUnit: "km",
    key: "distance-km",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 2,
  },
  {
    aliases: ["elevation-gain", "elevation_gain", "totalElevationGainMeters", "total_elevation_gain_meters"],
    biomarkerKey: null,
    canonicalUnit: "meter",
    category: "activity",
    displayName: "Elevation gain",
    displayUnit: "m",
    key: "elevation-gain-meters",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["floors", "floorsClimbed", "floors_climbed", "floors-climbed"],
    biomarkerKey: null,
    canonicalUnit: "count",
    category: "activity",
    displayName: "Floors climbed",
    displayUnit: "floors",
    key: "floors-climbed",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["handwashing"],
    biomarkerKey: null,
    canonicalUnit: "count",
    category: "activity",
    displayName: "Handwashing",
    displayUnit: "count",
    key: "handwashing-count",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["stand-duration"],
    biomarkerKey: null,
    canonicalUnit: "minutes",
    category: "activity",
    displayName: "Stand duration",
    displayUnit: "minutes",
    key: "stand-duration-minutes",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["stand-hour"],
    biomarkerKey: null,
    canonicalUnit: "count",
    category: "activity",
    displayName: "Stand hours",
    displayUnit: "hours",
    key: "stand-hours",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["uv-exposure"],
    biomarkerKey: null,
    canonicalUnit: "index",
    category: "activity",
    displayName: "UV exposure",
    displayUnit: "index",
    key: "uv-exposure-index",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 1,
  },
  {
    aliases: ["wheelchair-push"],
    biomarkerKey: null,
    canonicalUnit: "count",
    category: "activity",
    displayName: "Wheelchair pushes",
    displayUnit: "pushes",
    key: "wheelchair-push-count",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["workout-distance"],
    biomarkerKey: null,
    canonicalUnit: "km",
    category: "activity",
    displayName: "Workout distance",
    displayUnit: "km",
    key: "workout-distance-km",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 2,
  },
  {
    aliases: ["workout-swimming-stroke"],
    biomarkerKey: null,
    canonicalUnit: "count",
    category: "activity",
    displayName: "Swimming strokes",
    displayUnit: "strokes",
    key: "swimming-stroke-count",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["maxHeartRate", "max_heart_rate", "max-heart-rate", "max-hr", "max_hr"],
    biomarkerKey: null,
    canonicalUnit: "bpm",
    category: "fitness",
    displayName: "Daily max heart rate",
    displayUnit: "bpm",
    key: "max-heart-rate",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["mvpa", "moderate-vigorous-minutes", "moderate_vigorous_minutes", "moderate-to-vigorous-minutes"],
    biomarkerKey: null,
    canonicalUnit: "minutes",
    category: "activity",
    displayName: "MVPA",
    displayUnit: "minutes",
    key: "mvpa-minutes",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: [
      "cadence-peak-30m",
      "peak-30-minute-cadence",
      "peak-30min-cadence",
      "peak_30_minute_cadence",
      "peak_cadence",
      "peakCadence",
      "steps-per-minute-peak-30m",
    ],
    biomarkerKey: null,
    canonicalUnit: "steps/min",
    category: "activity",
    displayName: "Peak 30-minute cadence",
    displayUnit: "steps/min",
    key: "peak-30-minute-cadence",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 1,
  },
  {
    aliases: ["sedentary", "sedentary-time", "sedentary_time", "sedentary-minutes"],
    biomarkerKey: null,
    canonicalUnit: "minutes",
    category: "activity",
    displayName: "Sedentary time",
    displayUnit: "minutes",
    key: "sedentary-minutes",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["cardio-fitness", "estimated-vo2max", "estimated_vo2max", "estimated_vo2_max", "vo2-max", "vo2_max", "vo2max"],
    biomarkerKey: "biomarker:estimated-vo2max",
    canonicalUnit: "mL/kg/min",
    category: "fitness",
    displayName: "Estimated VO2 max",
    displayUnit: "mL/kg/min",
    key: "estimated-vo2-max",
    selectionPolicy: { kind: "latest-device-estimate", staleAfterDays: 45 },
    trendPolicy: { aggregation: "median", comparisonWindowDays: 90, latestWindowDays: 14, minimumPoints: 2 },
    valuePrecision: 1,
  },
  {
    aliases: ["workoutStrain", "workout_strain", "workout-strain"],
    biomarkerKey: null,
    canonicalUnit: "strain",
    category: "activity",
    displayName: "Workout strain",
    displayUnit: "strain",
    key: "workout-strain",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 1,
  },
  {
    aliases: ["valid-days-28d", "wearable_valid_day_count_28d", "wearable-valid-days-28d"],
    biomarkerKey: null,
    canonicalUnit: "count",
    category: "activity",
    displayName: "Wearable valid days",
    displayUnit: "days",
    key: "wearable-valid-day-count-28d",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["coverage-index", "wearable_coverage_index", "wearable_coverage_index_28d", "wearable-coverage"],
    biomarkerKey: null,
    canonicalUnit: "score",
    category: "custom",
    displayName: "Wearable coverage",
    displayUnit: "score",
    key: "wearable-coverage-index",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 2,
  },
] satisfies readonly MetricDefinition[];
