import type { MetricDefinition } from "../types.ts";

export const ACTIVITY_METRICS = [
  {
    aliases: [
      "daily-step-count",
      "daily_step_count",
      "daily-steps",
      "daily_steps",
      "step-count",
      "step_count",
      "step-count-per-day",
      "step_count_per_day",
      "steps",
      "steps-per-day",
      "steps_per_day",
    ],
    biomarkerKey: null,
    canonicalUnit: "count",
    category: "activity",
    displayName: "Steps",
    displayUnit: "steps",
    key: "steps",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["active-minutes", "active_minutes", "activeMinutes", "sessionMinutes", "session_minutes", "activity-minutes"],
    biomarkerKey: null,
    canonicalUnit: "minutes",
    category: "activity",
    displayName: "Activity minutes",
    displayUnit: "minutes",
    key: "activity-minutes",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["mvpa", "moderate-vigorous-minutes", "moderate_vigorous_minutes", "moderate-to-vigorous-minutes"],
    biomarkerKey: null,
    canonicalUnit: "minutes",
    category: "activity",
    displayName: "MVPA",
    displayUnit: "minutes",
    key: "mvpa-minutes",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: [
      "cadence-peak-30m",
      "peak-30-minute-cadence",
      "peak-30min-cadence",
      "peak_30_minute_cadence",
      "peak_cadence",
      "peakCadence",
      "steps-per-minute-peak-30m",
    ],
    biomarkerKey: null,
    canonicalUnit: "steps/min",
    category: "activity",
    displayName: "Peak 30-minute cadence",
    displayUnit: "steps/min",
    key: "peak-30-minute-cadence",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 1,
  },
  {
    aliases: ["sedentary", "sedentary-time", "sedentary_time", "sedentary-minutes"],
    biomarkerKey: null,
    canonicalUnit: "minutes",
    category: "activity",
    displayName: "Sedentary time",
    displayUnit: "minutes",
    key: "sedentary-minutes",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["cardio-fitness", "estimated-vo2max", "estimated_vo2max", "estimated_vo2_max", "vo2-max", "vo2_max", "vo2max"],
    biomarkerKey: "biomarker:estimated-vo2max",
    canonicalUnit: "mL/kg/min",
    category: "fitness",
    displayName: "Estimated VO2 max",
    displayUnit: "mL/kg/min",
    key: "estimated-vo2-max",
    selectionPolicy: { kind: "latest-device-estimate", staleAfterDays: 45 },
    trendPolicy: { aggregation: "median", comparisonWindowDays: 90, latestWindowDays: 14, minimumPoints: 2 },
    valuePrecision: 1,
  },
  {
    aliases: ["valid-days-28d", "wearable_valid_day_count_28d", "wearable-valid-days-28d"],
    biomarkerKey: null,
    canonicalUnit: "count",
    category: "activity",
    displayName: "Wearable valid days",
    displayUnit: "days",
    key: "wearable-valid-day-count-28d",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["coverage-index", "wearable_coverage_index", "wearable_coverage_index_28d", "wearable-coverage"],
    biomarkerKey: null,
    canonicalUnit: "score",
    category: "custom",
    displayName: "Wearable coverage",
    displayUnit: "score",
    key: "wearable-coverage-index",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 2,
  },
] satisfies readonly MetricDefinition[];
