import type { MetricDefinition } from "../types.ts";

export const BODY_METRICS = [
  {
    aliases: ["bmi", "body-mass-index", "body_mass_index"],
    biomarkerKey: null,
    canonicalUnit: "kg/m^2",
    category: "body",
    displayName: "BMI",
    displayUnit: "kg/m^2",
    key: "bmi",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 45 },
    valuePrecision: 1,
  },
  {
    aliases: [
      "waist",
      "waist_circumference",
      "waist_circumference_centimeter",
      "waist-circumference-cm",
    ],
    biomarkerKey: null,
    canonicalUnit: "cm",
    category: "body",
    displayName: "Waist circumference",
    displayUnit: "cm",
    key: "waist-circumference",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 45 },
    valuePrecision: 1,
  },
  {
    aliases: ["weight", "body_weight", "bodyWeight", "bodyweight", "weightKg"],
    biomarkerKey: null,
    canonicalUnit: "kg",
    category: "body",
    displayName: "Body weight",
    displayUnit: "kg",
    key: "body-weight",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 45 },
    valuePrecision: 1,
  },
  {
    aliases: ["body_fat", "bodyFat", "body_fat_pct", "body-fat-pct", "bodyFatPercentage", "body_fat_percentage"],
    biomarkerKey: null,
    canonicalUnit: "percent",
    category: "body",
    displayName: "Body fat",
    displayUnit: "percent",
    key: "body-fat-percentage",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 45 },
    valuePrecision: 1,
  },
  {
    aliases: [
      "leanBodyMassKg",
      "lean_body_mass",
      "lean_body_mass_kg",
      "lean_body_mass_kilogram",
      "lean_mass",
      "lean_mass_kg",
    ],
    biomarkerKey: null,
    canonicalUnit: "kg",
    category: "body",
    displayName: "Lean body mass",
    displayUnit: "kg",
    key: "lean-body-mass",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 45 },
    valuePrecision: 1,
  },
] satisfies readonly MetricDefinition[];
