import type { MetricDefinition } from "../types.ts";

export const BODY_METRICS = [
  {
    aliases: ["bmi", "body-mass-index", "body_mass_index"],
    biomarkerKey: null,
    canonicalUnit: "kg/m^2",
    category: "body",
    displayName: "BMI",
    displayUnit: "kg/m^2",
    key: "bmi",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 45 },
    valuePrecision: 1,
  },
  {
    aliases: [
      "waist",
      "waist_circumference",
      "waist_circumference_centimeter",
      "waist-circumference-cm",
    ],
    biomarkerKey: null,
    canonicalUnit: "cm",
    category: "body",
    displayName: "Waist circumference",
    displayUnit: "cm",
    key: "waist-circumference",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 45 },
    valuePrecision: 1,
  },
  {
    aliases: ["weight", "body_weight", "bodyWeight", "bodyweight", "weightKg"],
    biomarkerKey: null,
    canonicalUnit: "kg",
    category: "body",
    displayName: "Body weight",
    displayUnit: "kg",
    key: "body-weight",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 45 },
    valuePrecision: 1,
  },
  {
    aliases: ["fat", "body_fat", "bodyFat", "body_fat_pct", "body-fat-pct", "bodyFatPercentage", "body_fat_percentage"],
    biomarkerKey: null,
    canonicalUnit: "percent",
    category: "body",
    displayName: "Body fat",
    displayUnit: "percent",
    key: "body-fat-percentage",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 45 },
    valuePrecision: 1,
  },
  {
    aliases: ["boneMassPercentage", "bone_mass_percentage"],
    biomarkerKey: null,
    canonicalUnit: "percent",
    category: "body",
    displayName: "Bone mass percentage",
    displayUnit: "percent",
    key: "bone-mass-percentage",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 45 },
    valuePrecision: 1,
  },
  {
    aliases: ["muscleMassPercentage", "muscle_mass_percentage"],
    biomarkerKey: null,
    canonicalUnit: "percent",
    category: "body",
    displayName: "Muscle mass percentage",
    displayUnit: "percent",
    key: "muscle-mass-percentage",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 45 },
    valuePrecision: 1,
  },
  {
    aliases: ["bodyWaterPercentage", "body_water_percentage", "waterPercentage", "water_percentage"],
    biomarkerKey: null,
    canonicalUnit: "percent",
    category: "body",
    displayName: "Body water",
    displayUnit: "percent",
    key: "body-water-percentage",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 45 },
    valuePrecision: 1,
  },
  {
    aliases: ["visceralFatIndex", "visceral_fat_index"],
    biomarkerKey: null,
    canonicalUnit: "index",
    category: "body",
    displayName: "Visceral fat index",
    displayUnit: "index",
    key: "visceral-fat-index",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 45 },
    valuePrecision: 1,
  },
  {
    aliases: [
      "leanBodyMassKg",
      "lean_body_mass",
      "lean_body_mass_kg",
      "lean_body_mass_kilogram",
      "lean_mass",
      "lean_mass_kg",
    ],
    biomarkerKey: null,
    canonicalUnit: "kg",
    category: "body",
    displayName: "Lean body mass",
    displayUnit: "kg",
    key: "lean-body-mass",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 45 },
    valuePrecision: 1,
  },
] satisfies readonly MetricDefinition[];
