import type { MetricDefinition } from "../types.ts";

export const FUNCTION_METRICS = [
  {
    aliases: [
      "adl-count",
      "adl-limitation-count",
      "activities-of-daily-living-limitations",
      "daily-living-limitation-count",
    ],
    biomarkerKey: null,
    canonicalUnit: "count",
    category: "function",
    displayName: "ADL limitation count",
    displayUnit: "limitations",
    key: "adl-limitation-count",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: [
      "iadl-count",
      "iadl-limitation-count",
      "instrumental-adl-limitation-count",
      "instrumental-activities-of-daily-living-limitations",
    ],
    biomarkerKey: null,
    canonicalUnit: "count",
    category: "function",
    displayName: "IADL limitation count",
    displayUnit: "limitations",
    key: "iadl-limitation-count",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: [
      "disability-count",
      "functional-limitation-count",
      "mobility-count",
      "mobility-limitation-count",
      "physical-function-limitation-count",
    ],
    biomarkerKey: null,
    canonicalUnit: "count",
    category: "function",
    displayName: "Mobility limitation count",
    displayUnit: "limitations",
    key: "mobility-limitation-count",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: [
      "frailty-count",
      "frailty-symptom-count",
      "frailty_symptom_count",
    ],
    biomarkerKey: null,
    canonicalUnit: "count",
    category: "function",
    displayName: "Frailty symptom count",
    displayUnit: "symptoms",
    key: "frailty-symptom-count",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 365 },
    valuePrecision: 0,
  },
] satisfies readonly MetricDefinition[];
