import type { MetricDefinition } from "../types.ts";

export const LAB_METRICS = [
  {
    aliases: ["serum-albumin", "serum_albumin"],
    biomarkerKey: "biomarker:albumin",
    canonicalUnit: "g/dL",
    category: "lab",
    displayName: "Albumin",
    displayUnit: "g/dL",
    key: "albumin",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["serum-creatinine", "serum_creatinine"],
    biomarkerKey: "biomarker:creatinine",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "Creatinine",
    displayUnit: "mg/dL",
    key: "creatinine",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 2,
  },
  {
    aliases: ["bun", "serum-urea-nitrogen", "urea-nitrogen"],
    biomarkerKey: "biomarker:blood-urea-nitrogen",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "Blood urea nitrogen",
    displayUnit: "mg/dL",
    key: "blood-urea-nitrogen",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: [
      "estimated-glomerular-filtration-rate",
      "estimated_glomerular_filtration_rate",
      "glomerular-filtration-rate",
      "glomerular_filtration_rate",
      "egfr",
      "e-gfr",
      "estimated-gfr",
      "estimated-gfr-ckd-epi",
    ],
    biomarkerKey: "biomarker:egfr",
    canonicalUnit: "mL/min/1.73m^2",
    category: "lab",
    displayName: "eGFR",
    displayUnit: "mL/min/1.73m^2",
    key: "egfr",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["blood-glucose", "blood_glucose", "fasting-glucose", "fasting_glucose"],
    biomarkerKey: "biomarker:blood-glucose",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "Glucose",
    displayUnit: "mg/dL",
    key: "glucose",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, preferFasting: true, staleAfterDays: 90 },
    valuePrecision: 0,
  },
  {
    aliases: ["apo-b", "apo_b", "apolipoprotein-b", "apolipoprotein_b", "apolipoprotein b"],
    biomarkerAliases: ["biomarker:apolipoprotein-b"],
    biomarkerKey: "biomarker:apob",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "ApoB",
    displayUnit: "mg/dL",
    key: "apob",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: [
      "cholesterol-ldl",
      "ldl",
      "ldl-calculated",
      "ldl-chol-calc-nih",
      "ldl_cholesterol",
      "ldl-cholesterol",
      "ldlc",
      "ldl_c",
    ],
    biomarkerKey: "biomarker:ldl-c",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "LDL-C",
    displayUnit: "mg/dL",
    key: "ldl-c",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["cholesterol-hdl", "hdl", "hdl_cholesterol", "hdl-cholesterol", "hdlc", "hdl_c"],
    biomarkerKey: "biomarker:hdl-c",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "HDL-C",
    displayUnit: "mg/dL",
    key: "hdl-c",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["tg", "triglyceride"],
    biomarkerKey: "biomarker:triglycerides",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "Triglycerides",
    displayUnit: "mg/dL",
    key: "triglycerides",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: [
      "a1c",
      "hb-a1c",
      "hb-a1c-ngsp",
      "hb-a1c-si",
      "hba1c",
      "hba1c-ngsp",
      "hba1c-si",
      "hemoglobin-a-1c",
      "hemoglobin-a1c",
      "hemoglobin_a1c",
    ],
    biomarkerKey: "biomarker:hba1c",
    canonicalUnit: "percent",
    category: "lab",
    displayName: "HbA1c",
    displayUnit: "percent",
    key: "hba1c",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: [
      "alanine-aminotransferase",
      "alanine-transaminase",
      "alanine_aminotransferase",
      "alt-sgpt",
      "sgpt",
    ],
    biomarkerKey: "biomarker:alt",
    canonicalUnit: "U/L",
    category: "lab",
    displayName: "ALT",
    displayUnit: "U/L",
    key: "alt",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: [
      "aspartate-aminotransferase",
      "aspartate-transaminase",
      "aspartate_aminotransferase",
      "ast-sgot",
      "sgot",
    ],
    biomarkerKey: "biomarker:ast",
    canonicalUnit: "U/L",
    category: "lab",
    displayName: "AST",
    displayUnit: "U/L",
    key: "ast",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["gamma-glutamyl-transferase", "gamma_glutamyl_transferase"],
    biomarkerKey: "biomarker:ggt",
    canonicalUnit: "U/L",
    category: "lab",
    displayName: "GGT",
    displayUnit: "U/L",
    key: "ggt",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["alk-phos", "alkaline-phos", "alkaline_phosphatase", "alp"],
    biomarkerKey: "biomarker:alkaline-phosphatase",
    canonicalUnit: "U/L",
    category: "lab",
    displayName: "Alkaline phosphatase",
    displayUnit: "U/L",
    key: "alkaline-phosphatase",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["crp", "hscrp", "hs_crp", "high-sensitivity-crp", "high_sensitivity_crp", "c-reactive-protein"],
    biomarkerKey: "biomarker:hs-crp",
    canonicalUnit: "mg/L",
    category: "lab",
    displayName: "hs-CRP",
    displayUnit: "mg/L",
    key: "hs-crp",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: [
      "leukocytes",
      "white-blood-cell",
      "white-blood-cell-count-wbc",
      "white-blood-cells",
      "white_blood_cells",
      "wbc",
      "wbc-count",
    ],
    biomarkerKey: "biomarker:white-blood-cell-count",
    canonicalUnit: "10^3/uL",
    category: "lab",
    displayName: "White blood cells",
    displayUnit: "10^3/uL",
    key: "white-blood-cell-count",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: [
      "lymphocyte",
      "lymphocyte-percent",
      "lymphocyte-pct",
      "lymphocyte_pct",
      "lymphocyte-percentage",
      "lymphocytes-percent",
      "lymphocytes-pct",
      "lymphocytes",
    ],
    biomarkerKey: "biomarker:lymphocyte-percentage",
    canonicalUnit: "percent",
    category: "lab",
    displayName: "Lymphocytes",
    displayUnit: "%",
    key: "lymphocyte-percentage",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["mch", "mean-cell-haemoglobin", "mean-corpuscular-haemoglobin"],
    biomarkerKey: "biomarker:mean-corpuscular-hemoglobin",
    canonicalUnit: "pg",
    category: "lab",
    displayName: "Mean corpuscular hemoglobin",
    displayUnit: "pg",
    key: "mean-corpuscular-hemoglobin",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: [
      "mchc",
      "mean-corpuscular-hb-concentration",
      "mean-corpuscular-haemoglobin-concentration",
    ],
    biomarkerKey: "biomarker:mean-corpuscular-hemoglobin-concentration",
    canonicalUnit: "g/dL",
    category: "lab",
    displayName: "Mean corpuscular hemoglobin concentration",
    displayUnit: "g/dL",
    key: "mean-corpuscular-hemoglobin-concentration",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["mcv", "mean-cell-volume", "mean-corpuscular-volume"],
    biomarkerKey: "biomarker:mean-corpuscular-volume",
    canonicalUnit: "fL",
    category: "lab",
    displayName: "Mean corpuscular volume",
    displayUnit: "fL",
    key: "mean-corpuscular-volume",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["rdw", "rdw-cv", "red-cell-distribution-width", "red-cell-distribution-width-rdw", "red_cell_distribution_width"],
    biomarkerKey: "biomarker:red-cell-distribution-width",
    canonicalUnit: "percent",
    category: "lab",
    displayName: "Red cell distribution width",
    displayUnit: "%",
    key: "red-cell-distribution-width",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: [],
    biomarkerKey: "biomarker:ferritin",
    canonicalUnit: "ng/mL",
    category: "lab",
    displayName: "Ferritin",
    displayUnit: "ng/mL",
    key: "ferritin",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["thyrotropin", "tsh"],
    biomarkerKey: "biomarker:thyroid-stimulating-hormone",
    canonicalUnit: "mIU/L",
    category: "lab",
    displayName: "Thyroid-stimulating hormone",
    displayUnit: "mIU/L",
    key: "thyroid-stimulating-hormone",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 2,
  },
  {
    aliases: ["cholesterol-total", "total-cholesterol"],
    biomarkerKey: "biomarker:total-cholesterol",
    canonicalUnit: null,
    category: "lab",
    displayName: "Total cholesterol",
    displayUnit: null,
    key: "total-cholesterol",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["cholesterol-non-hdl", "non-hdl-c"],
    biomarkerKey: "biomarker:non-hdl-cholesterol",
    canonicalUnit: null,
    category: "lab",
    displayName: "Non-HDL cholesterol",
    displayUnit: null,
    key: "non-hdl-cholesterol",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["cholesterol-hdl-ratio"],
    biomarkerKey: "biomarker:cholesterol-hdl-ratio",
    canonicalUnit: null,
    category: "lab",
    displayName: "Cholesterol/HDL ratio",
    displayUnit: null,
    key: "cholesterol-hdl-ratio",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["vldl-cholesterol-cal", "vldl-cholesterol-calculated"],
    biomarkerKey: "biomarker:vldl-cholesterol",
    canonicalUnit: null,
    category: "lab",
    displayName: "VLDL cholesterol",
    displayUnit: null,
    key: "vldl-cholesterol",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["globulin", "globulin-total"],
    biomarkerKey: "biomarker:total-globulin",
    canonicalUnit: null,
    category: "lab",
    displayName: "Globulin",
    displayUnit: null,
    key: "total-globulin",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["bilirubin", "bilirubin-total"],
    biomarkerKey: "biomarker:total-bilirubin",
    canonicalUnit: null,
    category: "lab",
    displayName: "Total bilirubin",
    displayUnit: null,
    key: "total-bilirubin",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["fibrosis-score-fib4", "fibrosis-score-fib-4"],
    biomarkerKey: "biomarker:fib4",
    canonicalUnit: null,
    category: "lab",
    displayName: "FIB-4",
    displayUnit: null,
    key: "fib4",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 2,
  },
  {
    aliases: ["rbc", "red-blood-cell", "red-blood-cells"],
    biomarkerKey: "biomarker:red-blood-cell-count",
    canonicalUnit: null,
    category: "lab",
    displayName: "Red blood cells",
    displayUnit: null,
    key: "red-blood-cell-count",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 2,
  },
  {
    aliases: ["haemoglobin"],
    biomarkerKey: "biomarker:hemoglobin",
    canonicalUnit: null,
    category: "lab",
    displayName: "Hemoglobin",
    displayUnit: null,
    key: "hemoglobin",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["packed-cell-volume"],
    biomarkerKey: "biomarker:hematocrit",
    canonicalUnit: null,
    category: "lab",
    displayName: "Hematocrit",
    displayUnit: null,
    key: "hematocrit",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["platelet", "platelets"],
    biomarkerKey: "biomarker:platelet-count",
    canonicalUnit: null,
    category: "lab",
    displayName: "Platelets",
    displayUnit: null,
    key: "platelet-count",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["neutrophils", "neutrophils-percent", "neutrophils-relative"],
    biomarkerKey: "biomarker:neutrophil-percentage",
    canonicalUnit: null,
    category: "lab",
    displayName: "Neutrophils",
    displayUnit: null,
    key: "neutrophil-percentage",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["absolute-neutrophil-count", "anc", "neutrophils-absolute"],
    biomarkerKey: "biomarker:absolute-neutrophils",
    canonicalUnit: null,
    category: "lab",
    displayName: "Neutrophils, absolute",
    displayUnit: null,
    key: "absolute-neutrophils",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 2,
  },
  {
    aliases: ["absolute-lymphocytes", "lymphocytes-absolute"],
    biomarkerKey: "biomarker:absolute-lymphocytes",
    canonicalUnit: null,
    category: "lab",
    displayName: "Lymphocytes, absolute",
    displayUnit: null,
    key: "absolute-lymphocytes",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 2,
  },
  {
    aliases: ["monocytes", "monocytes-percent", "monocytes-relative"],
    biomarkerKey: "biomarker:monocyte-percentage",
    canonicalUnit: null,
    category: "lab",
    displayName: "Monocytes",
    displayUnit: null,
    key: "monocyte-percentage",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["monocytes-absolute"],
    biomarkerKey: "biomarker:absolute-monocytes",
    canonicalUnit: null,
    category: "lab",
    displayName: "Monocytes, absolute",
    displayUnit: null,
    key: "absolute-monocytes",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 2,
  },
  {
    aliases: ["eosinophils", "eosinophils-percent", "eosinophils-relative"],
    biomarkerKey: "biomarker:eosinophil-percentage",
    canonicalUnit: null,
    category: "lab",
    displayName: "Eosinophils",
    displayUnit: null,
    key: "eosinophil-percentage",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["eosinophils-absolute"],
    biomarkerKey: "biomarker:absolute-eosinophils",
    canonicalUnit: null,
    category: "lab",
    displayName: "Eosinophils, absolute",
    displayUnit: null,
    key: "absolute-eosinophils",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 2,
  },
  {
    aliases: ["basophils", "basophils-percent", "basophils-relative"],
    biomarkerKey: "biomarker:basophil-percentage",
    canonicalUnit: null,
    category: "lab",
    displayName: "Basophils",
    displayUnit: null,
    key: "basophil-percentage",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["basophils-absolute"],
    biomarkerKey: "biomarker:absolute-basophils",
    canonicalUnit: null,
    category: "lab",
    displayName: "Basophils, absolute",
    displayUnit: null,
    key: "absolute-basophils",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 2,
  },
  {
    aliases: ["immature-granulocytes"],
    biomarkerKey: "biomarker:immature-granulocyte-percentage",
    canonicalUnit: null,
    category: "lab",
    displayName: "Immature granulocytes",
    displayUnit: null,
    key: "immature-granulocyte-percentage",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["immature-grans-abs", "immature-granulocytes-absolute"],
    biomarkerKey: "biomarker:absolute-immature-granulocytes",
    canonicalUnit: null,
    category: "lab",
    displayName: "Immature granulocytes, absolute",
    displayUnit: null,
    key: "absolute-immature-granulocytes",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 2,
  },
  {
    aliases: ["vit-d-25-hydroxy", "vitamin-d-25-hydroxy", "25-hydroxy-vitamin-d"],
    biomarkerKey: "biomarker:vitamin-d",
    canonicalUnit: null,
    category: "lab",
    displayName: "Vitamin D",
    displayUnit: null,
    key: "vitamin-d",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["testosterone", "testosterone-total"],
    biomarkerKey: "biomarker:total-testosterone",
    canonicalUnit: null,
    category: "lab",
    displayName: "Total testosterone",
    displayUnit: null,
    key: "total-testosterone",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["testosterone-free"],
    biomarkerKey: "biomarker:free-testosterone",
    canonicalUnit: null,
    category: "lab",
    displayName: "Free testosterone",
    displayUnit: null,
    key: "free-testosterone",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["estradiol-e2"],
    biomarkerKey: "biomarker:estradiol",
    canonicalUnit: null,
    category: "lab",
    displayName: "Estradiol",
    displayUnit: null,
    key: "estradiol",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["iron-total", "serum-iron"],
    biomarkerKey: "biomarker:iron",
    canonicalUnit: null,
    category: "lab",
    displayName: "Iron",
    displayUnit: null,
    key: "iron",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["iron-saturation", "transferrin-saturation"],
    biomarkerKey: "biomarker:iron-saturation",
    canonicalUnit: null,
    category: "lab",
    displayName: "Iron saturation",
    displayUnit: null,
    key: "iron-saturation",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
] satisfies readonly MetricDefinition[];
