import type { MetricDefinition } from "../types.ts";

export const LAB_METRICS = [
  {
    aliases: ["serum-albumin", "serum_albumin"],
    biomarkerKey: "biomarker:albumin",
    canonicalUnit: "g/dL",
    category: "lab",
    displayName: "Albumin",
    displayUnit: "g/dL",
    key: "albumin",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["serum-creatinine", "serum_creatinine"],
    biomarkerKey: "biomarker:creatinine",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "Creatinine",
    displayUnit: "mg/dL",
    key: "creatinine",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 2,
  },
  {
    aliases: [
      "estimated-glomerular-filtration-rate",
      "estimated_glomerular_filtration_rate",
      "glomerular-filtration-rate",
      "glomerular_filtration_rate",
      "egfr",
      "e-gfr",
    ],
    biomarkerKey: "biomarker:egfr",
    canonicalUnit: "mL/min/1.73m^2",
    category: "lab",
    displayName: "eGFR",
    displayUnit: "mL/min/1.73m^2",
    key: "egfr",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["blood-glucose", "blood_glucose", "fasting-glucose", "fasting_glucose"],
    biomarkerKey: "biomarker:blood-glucose",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "Glucose",
    displayUnit: "mg/dL",
    key: "glucose",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, preferFasting: true, staleAfterDays: 90 },
    valuePrecision: 0,
  },
  {
    aliases: ["apo-b", "apo_b", "apolipoprotein-b", "apolipoprotein_b", "apolipoprotein b"],
    biomarkerAliases: ["biomarker:apolipoprotein-b"],
    biomarkerKey: "biomarker:apob",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "ApoB",
    displayUnit: "mg/dL",
    key: "apob",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["ldl", "ldl_cholesterol", "ldl-cholesterol", "ldlc", "ldl_c"],
    biomarkerKey: "biomarker:ldl-c",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "LDL-C",
    displayUnit: "mg/dL",
    key: "ldl-c",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["hdl", "hdl_cholesterol", "hdl-cholesterol", "hdlc", "hdl_c"],
    biomarkerKey: "biomarker:hdl-c",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "HDL-C",
    displayUnit: "mg/dL",
    key: "hdl-c",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["tg", "triglyceride"],
    biomarkerKey: "biomarker:triglycerides",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "Triglycerides",
    displayUnit: "mg/dL",
    key: "triglycerides",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["a1c", "hb-a1c", "hba1c", "hemoglobin-a-1c", "hemoglobin-a1c", "hemoglobin_a1c"],
    biomarkerKey: "biomarker:hba1c",
    canonicalUnit: "percent",
    category: "lab",
    displayName: "HbA1c",
    displayUnit: "percent",
    key: "hba1c",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["alanine-aminotransferase", "alanine_aminotransferase"],
    biomarkerKey: "biomarker:alt",
    canonicalUnit: "U/L",
    category: "lab",
    displayName: "ALT",
    displayUnit: "U/L",
    key: "alt",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["aspartate-aminotransferase", "aspartate_aminotransferase"],
    biomarkerKey: "biomarker:ast",
    canonicalUnit: "U/L",
    category: "lab",
    displayName: "AST",
    displayUnit: "U/L",
    key: "ast",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["gamma-glutamyl-transferase", "gamma_glutamyl_transferase"],
    biomarkerKey: "biomarker:ggt",
    canonicalUnit: "U/L",
    category: "lab",
    displayName: "GGT",
    displayUnit: "U/L",
    key: "ggt",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["alk-phos", "alkaline-phos", "alkaline_phosphatase", "alp"],
    biomarkerKey: "biomarker:alkaline-phosphatase",
    canonicalUnit: "U/L",
    category: "lab",
    displayName: "Alkaline phosphatase",
    displayUnit: "U/L",
    key: "alkaline-phosphatase",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["crp", "hscrp", "hs_crp", "high-sensitivity-crp", "high_sensitivity_crp", "c-reactive-protein"],
    biomarkerKey: "biomarker:hs-crp",
    canonicalUnit: "mg/L",
    category: "lab",
    displayName: "hs-CRP",
    displayUnit: "mg/L",
    key: "hs-crp",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: [
      "leukocytes",
      "white-blood-cell-count-wbc",
      "white-blood-cells",
      "white_blood_cells",
      "wbc",
      "wbc-count",
    ],
    biomarkerKey: "biomarker:white-blood-cell-count",
    canonicalUnit: "10^3/uL",
    category: "lab",
    displayName: "White blood cells",
    displayUnit: "10^3/uL",
    key: "white-blood-cell-count",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: [
      "lymphocyte",
      "lymphocyte-percent",
      "lymphocyte-pct",
      "lymphocyte_pct",
      "lymphocyte-percentage",
      "lymphocytes-percent",
      "lymphocytes-pct",
      "lymphocytes",
    ],
    biomarkerKey: "biomarker:lymphocyte-percentage",
    canonicalUnit: "percent",
    category: "lab",
    displayName: "Lymphocytes",
    displayUnit: "%",
    key: "lymphocyte-percentage",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["mcv", "mean-corpuscular-volume"],
    biomarkerKey: "biomarker:mean-corpuscular-volume",
    canonicalUnit: "fL",
    category: "lab",
    displayName: "Mean corpuscular volume",
    displayUnit: "fL",
    key: "mean-corpuscular-volume",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["rdw", "rdw-cv", "red-cell-distribution-width", "red-cell-distribution-width-rdw", "red_cell_distribution_width"],
    biomarkerKey: "biomarker:red-cell-distribution-width",
    canonicalUnit: "percent",
    category: "lab",
    displayName: "Red cell distribution width",
    displayUnit: "%",
    key: "red-cell-distribution-width",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: [],
    biomarkerKey: "biomarker:ferritin",
    canonicalUnit: "ng/mL",
    category: "lab",
    displayName: "Ferritin",
    displayUnit: "ng/mL",
    key: "ferritin",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["serum-calcium", "serum_calcium", "total-calcium", "total_calcium"],
    biomarkerKey: "biomarker:calcium",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "Calcium",
    displayUnit: "mg/dL",
    key: "calcium",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["cholesterol", "cholesterol-total", "cholesterol_total", "total_cholesterol"],
    biomarkerKey: "biomarker:total-cholesterol",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "Total cholesterol",
    displayUnit: "mg/dL",
    key: "total-cholesterol",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["serum-uric-acid", "serum_uric_acid", "urate"],
    biomarkerKey: "biomarker:uric-acid",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "Uric acid",
    displayUnit: "mg/dL",
    key: "uric-acid",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["bilirubin", "bilirubin-total", "bilirubin_total", "total_bilirubin"],
    biomarkerKey: "biomarker:total-bilirubin",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "Total bilirubin",
    displayUnit: "mg/dL",
    key: "total-bilirubin",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
] satisfies readonly MetricDefinition[];
