import type { MetricDefinition } from "../types.ts";

interface SourceUnitLabMetricInput {
  aliases: readonly string[];
  biomarkerKey: string;
  displayName: string;
  key: string;
  valuePrecision?: number;
}

function sourceUnitLabMetric(input: SourceUnitLabMetricInput): MetricDefinition {
  return {
    ...input,
    canonicalUnit: null,
    category: "lab",
    displayUnit: null,
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: input.valuePrecision ?? 1,
  };
}

export const LAB_RESULT_METRICS = [
  {
    aliases: ["serum-albumin", "serum_albumin"],
    biomarkerKey: "biomarker:albumin",
    canonicalUnit: "g/dL",
    category: "lab",
    displayName: "Albumin",
    displayUnit: "g/dL",
    key: "albumin",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["serum-creatinine", "serum_creatinine"],
    biomarkerKey: "biomarker:creatinine",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "Creatinine",
    displayUnit: "mg/dL",
    key: "creatinine",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 2,
  },
  {
    aliases: ["bun", "serum-urea-nitrogen", "urea-nitrogen"],
    biomarkerAliases: [
      "biomarker:bun",
      "biomarker:serum-urea-nitrogen",
      "biomarker:urea-nitrogen",
    ],
    biomarkerKey: "biomarker:blood-urea-nitrogen",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "Blood urea nitrogen",
    displayUnit: "mg/dL",
    key: "blood-urea-nitrogen",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: [
      "estimated-glomerular-filtration-rate",
      "estimated_glomerular_filtration_rate",
      "glomerular-filtration-rate",
      "glomerular_filtration_rate",
      "egfr",
      "e-gfr",
      "estimated-gfr",
    ],
    biomarkerKey: "biomarker:egfr",
    canonicalUnit: "mL/min/1.73m^2",
    category: "lab",
    displayName: "eGFR",
    displayUnit: "mL/min/1.73m^2",
    key: "egfr",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["estimated-gfr-ckd-epi", "e-gfr-ckd-epi"],
    biomarkerKey: "biomarker:egfr-ckd-epi",
    canonicalUnit: "mL/min/1.73m^2",
    category: "lab",
    displayName: "eGFR (CKD-EPI)",
    displayUnit: "mL/min/1.73m^2",
    key: "egfr-ckd-epi",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["blood-glucose", "blood_glucose", "fasting-glucose", "fasting_glucose"],
    biomarkerKey: "biomarker:blood-glucose",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "Glucose",
    displayUnit: "mg/dL",
    key: "glucose",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, preferFasting: true, staleAfterDays: 90 },
    valuePrecision: 0,
  },
  {
    aliases: ["apo-b", "apo_b", "apolipoprotein-b", "apolipoprotein_b", "apolipoprotein b"],
    biomarkerAliases: ["biomarker:apolipoprotein-b"],
    biomarkerKey: "biomarker:apob",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "ApoB",
    displayUnit: "mg/dL",
    key: "apob",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: [
      "cholesterol-ldl",
      "ldl",
      "ldl_cholesterol",
      "ldl-cholesterol",
      "ldlc",
      "ldl_c",
    ],
    biomarkerKey: "biomarker:ldl-c",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "LDL-C",
    displayUnit: "mg/dL",
    key: "ldl-c",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["cholesterol-hdl", "hdl", "hdl_cholesterol", "hdl-cholesterol", "hdlc", "hdl_c"],
    biomarkerKey: "biomarker:hdl-c",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "HDL-C",
    displayUnit: "mg/dL",
    key: "hdl-c",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["tg", "triglyceride"],
    biomarkerKey: "biomarker:triglycerides",
    canonicalUnit: "mg/dL",
    category: "lab",
    displayName: "Triglycerides",
    displayUnit: "mg/dL",
    key: "triglycerides",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: [
      "a1c",
      "hb-a1c",
      "hb-a1c-ngsp",
      "hb-a1c-si",
      "hba1c",
      "hba1c-ngsp",
      "hba1c-si",
      "hemoglobin-a-1c",
      "hemoglobin-a1c",
      "hemoglobin_a1c",
    ],
    biomarkerKey: "biomarker:hba1c",
    canonicalUnit: "percent",
    category: "lab",
    displayName: "HbA1c",
    displayUnit: "percent",
    key: "hba1c",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: [
      "alanine-aminotransferase",
      "alanine-transaminase",
      "alanine_aminotransferase",
      "alt-sgpt",
      "sgpt",
    ],
    biomarkerKey: "biomarker:alt",
    canonicalUnit: "U/L",
    category: "lab",
    displayName: "ALT",
    displayUnit: "U/L",
    key: "alt",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: [
      "aspartate-aminotransferase",
      "aspartate-transaminase",
      "aspartate_aminotransferase",
      "ast-sgot",
      "sgot",
    ],
    biomarkerKey: "biomarker:ast",
    canonicalUnit: "U/L",
    category: "lab",
    displayName: "AST",
    displayUnit: "U/L",
    key: "ast",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["gamma-glutamyl-transferase", "gamma_glutamyl_transferase"],
    biomarkerKey: "biomarker:ggt",
    canonicalUnit: "U/L",
    category: "lab",
    displayName: "GGT",
    displayUnit: "U/L",
    key: "ggt",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["alk-phos", "alkaline-phos", "alkaline_phosphatase", "alp"],
    biomarkerKey: "biomarker:alkaline-phosphatase",
    canonicalUnit: "U/L",
    category: "lab",
    displayName: "Alkaline phosphatase",
    displayUnit: "U/L",
    key: "alkaline-phosphatase",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["crp", "hscrp", "hs_crp", "high-sensitivity-crp", "high_sensitivity_crp", "c-reactive-protein"],
    biomarkerKey: "biomarker:hs-crp",
    canonicalUnit: "mg/L",
    category: "lab",
    displayName: "hs-CRP",
    displayUnit: "mg/L",
    key: "hs-crp",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: [
      "leukocytes",
      "white-blood-cell",
      "white-blood-cell-count-wbc",
      "white-blood-cells",
      "white_blood_cells",
      "wbc",
      "wbc-count",
    ],
    biomarkerKey: "biomarker:white-blood-cell-count",
    canonicalUnit: "10^3/uL",
    category: "lab",
    displayName: "White blood cells",
    displayUnit: "10^3/uL",
    key: "white-blood-cell-count",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: [
      "lymphocyte",
      "lymphocyte-percent",
      "lymphocyte-pct",
      "lymphocyte_pct",
      "lymphocyte-percentage",
      "lymphocytes-percent",
      "lymphocytes-pct",
      "lymphocytes",
    ],
    biomarkerKey: "biomarker:lymphocyte-percentage",
    canonicalUnit: "percent",
    category: "lab",
    displayName: "Lymphocytes",
    displayUnit: "%",
    key: "lymphocyte-percentage",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["mch", "mean-cell-haemoglobin", "mean-corpuscular-haemoglobin"],
    biomarkerAliases: ["biomarker:mch"],
    biomarkerKey: "biomarker:mean-corpuscular-hemoglobin",
    canonicalUnit: "pg",
    category: "lab",
    displayName: "Mean corpuscular hemoglobin",
    displayUnit: "pg",
    key: "mean-corpuscular-hemoglobin",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: [
      "mchc",
      "mean-corpuscular-hb-concentration",
      "mean-corpuscular-haemoglobin-concentration",
    ],
    biomarkerAliases: ["biomarker:mchc"],
    biomarkerKey: "biomarker:mean-corpuscular-hemoglobin-concentration",
    canonicalUnit: "g/dL",
    category: "lab",
    displayName: "Mean corpuscular hemoglobin concentration",
    displayUnit: "g/dL",
    key: "mean-corpuscular-hemoglobin-concentration",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["mcv", "mean-cell-volume", "mean-corpuscular-volume"],
    biomarkerKey: "biomarker:mean-corpuscular-volume",
    canonicalUnit: "fL",
    category: "lab",
    displayName: "Mean corpuscular volume",
    displayUnit: "fL",
    key: "mean-corpuscular-volume",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["rdw", "rdw-cv", "red-cell-distribution-width", "red-cell-distribution-width-rdw", "red_cell_distribution_width"],
    biomarkerKey: "biomarker:red-cell-distribution-width",
    canonicalUnit: "percent",
    category: "lab",
    displayName: "Red cell distribution width",
    displayUnit: "%",
    key: "red-cell-distribution-width",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: [],
    biomarkerKey: "biomarker:ferritin",
    canonicalUnit: "ng/mL",
    category: "lab",
    displayName: "Ferritin",
    displayUnit: "ng/mL",
    key: "ferritin",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["thyrotropin", "tsh"],
    biomarkerAliases: ["biomarker:thyrotropin", "biomarker:tsh"],
    biomarkerKey: "biomarker:thyroid-stimulating-hormone",
    canonicalUnit: "mIU/L",
    category: "lab",
    displayName: "Thyroid-stimulating hormone",
    displayUnit: "mIU/L",
    key: "thyroid-stimulating-hormone",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 2,
  },
  {
    aliases: ["cholesterol-total", "total-cholesterol"],
    biomarkerKey: "biomarker:total-cholesterol",
    canonicalUnit: null,
    category: "lab",
    displayName: "Total cholesterol",
    displayUnit: null,
    key: "total-cholesterol",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["cholesterol-non-hdl", "non-hdl-c"],
    biomarkerKey: "biomarker:non-hdl-cholesterol",
    canonicalUnit: null,
    category: "lab",
    displayName: "Non-HDL cholesterol",
    displayUnit: null,
    key: "non-hdl-cholesterol",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["cholesterol-hdl-ratio"],
    biomarkerKey: "biomarker:cholesterol-hdl-ratio",
    canonicalUnit: null,
    category: "lab",
    displayName: "Cholesterol/HDL ratio",
    displayUnit: null,
    key: "cholesterol-hdl-ratio",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["vldl-cholesterol-cal", "calculated-vldl-cholesterol"],
    biomarkerKey: "biomarker:vldl-cholesterol-calculated",
    canonicalUnit: null,
    category: "lab",
    displayName: "Calculated VLDL cholesterol",
    displayUnit: null,
    key: "vldl-cholesterol-calculated",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["globulin", "globulin-total"],
    biomarkerKey: "biomarker:total-globulin",
    canonicalUnit: null,
    category: "lab",
    displayName: "Globulin",
    displayUnit: null,
    key: "total-globulin",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["bilirubin", "bilirubin-total"],
    biomarkerKey: "biomarker:total-bilirubin",
    canonicalUnit: null,
    category: "lab",
    displayName: "Total bilirubin",
    displayUnit: null,
    key: "total-bilirubin",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["fibrosis-score-fib4", "fibrosis-score-fib-4", "fib-4"],
    biomarkerKey: "biomarker:fib4",
    canonicalUnit: null,
    category: "lab",
    displayName: "FIB-4",
    displayUnit: null,
    key: "fib4",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 2,
  },
  {
    aliases: ["rbc", "red-blood-cell", "red-blood-cells"],
    biomarkerKey: "biomarker:red-blood-cell-count",
    canonicalUnit: null,
    category: "lab",
    displayName: "Red blood cells",
    displayUnit: null,
    key: "red-blood-cell-count",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 2,
  },
  {
    aliases: ["haemoglobin"],
    biomarkerKey: "biomarker:hemoglobin",
    canonicalUnit: null,
    category: "lab",
    displayName: "Hemoglobin",
    displayUnit: null,
    key: "hemoglobin",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["packed-cell-volume"],
    biomarkerKey: "biomarker:hematocrit",
    canonicalUnit: null,
    category: "lab",
    displayName: "Hematocrit",
    displayUnit: null,
    key: "hematocrit",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["platelet", "platelets"],
    biomarkerKey: "biomarker:platelet-count",
    canonicalUnit: null,
    category: "lab",
    displayName: "Platelets",
    displayUnit: null,
    key: "platelet-count",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["neutrophils", "neutrophils-percent", "neutrophils-relative"],
    biomarkerKey: "biomarker:neutrophil-percentage",
    canonicalUnit: null,
    category: "lab",
    displayName: "Neutrophils",
    displayUnit: null,
    key: "neutrophil-percentage",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["absolute-neutrophil-count", "anc", "neutrophils-absolute"],
    biomarkerKey: "biomarker:absolute-neutrophils",
    canonicalUnit: null,
    category: "lab",
    displayName: "Neutrophils, absolute",
    displayUnit: null,
    key: "absolute-neutrophils",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 2,
  },
  {
    aliases: ["absolute-lymphocytes", "lymphocytes-absolute"],
    biomarkerKey: "biomarker:absolute-lymphocytes",
    canonicalUnit: null,
    category: "lab",
    displayName: "Lymphocytes, absolute",
    displayUnit: null,
    key: "absolute-lymphocytes",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 2,
  },
  {
    aliases: ["monocytes", "monocytes-percent", "monocytes-relative"],
    biomarkerKey: "biomarker:monocyte-percentage",
    canonicalUnit: null,
    category: "lab",
    displayName: "Monocytes",
    displayUnit: null,
    key: "monocyte-percentage",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["monocytes-absolute"],
    biomarkerKey: "biomarker:absolute-monocytes",
    canonicalUnit: null,
    category: "lab",
    displayName: "Monocytes, absolute",
    displayUnit: null,
    key: "absolute-monocytes",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 2,
  },
  {
    aliases: ["eosinophils", "eosinophils-percent", "eosinophils-relative"],
    biomarkerKey: "biomarker:eosinophil-percentage",
    canonicalUnit: null,
    category: "lab",
    displayName: "Eosinophils",
    displayUnit: null,
    key: "eosinophil-percentage",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["eosinophils-absolute"],
    biomarkerKey: "biomarker:absolute-eosinophils",
    canonicalUnit: null,
    category: "lab",
    displayName: "Eosinophils, absolute",
    displayUnit: null,
    key: "absolute-eosinophils",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 2,
  },
  {
    aliases: ["basophils", "basophils-percent", "basophils-relative"],
    biomarkerKey: "biomarker:basophil-percentage",
    canonicalUnit: null,
    category: "lab",
    displayName: "Basophils",
    displayUnit: null,
    key: "basophil-percentage",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["basophils-absolute"],
    biomarkerKey: "biomarker:absolute-basophils",
    canonicalUnit: null,
    category: "lab",
    displayName: "Basophils, absolute",
    displayUnit: null,
    key: "absolute-basophils",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 2,
  },
  {
    aliases: ["immature-granulocytes"],
    biomarkerKey: "biomarker:immature-granulocyte-percentage",
    canonicalUnit: null,
    category: "lab",
    displayName: "Immature granulocytes",
    displayUnit: null,
    key: "immature-granulocyte-percentage",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["immature-grans-abs", "immature-granulocytes-absolute"],
    biomarkerKey: "biomarker:absolute-immature-granulocytes",
    canonicalUnit: null,
    category: "lab",
    displayName: "Immature granulocytes, absolute",
    displayUnit: null,
    key: "absolute-immature-granulocytes",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 2,
  },
  {
    aliases: ["vit-d-25-hydroxy", "vitamin-d-25-hydroxy", "25-hydroxy-vitamin-d"],
    biomarkerKey: "biomarker:vitamin-d",
    canonicalUnit: null,
    category: "lab",
    displayName: "Vitamin D",
    displayUnit: null,
    key: "vitamin-d",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["testosterone", "testosterone-total"],
    biomarkerKey: "biomarker:total-testosterone",
    canonicalUnit: null,
    category: "lab",
    displayName: "Total testosterone",
    displayUnit: null,
    key: "total-testosterone",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["testosterone-free"],
    biomarkerKey: "biomarker:free-testosterone",
    canonicalUnit: null,
    category: "lab",
    displayName: "Free testosterone",
    displayUnit: null,
    key: "free-testosterone",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["estradiol-e2"],
    biomarkerKey: "biomarker:estradiol",
    canonicalUnit: null,
    category: "lab",
    displayName: "Estradiol",
    displayUnit: null,
    key: "estradiol",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["iron-total", "serum-iron"],
    biomarkerKey: "biomarker:iron",
    canonicalUnit: null,
    category: "lab",
    displayName: "Iron",
    displayUnit: null,
    key: "iron",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  {
    aliases: ["iron-saturation", "transferrin-saturation"],
    biomarkerKey: "biomarker:iron-saturation",
    canonicalUnit: null,
    category: "lab",
    displayName: "Iron saturation",
    displayUnit: null,
    key: "iron-saturation",
    selectionPolicy: { kind: "latest-lab", preferCollectedAt: true, staleAfterDays: 365 },
    valuePrecision: 1,
  },
  sourceUnitLabMetric({
    aliases: ["c peptide", "c_peptide", "serum-c-peptide"],
    biomarkerKey: "biomarker:c-peptide",
    displayName: "C-peptide",
    key: "c-peptide",
    valuePrecision: 2,
  }),
  sourceUnitLabMetric({
    aliases: ["serum-insulin", "fasting-insulin"],
    biomarkerKey: "biomarker:insulin",
    displayName: "Insulin",
    key: "insulin",
  }),
  sourceUnitLabMetric({
    aliases: ["total-homocysteine"],
    biomarkerKey: "biomarker:homocysteine",
    displayName: "Homocysteine",
    key: "homocysteine",
  }),
  sourceUnitLabMetric({
    aliases: ["large-ldl-particles", "ldl-large"],
    biomarkerKey: "biomarker:ldl-large-particles",
    displayName: "LDL large particles",
    key: "ldl-large-particles",
    valuePrecision: 0,
  }),
  sourceUnitLabMetric({
    aliases: ["medium-ldl-particles", "ldl-medium"],
    biomarkerKey: "biomarker:ldl-medium-particles",
    displayName: "LDL medium particles",
    key: "ldl-medium-particles",
    valuePrecision: 0,
  }),
  sourceUnitLabMetric({
    aliases: ["ldl-p", "ldl-particle-concentration"],
    biomarkerKey: "biomarker:ldl-particle-number",
    displayName: "LDL particle number",
    key: "ldl-particle-number",
    valuePrecision: 0,
  }),
  sourceUnitLabMetric({
    aliases: ["ldl-size", "ldl-peak-particle-size"],
    biomarkerKey: "biomarker:ldl-peak-size",
    displayName: "LDL peak size",
    key: "ldl-peak-size",
  }),
  sourceUnitLabMetric({
    aliases: ["small-ldl-particles", "ldl-small"],
    biomarkerKey: "biomarker:ldl-small-particles",
    displayName: "LDL small particles",
    key: "ldl-small-particles",
    valuePrecision: 0,
  }),
  sourceUnitLabMetric({
    aliases: ["ldl-particle-pattern"],
    biomarkerKey: "biomarker:ldl-pattern",
    displayName: "LDL pattern",
    key: "ldl-pattern",
    valuePrecision: 0,
  }),
  sourceUnitLabMetric({
    aliases: ["lp-a", "lpa", "lipoprotein(a)"],
    biomarkerKey: "biomarker:lipoprotein-a",
    displayName: "Lipoprotein(a)",
    key: "lipoprotein-a",
  }),
  sourceUnitLabMetric({
    aliases: ["calculated-ldl", "ldl-c-calculated"],
    biomarkerKey: "biomarker:ldl-calculated",
    displayName: "LDL Calculated",
    key: "ldl-calculated",
  }),
  sourceUnitLabMetric({
    aliases: ["ldl-cholesterol-calculated-nih", "ldl-calc-nih", "sampson-nih-ldl"],
    biomarkerKey: "biomarker:ldl-chol-calc-nih",
    displayName: "LDL CHOL CALC (NIH)",
    key: "ldl-chol-calc-nih",
  }),
  sourceUnitLabMetric({
    aliases: ["troponin-i-poc", "point-of-care-troponin-i"],
    biomarkerKey: "biomarker:poc-troponin-i",
    displayName: "POC Troponin I",
    key: "poc-troponin-i",
    valuePrecision: 3,
  }),
  sourceUnitLabMetric({
    aliases: ["serum-uric-acid", "urate"],
    biomarkerKey: "biomarker:serum-uric-acid",
    displayName: "Uric acid",
    key: "uric-acid",
  }),
  sourceUnitLabMetric({
    aliases: ["protein-urine", "urine-protein-qualitative"],
    biomarkerKey: "biomarker:urine-protein",
    displayName: "Urine protein",
    key: "urine-protein",
  }),
  sourceUnitLabMetric({
    aliases: ["bun-creatinine-ratio", "blood-urea-nitrogen-creatinine-ratio"],
    biomarkerKey: "biomarker:bun-creatinine-ratio",
    displayName: "BUN/Creatinine Ratio",
    key: "bun-creatinine-ratio",
  }),
  sourceUnitLabMetric({
    aliases: ["gfr-mdrd-african-american", "mdrd-gfr-af-amer"],
    biomarkerKey: "biomarker:gfr-mdrd-af-amer",
    displayName: "GFR MDRD Af Amer",
    key: "gfr-mdrd-af-amer",
    valuePrecision: 0,
  }),
  sourceUnitLabMetric({
    aliases: ["gfr-mdrd-non-african-american", "mdrd-gfr-non-af-amer"],
    biomarkerKey: "biomarker:gfr-mdrd-non-af-amer",
    displayName: "GFR MDRD Non Af Amer",
    key: "gfr-mdrd-non-af-amer",
    valuePrecision: 0,
  }),
  sourceUnitLabMetric({
    aliases: ["random-urine-albumin-without-creatinine", "urine-microalbumin-random-without-creatinine"],
    biomarkerKey: "biomarker:urine-albumin-random-without-creatinine",
    displayName: "Urine albumin random without creatinine",
    key: "urine-albumin-random-without-creatinine",
  }),
  sourceUnitLabMetric({
    aliases: ["a-g-ratio", "albumin-to-globulin-ratio"],
    biomarkerKey: "biomarker:albumin-globulin-ratio",
    displayName: "Albumin/Globulin Ratio",
    key: "albumin-globulin-ratio",
    valuePrecision: 2,
  }),
  sourceUnitLabMetric({
    aliases: ["protein-total", "serum-total-protein"],
    biomarkerKey: "biomarker:total-protein",
    displayName: "Total Protein",
    key: "total-protein",
  }),
  sourceUnitLabMetric({
    aliases: ["triiodothyronine-free", "free-triiodothyronine"],
    biomarkerKey: "biomarker:free-t3",
    displayName: "Free T3",
    key: "free-t3",
    valuePrecision: 2,
  }),
  sourceUnitLabMetric({
    aliases: ["thyroxine-free", "free-thyroxine"],
    biomarkerKey: "biomarker:free-t4",
    displayName: "Free T4",
    key: "free-t4",
    valuePrecision: 2,
  }),
  sourceUnitLabMetric({
    aliases: ["thyroglobulin-antibody", "tg-antibodies", "tgab"],
    biomarkerKey: "biomarker:thyroglobulin-antibodies",
    displayName: "Thyroglobulin Antibodies",
    key: "thyroglobulin-antibodies",
  }),
  sourceUnitLabMetric({
    aliases: ["thyroid-peroxidase-antibody", "tpo-antibodies", "tpoab"],
    biomarkerKey: "biomarker:thyroid-peroxidase-antibodies",
    displayName: "Thyroid Peroxidase Antibodies",
    key: "thyroid-peroxidase-antibodies",
  }),
  sourceUnitLabMetric({
    aliases: ["mpv", "mean-platelet-volume"],
    biomarkerKey: "biomarker:mean-platelet-volume",
    displayName: "Mean Platelet Volume",
    key: "mean-platelet-volume",
  }),
  sourceUnitLabMetric({
    aliases: ["serum-cortisol", "plasma-cortisol"],
    biomarkerKey: "biomarker:cortisol",
    displayName: "Cortisol",
    key: "cortisol",
  }),
  sourceUnitLabMetric({
    aliases: ["dheas", "dhea-s", "dehydroepiandrosterone-sulfate"],
    biomarkerKey: "biomarker:dhea-sulfate",
    displayName: "DHEA sulfate",
    key: "dhea-sulfate",
  }),
  sourceUnitLabMetric({
    aliases: ["shbg", "sex-hormone-binding-globulin"],
    biomarkerKey: "biomarker:sex-hormone-binding-globulin",
    displayName: "Sex Hormone Binding Globulin",
    key: "sex-hormone-binding-globulin",
  }),
  sourceUnitLabMetric({
    aliases: ["fsh", "follicle-stimulating-hormone"],
    biomarkerKey: "biomarker:follicle-stimulating-hormone",
    displayName: "Follicle Stimulating Hormone",
    key: "follicle-stimulating-hormone",
  }),
  sourceUnitLabMetric({
    aliases: ["lh", "luteinizing-hormone"],
    biomarkerKey: "biomarker:luteinizing-hormone",
    displayName: "Luteinizing Hormone",
    key: "luteinizing-hormone",
  }),
  sourceUnitLabMetric({
    aliases: ["serum-prolactin"],
    biomarkerKey: "biomarker:prolactin",
    displayName: "Prolactin",
    key: "prolactin",
  }),
  sourceUnitLabMetric({
    aliases: ["omega-3-total-omega-check", "omega3-total-omegacheck"],
    biomarkerKey: "biomarker:omega-3-total-omegacheck",
    displayName: "Omega-3 Total / OmegaCheck",
    key: "omega-3-total-omegacheck",
  }),
  sourceUnitLabMetric({
    aliases: ["aa-fatty-acid"],
    biomarkerKey: "biomarker:arachidonic-acid",
    displayName: "Arachidonic Acid",
    key: "arachidonic-acid",
  }),
  sourceUnitLabMetric({
    aliases: ["aa-epa-ratio", "arachidonic-acid-to-epa-ratio"],
    biomarkerKey: "biomarker:arachidonic-acid-epa-ratio",
    displayName: "Arachidonic Acid/EPA Ratio",
    key: "arachidonic-acid-epa-ratio",
  }),
  sourceUnitLabMetric({
    aliases: ["docosahexaenoic-acid"],
    biomarkerKey: "biomarker:dha",
    displayName: "DHA",
    key: "dha",
  }),
  sourceUnitLabMetric({
    aliases: ["docosapentaenoic-acid"],
    biomarkerKey: "biomarker:dpa",
    displayName: "DPA",
    key: "dpa",
  }),
  sourceUnitLabMetric({
    aliases: ["eicosapentaenoic-acid"],
    biomarkerKey: "biomarker:epa",
    displayName: "EPA",
    key: "epa",
  }),
  sourceUnitLabMetric({
    aliases: ["la-fatty-acid"],
    biomarkerKey: "biomarker:linoleic-acid",
    displayName: "Linoleic Acid",
    key: "linoleic-acid",
  }),
  sourceUnitLabMetric({
    aliases: ["rbc-magnesium", "magnesium-red-blood-cell"],
    biomarkerKey: "biomarker:magnesium-rbc",
    displayName: "Magnesium RBC",
    key: "magnesium-rbc",
  }),
  sourceUnitLabMetric({
    aliases: ["mma", "methylmalonate"],
    biomarkerKey: "biomarker:methylmalonic-acid",
    displayName: "Methylmalonic Acid",
    key: "methylmalonic-acid",
  }),
  sourceUnitLabMetric({
    aliases: ["omega-6-to-3-ratio", "omega6-omega3-ratio"],
    biomarkerKey: "biomarker:omega-6-3-ratio",
    displayName: "Omega 6/3 Ratio",
    key: "omega-6-3-ratio",
  }),
  sourceUnitLabMetric({
    aliases: ["tibc", "iron-binding-capacity-total"],
    biomarkerKey: "biomarker:total-iron-binding-capacity",
    displayName: "Total Iron Binding Capacity",
    key: "total-iron-binding-capacity",
  }),
  sourceUnitLabMetric({
    aliases: ["serum-zinc", "plasma-zinc"],
    biomarkerKey: "biomarker:zinc",
    displayName: "Zinc",
    key: "zinc",
  }),
  sourceUnitLabMetric({
    aliases: ["total-omega-6", "omega6-total"],
    biomarkerKey: "biomarker:omega-6-total",
    displayName: "Omega-6 total",
    key: "omega-6-total",
  }),
  sourceUnitLabMetric({
    aliases: ["omega-check-total"],
    biomarkerKey: "biomarker:omegacheck-total",
    displayName: "OmegaCheck total",
    key: "omegacheck-total",
  }),
  sourceUnitLabMetric({
    aliases: ["antinuclear-antibody-screen", "antinuclear-antibodies-screen"],
    biomarkerKey: "biomarker:ana-screen",
    displayName: "ANA screen",
    key: "ana-screen",
    valuePrecision: 0,
  }),
  sourceUnitLabMetric({
    aliases: ["rf", "rheumatoid-factor"],
    biomarkerKey: "biomarker:rheumatoid-factor",
    displayName: "Rheumatoid Factor",
    key: "rheumatoid-factor",
  }),
  sourceUnitLabMetric({
    aliases: ["corrected-calcium", "albumin-adjusted-calcium"],
    biomarkerKey: "biomarker:adjusted-calcium",
    displayName: "Adjusted Calcium",
    key: "adjusted-calcium",
  }),
  sourceUnitLabMetric({
    aliases: ["serum-calcium", "total-calcium"],
    biomarkerKey: "biomarker:calcium",
    displayName: "Calcium",
    key: "calcium",
  }),
  sourceUnitLabMetric({
    aliases: ["co2", "carbon-dioxide", "total-co2"],
    biomarkerKey: "biomarker:carbon-dioxide",
    displayName: "Carbon Dioxide",
    key: "carbon-dioxide",
  }),
  sourceUnitLabMetric({
    aliases: ["serum-chloride"],
    biomarkerKey: "biomarker:chloride",
    displayName: "Chloride",
    key: "chloride",
  }),
  sourceUnitLabMetric({
    aliases: ["phosphorus", "serum-phosphate"],
    biomarkerKey: "biomarker:phosphate",
    displayName: "Phosphate",
    key: "phosphate",
  }),
  sourceUnitLabMetric({
    aliases: ["serum-potassium"],
    biomarkerKey: "biomarker:potassium",
    displayName: "Potassium",
    key: "potassium",
  }),
  sourceUnitLabMetric({
    aliases: ["serum-sodium"],
    biomarkerKey: "biomarker:sodium",
    displayName: "Sodium",
    key: "sodium",
  }),
  sourceUnitLabMetric({
    aliases: ["anion-gap-without-potassium"],
    biomarkerKey: "biomarker:anion-gap",
    displayName: "Anion Gap",
    key: "anion-gap",
  }),
  sourceUnitLabMetric({
    aliases: ["ck", "total-ck", "creatine-phosphokinase", "cpk"],
    biomarkerKey: "biomarker:creatine-kinase",
    displayName: "Creatine Kinase",
    key: "creatine-kinase",
    valuePrecision: 0,
  }),
  sourceUnitLabMetric({
    aliases: ["lactate-dehydrogenase", "lactic-dehydrogenase"],
    biomarkerKey: "biomarker:ldh",
    displayName: "LDH",
    key: "ldh",
    valuePrecision: 0,
  }),
  sourceUnitLabMetric({
    aliases: ["blood-lead", "blood-lead-level"],
    biomarkerKey: "biomarker:lead",
    displayName: "Lead",
    key: "lead",
  }),
  sourceUnitLabMetric({
    aliases: ["total-mercury"],
    biomarkerKey: "biomarker:mercury",
    displayName: "Mercury",
    key: "mercury",
  }),
  sourceUnitLabMetric({
    aliases: ["free-psa", "prostate-specific-antigen-free"],
    biomarkerKey: "biomarker:psa-free",
    displayName: "PSA free",
    key: "psa-free",
    valuePrecision: 2,
  }),
  sourceUnitLabMetric({
    aliases: ["percent-free-psa", "free-psa-percent"],
    biomarkerKey: "biomarker:psa-percent-free",
    displayName: "PSA percent free",
    key: "psa-percent-free",
  }),
  sourceUnitLabMetric({
    aliases: ["total-psa", "prostate-specific-antigen-total"],
    biomarkerKey: "biomarker:psa-total",
    displayName: "PSA total",
    key: "psa-total",
    valuePrecision: 2,
  }),
] satisfies readonly MetricDefinition[];

/**
 * The general metric catalog intentionally retains its pre-existing lab
 * surface. The broader result catalog above is resolved only while projecting
 * test results, so recognizing a lab label cannot revoke manual measurements,
 * metric samples, goals, or experiment bindings that use the same words.
 */
const GLOBAL_LAB_ALIASES_BY_KEY: Readonly<Record<string, readonly string[]>> = {
  albumin: ["serum-albumin", "serum_albumin"],
  "blood-urea-nitrogen": ["bun", "serum-urea-nitrogen", "urea-nitrogen"],
  creatinine: ["serum-creatinine", "serum_creatinine"],
  egfr: [
    "estimated-glomerular-filtration-rate",
    "estimated_glomerular_filtration_rate",
    "glomerular-filtration-rate",
    "glomerular_filtration_rate",
    "egfr",
    "e-gfr",
  ],
  glucose: ["blood-glucose", "blood_glucose", "fasting-glucose", "fasting_glucose"],
  apob: ["apo-b", "apo_b", "apolipoprotein-b", "apolipoprotein_b", "apolipoprotein b"],
  "ldl-c": ["ldl", "ldl_cholesterol", "ldl-cholesterol", "ldlc", "ldl_c"],
  "hdl-c": ["hdl", "hdl_cholesterol", "hdl-cholesterol", "hdlc", "hdl_c"],
  triglycerides: ["tg", "triglyceride"],
  hba1c: ["a1c", "hb-a1c", "hba1c", "hemoglobin-a-1c", "hemoglobin-a1c", "hemoglobin_a1c"],
  alt: ["alanine-aminotransferase", "alanine_aminotransferase"],
  ast: ["aspartate-aminotransferase", "aspartate_aminotransferase"],
  ggt: ["gamma-glutamyl-transferase", "gamma_glutamyl_transferase"],
  "alkaline-phosphatase": ["alk-phos", "alkaline-phos", "alkaline_phosphatase", "alp"],
  "hs-crp": ["crp", "hscrp", "hs_crp", "high-sensitivity-crp", "high_sensitivity_crp", "c-reactive-protein"],
  "white-blood-cell-count": [
    "leukocytes",
    "white-blood-cell-count-wbc",
    "white-blood-cells",
    "white_blood_cells",
    "wbc",
    "wbc-count",
  ],
  "lymphocyte-percentage": [
    "lymphocyte",
    "lymphocyte-percent",
    "lymphocyte-pct",
    "lymphocyte_pct",
    "lymphocyte-percentage",
    "lymphocytes-percent",
    "lymphocytes-pct",
    "lymphocytes",
  ],
  "mean-corpuscular-hemoglobin": ["mch"],
  "mean-corpuscular-hemoglobin-concentration": ["mchc"],
  "mean-corpuscular-volume": ["mcv", "mean-corpuscular-volume"],
  "red-cell-distribution-width": [
    "rdw",
    "rdw-cv",
    "red-cell-distribution-width",
    "red-cell-distribution-width-rdw",
    "red_cell_distribution_width",
  ],
  "thyroid-stimulating-hormone": ["thyrotropin", "tsh"],
  ferritin: [],
};

export const LAB_METRICS = LAB_RESULT_METRICS.flatMap((definition) => {
  const aliases = GLOBAL_LAB_ALIASES_BY_KEY[definition.key];
  return aliases ? [{ ...definition, aliases }] : [];
}) satisfies readonly MetricDefinition[];
