import type { MetricDefinition } from "../types.ts";

/** Sparse physiological/event measurements shared by device and manual paths. */
export const PHYSIOLOGY_METRICS = [
  {
    aliases: ["carbohydrate", "carbohydrates", "carbohydrate-grams", "carbohydrates_g"],
    biomarkerKey: null,
    canonicalUnit: "g",
    category: "custom",
    displayName: "Carbohydrates",
    displayUnit: "g",
    key: "carbohydrates",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 45 },
    valuePrecision: 1,
  },
  {
    aliases: ["fev1", "forced_expiratory_volume_1", "forced-expiratory-volume-one"],
    biomarkerKey: null,
    canonicalUnit: "L",
    category: "function",
    displayName: "Forced expiratory volume in one second",
    displayUnit: "L",
    key: "forced-expiratory-volume-1",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 90 },
    valuePrecision: 2,
  },
  {
    aliases: ["fvc", "forced_vital_capacity"],
    biomarkerKey: null,
    canonicalUnit: "L",
    category: "function",
    displayName: "Forced vital capacity",
    displayUnit: "L",
    key: "forced-vital-capacity",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 90 },
    valuePrecision: 2,
  },
  {
    aliases: ["peak-flow", "peak_flow", "peak_expiratory_flow_rate", "pefr"],
    biomarkerKey: null,
    canonicalUnit: "L/min",
    category: "function",
    displayName: "Peak expiratory flow rate",
    displayUnit: "L/min",
    key: "peak-expiratory-flow-rate",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 90 },
    valuePrecision: 0,
  },
  {
    aliases: ["heart_rate_alert", "heart-alert-count"],
    biomarkerKey: null,
    canonicalUnit: "count",
    category: "vital",
    displayName: "Heart-rate alert count",
    displayUnit: "count",
    key: "heart-rate-alert",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 90 },
    valuePrecision: 0,
  },
  {
    aliases: ["inhaler_usage", "inhaler-use", "inhaler-use-count"],
    biomarkerKey: null,
    canonicalUnit: "count",
    category: "custom",
    displayName: "Inhaler usage",
    displayUnit: "count",
    key: "inhaler-usage",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 90 },
    valuePrecision: 0,
  },
  {
    aliases: ["sleep_apnea_alert", "sleep-apnea-alert-count"],
    biomarkerKey: null,
    canonicalUnit: "count",
    category: "sleep",
    displayName: "Sleep-apnea alert count",
    displayUnit: "count",
    key: "sleep-apnea-alert",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 90 },
    valuePrecision: 0,
  },
] satisfies readonly MetricDefinition[];
