import type { MetricDefinition } from "../types.ts";

export const PROXY_METRICS = [
  {
    aliases: ["self-rated-health", "self_rated_health", "srh"],
    biomarkerKey: null,
    canonicalUnit: "score",
    category: "custom",
    displayName: "Self-rated health",
    displayUnit: "score",
    key: "self-rated-health",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["hypertension_history_proxy_yes", "hypertension-history", "hypertension-history-yes"],
    biomarkerKey: null,
    canonicalUnit: "binary",
    category: "custom",
    displayName: "Hypertension history",
    displayUnit: "binary",
    key: "hypertension-history-proxy-yes",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["diabetes_history_proxy_yes", "diabetes-history", "diabetes-history-yes"],
    biomarkerKey: null,
    canonicalUnit: "binary",
    category: "custom",
    displayName: "Diabetes history",
    displayUnit: "binary",
    key: "diabetes-history-proxy-yes",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["smoking_status_proxy", "smoking-status", "smoking-status-code"],
    biomarkerKey: null,
    canonicalUnit: "score",
    category: "custom",
    displayName: "Smoking status",
    displayUnit: "score",
    key: "smoking-status-proxy",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 365 },
    valuePrecision: 0,
  },
  {
    aliases: ["physical_activity_proxy", "physical-activity", "physical-activity-code"],
    biomarkerKey: null,
    canonicalUnit: "score",
    category: "custom",
    displayName: "Physical activity proxy",
    displayUnit: "score",
    key: "physical-activity-proxy",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 365 },
    valuePrecision: 0,
  },
] satisfies readonly MetricDefinition[];
