import type { MetricDefinition } from "../types.ts";

export const SLEEP_METRICS = [
  {
    aliases: ["deep", "deep_minutes", "deepMinutes", "deep-sleep", "deep_sleep"],
    biomarkerKey: "biomarker:deep-sleep-minutes",
    canonicalUnit: "minutes",
    category: "sleep",
    displayName: "Deep sleep",
    displayUnit: "minutes",
    key: "deep-sleep-minutes",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    trendPolicy: { aggregation: "median", comparisonWindowDays: 30, latestWindowDays: 7, minimumPoints: 5 },
    valuePrecision: 0,
  },
  {
    aliases: ["rem", "rem_minutes", "remMinutes", "rem-sleep", "rem_sleep"],
    biomarkerKey: "biomarker:rem-sleep-minutes",
    canonicalUnit: "minutes",
    category: "sleep",
    displayName: "REM sleep",
    displayUnit: "minutes",
    key: "rem-sleep-minutes",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    trendPolicy: { aggregation: "median", comparisonWindowDays: 30, latestWindowDays: 7, minimumPoints: 5 },
    valuePrecision: 0,
  },
  {
    aliases: ["sleep_duration", "sleep-duration", "total-sleep-time", "total_sleep_time", "totalSleepMinutes", "total_sleep_minutes", "total-minutes", "totalMinutes"],
    biomarkerKey: null,
    canonicalUnit: "minutes",
    category: "sleep",
    displayName: "Total sleep",
    displayUnit: "minutes",
    key: "total-sleep-minutes",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["sleep-quality", "sleep_quality", "sleepScore", "sleep_score"],
    biomarkerKey: null,
    canonicalUnit: "score",
    category: "sleep",
    displayName: "Sleep score",
    displayUnit: "score",
    key: "sleep-score",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
] satisfies readonly MetricDefinition[];
