import type { MetricDefinition } from "../types.ts";

export const SLEEP_METRICS = [
  {
    aliases: ["deep", "deep_minutes", "deepMinutes", "deep-sleep", "deep_sleep"],
    biomarkerKey: "biomarker:deep-sleep-minutes",
    canonicalUnit: "minutes",
    category: "sleep",
    displayName: "Deep sleep",
    displayUnit: "minutes",
    key: "deep-sleep-minutes",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    trendPolicy: { aggregation: "median", comparisonWindowDays: 30, latestWindowDays: 7, minimumPoints: 5 },
    valuePrecision: 0,
  },
  {
    aliases: ["rem", "rem_minutes", "remMinutes", "rem-sleep", "rem_sleep"],
    biomarkerKey: "biomarker:rem-sleep-minutes",
    canonicalUnit: "minutes",
    category: "sleep",
    displayName: "REM sleep",
    displayUnit: "minutes",
    key: "rem-sleep-minutes",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    trendPolicy: { aggregation: "median", comparisonWindowDays: 30, latestWindowDays: 7, minimumPoints: 5 },
    valuePrecision: 0,
  },
  {
    aliases: [
      "sleep_duration",
      "sleep-duration",
      "sleep-duration-hours",
      "sleep_duration_hours",
      "sleep-hours",
      "sleep_hours",
      "total-sleep-hours",
      "total_sleep_hours",
      "total-sleep-time",
      "total_sleep_time",
      "totalSleepMinutes",
      "total_sleep_minutes",
      "total-minutes",
      "totalMinutes",
    ],
    biomarkerKey: null,
    canonicalUnit: "minutes",
    category: "sleep",
    displayName: "Total sleep",
    displayUnit: "minutes",
    key: "total-sleep-minutes",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["sleep-duration-variability", "sleep_duration_variability", "sleep-duration-sd", "sleep_duration_sd"],
    biomarkerKey: null,
    canonicalUnit: "minutes",
    category: "sleep",
    displayName: "Sleep duration variability",
    displayUnit: "minutes",
    key: "sleep-duration-variability-minutes",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["sleep_efficiency", "sleep-efficiency-percent", "sleepEfficiency"],
    biomarkerKey: null,
    canonicalUnit: "percent",
    category: "sleep",
    displayName: "Sleep efficiency",
    displayUnit: "%",
    key: "sleep-efficiency",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 1,
  },
  {
    aliases: ["valid-nights-28d", "wearable_valid_night_count_28d", "wearable-valid-nights-28d"],
    biomarkerKey: null,
    canonicalUnit: "count",
    category: "sleep",
    displayName: "Wearable valid nights",
    displayUnit: "nights",
    key: "wearable-valid-night-count-28d",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["sleep-quality", "sleep_quality", "sleepScore", "sleep_score"],
    biomarkerKey: null,
    canonicalUnit: "score",
    category: "sleep",
    displayName: "Sleep score",
    displayUnit: "score",
    key: "sleep-score",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: ["sleep-regularity", "sleep_regularity", "sleepRegularity", "sleep-regularity-index"],
    biomarkerKey: null,
    canonicalUnit: "score",
    category: "sleep",
    displayName: "Sleep regularity",
    displayUnit: "score",
    key: "sleep-regularity-score",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
  {
    aliases: [
      "sleep-midpoint-variability",
      "sleep_midpoint_variability",
      "sleep-midpoint-variability-minutes",
      "sleep_midpoint_variability_minutes",
      "sleep-timing-variability",
    ],
    biomarkerKey: null,
    canonicalUnit: "minutes",
    category: "sleep",
    displayName: "Sleep timing variability",
    displayUnit: "minutes",
    key: "sleep-midpoint-variability-minutes",
    selectionPolicy: { kind: "latest-valid", staleAfterDays: 14 },
    valuePrecision: 0,
  },
] satisfies readonly MetricDefinition[];
