export const MURPH_ASSISTANT_SKILLS_ROOT_ENV =
  'MURPH_ASSISTANT_SKILLS_ROOT' as const

export const MURPH_ASSISTANT_CLI_SURFACE_PREBUILT_ARTIFACT_PATH_ENV =
  'MURPH_ASSISTANT_CLI_SURFACE_PREBUILT_ARTIFACT_PATH' as const
