// Legacy internal shim while inbox runtime ownership lives in @murphai/inbox-services.
export { createIntegratedInboxServices } from '@murphai/inbox-services'

export type {
  CanonicalAttachmentPromotionResult,
  CanonicalPromotionLookupSpec,
  CanonicalPromotionLookupTarget,
  CanonicalPromotionManifest,
  CanonicalPromotionMatch,
  ConfiguredParserRegistryRuntime,
  CoreRuntimeModule,
  EmailDriver,
  ImessageDriver,
  InboxServices,
  InboxSourceSetEnabledResult,
  InboxParserServiceRuntime,
  InboxPaths,
  InboxPipeline,
  InboxRunEvent,
  InboxRuntimeModule,
  ParserDoctorRuntimeReport,
  ParserRuntimeDrainResult,
  ParserToolRuntimeStatus,
  ParsersRuntimeModule,
  PersistedCapture,
  PollConnector,
  PromotionScope,
  PromotionStore,
  PromotionTarget,
  RuntimeAttachmentParseJobRecord,
  RuntimeAttachmentRecord,
  RuntimeCaptureRecord,
  RuntimeCaptureRecordInput,
  RuntimeSearchHit,
  RuntimeStore,
  TelegramDriver,
} from '@murphai/inbox-services'
