export {
  getKnowledgePage,
  lintKnowledgePages,
  listKnowledgePages,
  rebuildKnowledgeIndex,
  searchKnowledgePages,
  tailKnowledgeLog,
  upsertKnowledgePage,
  type KnowledgeGetInput,
  type KnowledgeListInput,
  type KnowledgeLogTailInput,
  type KnowledgeMaintenanceInput,
  type KnowledgeSearchInput,
  type KnowledgeServiceDependencies,
  type KnowledgeUpsertInput,
} from './knowledge/service.js'
