export const HOSTED_IDLE_COMPACT_MIN_THREAD_TOKENS = 90_000;
export const HOSTED_GROUP_IDLE_COMPACT_MIN_THREAD_TOKENS = 50_000;
export const HOSTED_IDLE_COMPACT_TIMEOUT_MS = 120_000;
export const HOSTED_INTEGRATION_INGEST_ARCHIVE_TIMEOUT_MS = 30_000;
